// Batch export service (generated by OpenClaw)
import 'dart:io';
import 'dart:typed_data';
import 'package:flutter/foundation.dart' show kDebugMode, kIsWeb;
import 'package:flutter/material.dart';
import 'package:image/image.dart' as img;
import 'package:flutter_fractals/core/models/export_options.dart';
import 'package:flutter_fractals/core/models/fractal_preset.dart';
import 'package:flutter_fractals/core/services/export/export_service.dart';
import 'package:flutter_fractals/shared/utils/slugify.dart';

class BatchExportItemResult {
  final FractalPreset preset;
  final File file;
  final int index;

  const BatchExportItemResult({
    required this.preset,
    required this.file,
    required this.index,
  });
}

class BatchExportResult {
  final Directory directory;
  final List<BatchExportItemResult> items;
  final File? contactSheet;

  const BatchExportResult({
    required this.directory,
    required this.items,
    this.contactSheet,
  });
}

class BatchExportPlanEntry {
  final FractalPreset preset;
  final int sourceIndex;
  final int exportIndex;

  const BatchExportPlanEntry({
    required this.preset,
    required this.sourceIndex,
    required this.exportIndex,
  });
}

class BatchExportPlan {
  final List<BatchExportPlanEntry> entries;

  const BatchExportPlan._(this.entries);

  int get total => entries.length;

  static BatchExportPlan forModule({
    required String moduleId,
    required List<FractalPreset> presets,
  }) {
    final entries = <BatchExportPlanEntry>[];
    for (var sourceIndex = 0; sourceIndex < presets.length; sourceIndex++) {
      final preset = presets[sourceIndex];
      if (preset.moduleId != moduleId) continue;
      entries.add(
        BatchExportPlanEntry(
          preset: preset,
          sourceIndex: sourceIndex,
          exportIndex: entries.length,
        ),
      );
    }
    return BatchExportPlan._(List.unmodifiable(entries));
  }
}

/// Replayable final progress/status for a batch export run.
///
/// Cancellation can occur after a subset of planned presets has been written.
/// Keep that completion state explicit so partial runs are not reported as a
/// successful 100% `Done` export.
class BatchExportCompletion {
  final int completedItems;
  final int plannedItems;
  final bool wasCancelled;

  const BatchExportCompletion({
    required this.completedItems,
    required this.plannedItems,
    required this.wasCancelled,
  })  : assert(completedItems >= 0),
        assert(plannedItems >= 0);

  int get _boundedCompletedItems {
    if (plannedItems <= 0) return 0;
    return completedItems.clamp(0, plannedItems).toInt();
  }

  double get progress {
    if (!wasCancelled || plannedItems <= 0) return 1.0;
    return (_boundedCompletedItems / plannedItems).clamp(0.0, 1.0).toDouble();
  }

  String get status {
    if (!wasCancelled) return 'Done';
    if (plannedItems <= 0) return 'Cancelled';
    return 'Cancelled after $_boundedCompletedItems/$plannedItems';
  }
}

/// Replayable capture options and output path for one batch item.
///
/// Batch export goes through the same encoder as single-image export, where
/// WebP currently resolves to PNG. Keeping the effective format in this plan
/// prevents PNG bytes from being written to a stale `.webp` filename and keeps
/// metadata timestamps tied to the injected batch clock.
class BatchExportCapturePlan {
  final ExportOptions captureOptions;
  final String filename;
  final ExportMetadata? metadata;

  const BatchExportCapturePlan({
    required this.captureOptions,
    required this.filename,
    this.metadata,
  });

  factory BatchExportCapturePlan.forEntry({
    required BatchExportPlanEntry entry,
    required ExportOptions baseOptions,
    required ExportFormat effectiveFormat,
    required String moduleId,
    required String moduleDisplayName,
    required Map<String, Object> parameters,
    required DateTime createdAt,
  }) {
    final preset = entry.preset;
    final metadata = baseOptions.embedMetadata
        ? ExportMetadata(
            title: preset.name,
            description: 'Preset export from $moduleDisplayName',
            fractalType: moduleId,
            parameters: parameters,
            createdAt: createdAt,
          )
        : null;

    return BatchExportCapturePlan(
      captureOptions: baseOptions.copyWith(
        format: effectiveFormat,
        metadata: metadata,
      ),
      filename: BatchExportPresetFilename(
        moduleId: moduleId,
        index: entry.exportIndex,
        presetName: preset.name,
        format: effectiveFormat,
      ).value,
      metadata: metadata,
    );
  }
}

/// Replayable filename contract for one batch preset image.
class BatchExportPresetFilename {
  final String moduleId;
  final int index;
  final String presetName;
  final ExportFormat format;

  const BatchExportPresetFilename({
    required this.moduleId,
    required this.index,
    required this.presetName,
    required this.format,
  });

  String get value {
    final idx = (index + 1).toString().padLeft(3, '0');
    final slug = slugify(presetName, emptyFallback: 'untitled')!;
    return '${slugify(moduleId, emptyFallback: 'untitled')!}_${idx}_$slug.${format.extension}';
  }
}

/// Clock contract for replayable batch export directory naming.
abstract class BatchExportClock {
  DateTime now();
}

class SystemBatchExportClock implements BatchExportClock {
  const SystemBatchExportClock();

  @override
  DateTime now() => DateTime.now();
}

/// Frame-pump contract for replayable batch export tests.
abstract class BatchExportFramePump {
  Future<void> waitForPresetRender();
}

class WidgetsBindingBatchExportFramePump implements BatchExportFramePump {
  const WidgetsBindingBatchExportFramePump();

  @override
  Future<void> waitForPresetRender() async {
    await WidgetsBinding.instance.endOfFrame;
    await WidgetsBinding.instance.endOfFrame;
  }
}

class BatchExportService {
  final ExportService _exportService;
  final BatchExportClock _clock;
  final BatchExportFramePump _framePump;

  const BatchExportService({
    ExportService exportService = const ExportService(),
    BatchExportClock clock = const SystemBatchExportClock(),
    BatchExportFramePump framePump = const WidgetsBindingBatchExportFramePump(),
  })  : _exportService = exportService,
        _clock = clock,
        _framePump = framePump;

  Future<BatchExportResult> exportPresets({
    required GlobalKey boundaryKey,
    required Future<void> Function(FractalPreset preset) applyPreset,
    required List<FractalPreset> presets,
    required ExportOptions options,
    required double screenWidth,
    required double screenHeight,
    required String moduleId,
    required String moduleDisplayName,
    required Map<String, Object> Function() currentParameters,
    required void Function(double overallProgress, String status)? onProgress,
    required void Function(BatchExportItemResult item)? onItemDone,
    required bool Function() isCancelled,
  }) async {
    if (kIsWeb) throw UnsupportedError('exportPresets is not supported on web');
    final directory = await _createBatchDirectory(moduleId: moduleId);
    final results = <BatchExportItemResult>[];
    final plan =
        BatchExportPlan.forModule(moduleId: moduleId, presets: presets);
    final effectiveFormat =
        _exportService.resolveEffectiveFormat(options.format);
    var wasCancelled = false;

    for (final entry in plan.entries) {
      if (isCancelled()) {
        wasCancelled = true;
        break;
      }

      final preset = entry.preset;
      onProgress?.call(
        entry.exportIndex / plan.total,
        'Exporting ${entry.exportIndex + 1}/${plan.total}: ${preset.name}',
      );

      await applyPreset(preset);
      await _framePump.waitForPresetRender();

      final capturePlan = BatchExportCapturePlan.forEntry(
        entry: entry,
        baseOptions: options,
        effectiveFormat: effectiveFormat,
        moduleId: moduleId,
        moduleDisplayName: moduleDisplayName,
        parameters: options.embedMetadata
            ? Map<String, Object>.from(currentParameters())
            : const <String, Object>{},
        createdAt: _clock.now(),
      );

      final bytes = await _exportService.captureWithOptions(
        boundaryKey,
        options: capturePlan.captureOptions,
        screenWidth: screenWidth,
        screenHeight: screenHeight,
      );

      final file = File('${directory.path}/${capturePlan.filename}');
      await file.writeAsBytes(bytes, flush: true);

      final item = BatchExportItemResult(
        preset: preset,
        file: file,
        index: entry.exportIndex,
      );
      results.add(item);
      onItemDone?.call(item);
    }

    File? contactSheet;
    if (results.isNotEmpty) {
      if (isCancelled()) {
        wasCancelled = true;
      } else {
        onProgress?.call(0.95, 'Building contact sheet…');
        try {
          final pngBytes = await const BatchExportContactSheetBuilder().build(
            results.map((e) => e.file).toList(),
            columns: 4,
            tileSize: 512,
            padding: 16,
          );
          final name =
              'contact_sheet_${slugify(moduleId, emptyFallback: 'untitled')!}.png';
          final out = File('${directory.path}/$name');
          await out.writeAsBytes(pngBytes, flush: true);
          contactSheet = out;
        } catch (e) {
          if (kDebugMode) debugPrint('[FF] silent catch: $e');
        }
      }
    }

    final completion = BatchExportCompletion(
      completedItems: results.length,
      plannedItems: plan.total,
      wasCancelled: wasCancelled,
    );
    onProgress?.call(completion.progress, completion.status);
    return BatchExportResult(
        directory: directory, items: results, contactSheet: contactSheet);
  }

  Future<Directory> _createBatchDirectory({required String moduleId}) async {
    final base = await _exportService.getExportDirectory();
    final ts = _clock.now();
    final stamp =
        '${ts.year.toString().padLeft(4, '0')}${ts.month.toString().padLeft(2, '0')}${ts.day.toString().padLeft(2, '0')}_${ts.hour.toString().padLeft(2, '0')}${ts.minute.toString().padLeft(2, '0')}${ts.second.toString().padLeft(2, '0')}';
    final prefix =
        '${base.path}/batch_${slugify(moduleId, emptyFallback: 'untitled')!}_$stamp';

    for (var attempt = 1;; attempt++) {
      final suffix =
          attempt == 1 ? '' : '_${attempt.toString().padLeft(2, '0')}';
      final dir = Directory('$prefix$suffix');
      if (await dir.exists()) continue;
      await dir.create(recursive: true);
      return dir;
    }
  }
}

class BatchExportContactSheetBuilder {
  const BatchExportContactSheetBuilder();

  Future<Uint8List> build(
    List<File> files, {
    required int columns,
    required int tileSize,
    required int padding,
  }) async {
    final cols = columns.clamp(1, 12).toInt();
    final rows = ((files.length + cols - 1) / cols).floor().clamp(1, 1 << 20);
    final width = padding + cols * (tileSize + padding);
    final height = padding + rows * (tileSize + padding);

    final sheet = img.Image(width: width, height: height, numChannels: 4);
    img.fill(sheet, color: img.ColorRgba8(12, 12, 12, 255));

    var imageIndex = 0;
    for (final f in files) {
      final img.Image? decoded;
      try {
        final bytes = await f.readAsBytes();
        decoded = img.decodeImage(bytes);
      } catch (e) {
        if (kDebugMode) debugPrint('[FF] skipping contact sheet image: $e');
        continue;
      }
      if (decoded == null) continue;

      final thumb = img.copyResize(
        decoded,
        width: tileSize,
        height: tileSize,
        // Avoid cubic on mobile: Play Console ANRs showed
        // Image.getPixelCubic.cubic blocking input dispatch.
        interpolation: img.Interpolation.average,
      );
      final r = imageIndex ~/ cols;
      final c = imageIndex % cols;
      final x = padding + c * (tileSize + padding);
      final y = padding + r * (tileSize + padding);
      img.compositeImage(sheet, thumb, dstX: x, dstY: y);
      imageIndex++;
    }
    if (imageIndex == 0) throw StateError('No images');

    return Uint8List.fromList(img.encodePng(sheet, level: 6));
  }
}
