include: package:lints/recommended.yaml

analyzer:
  errors:
    unused_import: warning
    unused_local_variable: ignore
    unused_element: ignore
    deprecated_member_use: warning

  exclude:
    - third_party/**

linter:
  rules:
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    prefer_const_declarations: false
    unnecessary_const: false
    non_constant_identifier_names: false
    curly_braces_in_flow_control_structures: false
    use_super_parameters: false
