part of '../escape_time_catalog.dart';

final List<EscapeTimeConfig> _batch23FifthWaveResearchCatalog = [
  // Fifth-wave additions from research/fractal-types-fifth-wave/report.md.
  EscapeTimeConfig(
    id: 'external_rays_equipotential_overlay',
    name: 'External Rays / Equipotential Overlay',
    shaderAsset:
        'shaders/escape_time_family/orbit_and_domain/external_rays_equipotential_gpu.frag',
    defaultIterations: 140,
    defaultBailout: 8.0,
    defaultColorScheme: 2,
    defaultCenterX: -0.55,
    defaultZoom: 0.85,
    maxIterations: 260,
    category: 'Orbit / Domain Coloring',
    extraParams: [
      _floatParam(
        id: 'rayDensity',
        label: 'Ray Density',
        min: 4,
        max: 48,
        step: 1,
        defaultValue: 24,
      ),
      _floatParam(
        id: 'potentialBands',
        label: 'Equipotential Bands',
        min: 2,
        max: 32,
        step: 1,
        defaultValue: 14,
      ),
    ],
  ),
  EscapeTimeConfig(
    id: 'newton_flow_streamlines',
    name: 'Newton-Flow Streamlines',
    shaderAsset: 'shaders/root_finding/newton_flow_streamlines_gpu.frag',
    defaultIterations: 80,
    defaultBailout: 4.0,
    defaultColorScheme: 0,
    defaultZoom: 0.9,
    maxIterations: 160,
    category: 'Root Finding',
    extraParams: [
      _floatParam(
        id: 'degree',
        label: 'Polynomial Degree',
        min: 3,
        max: 6,
        step: 1,
        defaultValue: 4,
      ),
      _floatParam(
        id: 'flowStrength',
        label: 'Flow Strength',
        min: 0.1,
        max: 2.0,
        step: 0.05,
        defaultValue: 0.9,
      ),
    ],
  ),
  EscapeTimeConfig(
    id: 'wada_riddled_basin_visualizer',
    name: 'Wada / Riddled Basin Visualizer',
    shaderAsset: 'shaders/root_finding/wada_riddled_basins_gpu.frag',
    defaultIterations: 90,
    defaultBailout: 4.0,
    defaultColorScheme: 5,
    defaultZoom: 0.85,
    maxIterations: 180,
    category: 'Root Finding',
    extraParams: [
      _floatParam(
        id: 'basinCount',
        label: 'Basin Count',
        min: 3,
        max: 5,
        step: 1,
        defaultValue: 3,
      ),
      _floatParam(
        id: 'riddleScale',
        label: 'Riddle Scale',
        min: 0.2,
        max: 2.0,
        step: 0.05,
        defaultValue: 0.85,
      ),
    ],
  ),
  EscapeTimeConfig(
    id: 'fuchsian_limit_set_lace',
    name: 'Fuchsian / Quasi-Fuchsian Limit Set',
    shaderAsset: 'shaders/ifs_and_geometric/fuchsian_limit_set_lace_gpu.frag',
    defaultIterations: 64,
    defaultBailout: 4.0,
    defaultColorScheme: 4,
    defaultZoom: 0.8,
    maxIterations: 128,
    category: 'IFS / Geometric Fractals',
    extraParams: [
      _floatParam(
        id: 'generatorCount',
        label: 'Generator Count',
        min: 3,
        max: 8,
        step: 1,
        defaultValue: 5,
      ),
      _floatParam(
        id: 'bend',
        label: 'Quasi-Fuchsian Bend',
        min: 0,
        max: 1.6,
        step: 0.02,
        defaultValue: 0.45,
      ),
    ],
  ),
  EscapeTimeConfig(
    id: 'wild_knot_pearl_limit_set',
    name: "Wild-Knot Pearl Limit Set",
    shaderAsset: 'shaders/ifs_and_geometric/wild_knot_pearls_gpu.frag',
    defaultIterations: 72,
    defaultBailout: 4.0,
    defaultColorScheme: 6,
    defaultZoom: 0.75,
    maxIterations: 144,
    category: 'IFS / Geometric Fractals',
    extraParams: [
      _floatParam(
        id: 'knotTurns',
        label: 'Knot Turns',
        min: 2,
        max: 7,
        step: 1,
        defaultValue: 3,
      ),
      _floatParam(
        id: 'pearlRadius',
        label: 'Pearl Radius',
        min: 0.04,
        max: 0.22,
        step: 0.005,
        defaultValue: 0.11,
      ),
    ],
  ),
];
