part of '../escape_time_catalog.dart';

/// Tenth research wave: sixteen non-duplicative mathematical systems selected
/// from `research/fractal-types-tenth-wave/report.md` to take the public catalog
/// from 984 to exactly 1,000 production fractals.
final List<EscapeTimeConfig> _batch26TenthWaveResearchCatalog = [
  EscapeTimeConfig(
    id: 'cubic_connectedness_locus',
    name: 'Cubic Connectedness Locus',
    shaderAsset:
        'shaders/escape_time_family/polynomial_maps/cubic_connectedness_locus_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 8,
    defaultColorScheme: 2,
    defaultCenterX: 0,
    defaultCenterY: 0,
    defaultZoom: 0.65,
    maxIterations: 240,
    category: 'Complex Dynamics',
    extraParams: [
      _floatParam(
          id: 'aReal',
          label: 'Critical Point Re',
          min: -1.5,
          max: 1.5,
          step: 0.01,
          defaultValue: 0.45),
      _floatParam(
          id: 'aImag',
          label: 'Critical Point Im',
          min: -1.5,
          max: 1.5,
          step: 0.01,
          defaultValue: 0.0),
      _floatParam(
          id: 'mode',
          label: 'Critical Orbit Mode',
          min: 0,
          max: 2,
          step: 1,
          defaultValue: 0),
    ],
  ),
  EscapeTimeConfig(
    id: 'newton_parameter_plane',
    name: 'Newton Parameter Plane',
    shaderAsset: 'shaders/root_finding/newton_parameter_plane_gpu.frag',
    defaultIterations: 80,
    defaultBailout: 16,
    defaultColorScheme: 0,
    defaultCenterX: 0,
    defaultCenterY: 0,
    defaultZoom: 0.8,
    maxIterations: 160,
    category: 'Root-Finding',
    extraParams: [
      _floatParam(
          id: 'seedRe',
          label: 'Orbit Seed Re',
          min: -2,
          max: 2,
          step: 0.01,
          defaultValue: 0.35),
      _floatParam(
          id: 'seedIm',
          label: 'Orbit Seed Im',
          min: -2,
          max: 2,
          step: 0.01,
          defaultValue: 0.2),
      _floatParam(
          id: 'damping',
          label: 'Newton Damping',
          min: 0.2,
          max: 1.2,
          step: 0.02,
          defaultValue: 1.0),
    ],
  ),
  EscapeTimeConfig(
    id: 'polylogarithm_julia',
    name: 'Polylogarithm Julia Field',
    shaderAsset:
        'shaders/escape_time_family/transcendental_maps/polylogarithm_julia_gpu.frag',
    defaultIterations: 90,
    defaultBailout: 8,
    defaultColorScheme: 1,
    defaultCenterX: 0,
    defaultCenterY: 0,
    defaultZoom: 0.8,
    maxIterations: 180,
    category: 'Complex Dynamics',
    extraParams: [
      _floatParam(
          id: 'order',
          label: 'Polylog Order',
          min: 1,
          max: 4,
          step: 0.25,
          defaultValue: 2),
      _floatParam(
          id: 'cReal',
          label: 'Julia c Re',
          min: -1.5,
          max: 1.5,
          step: 0.01,
          defaultValue: -0.35),
      _floatParam(
          id: 'cImag',
          label: 'Julia c Im',
          min: -1.5,
          max: 1.5,
          step: 0.01,
          defaultValue: 0.42),
    ],
  ),
  EscapeTimeConfig(
    id: 'q_exponential_julia',
    name: 'q-Exponential Julia Field',
    shaderAsset:
        'shaders/escape_time_family/transcendental_maps/q_exponential_julia_gpu.frag',
    defaultIterations: 90,
    defaultBailout: 8,
    defaultColorScheme: 2,
    defaultCenterX: 0,
    defaultCenterY: 0,
    defaultZoom: 0.85,
    maxIterations: 180,
    category: 'Complex Dynamics',
    extraParams: [
      _floatParam(
          id: 'q',
          label: 'q Deformation',
          min: 0.1,
          max: 1.4,
          step: 0.02,
          defaultValue: 0.72),
      _floatParam(
          id: 'cReal',
          label: 'Julia c Re',
          min: -1.5,
          max: 1.5,
          step: 0.01,
          defaultValue: -0.55),
      _floatParam(
          id: 'cImag',
          label: 'Julia c Im',
          min: -1.5,
          max: 1.5,
          step: 0.01,
          defaultValue: 0.25),
    ],
  ),
  EscapeTimeConfig(
    id: 'klein_j_invariant',
    name: 'Klein j-Invariant Modular Field',
    shaderAsset: 'shaders/number_theory/klein_j_invariant_gpu.frag',
    defaultIterations: 24,
    defaultBailout: 4,
    defaultColorScheme: 2,
    defaultCenterY: 0.35,
    defaultZoom: 0.9,
    maxIterations: 32,
    category: 'Number Theory',
    extraParams: [
      _floatParam(
          id: 'mode',
          label: 'Field Mode',
          min: 0,
          max: 2,
          step: 1,
          defaultValue: 0),
    ],
  ),
  EscapeTimeConfig(
    id: 'jacobi_theta_field',
    name: 'Jacobi Theta Function Field',
    shaderAsset: 'shaders/number_theory/jacobi_theta_field_gpu.frag',
    defaultIterations: 24,
    defaultBailout: 4,
    defaultColorScheme: 1,
    defaultCenterX: 0,
    defaultCenterY: 0,
    defaultZoom: 0.8,
    maxIterations: 32,
    category: 'Number Theory',
    extraParams: [
      _floatParam(
          id: 'nome',
          label: 'Nome q',
          min: 0.05,
          max: 0.92,
          step: 0.01,
          defaultValue: 0.55),
      _floatParam(
          id: 'family',
          label: 'Theta Family',
          min: 2,
          max: 4,
          step: 1,
          defaultValue: 3),
      _floatParam(
          id: 'mode',
          label: 'Field Mode',
          min: 0,
          max: 2,
          step: 1,
          defaultValue: 0),
    ],
  ),
  EscapeTimeConfig(
    id: 'eisenstein_series_field',
    name: 'Eisenstein Series Modular Field',
    shaderAsset: 'shaders/number_theory/eisenstein_series_field_gpu.frag',
    defaultIterations: 24,
    defaultBailout: 4,
    defaultColorScheme: 0,
    defaultCenterY: 0.35,
    defaultZoom: 0.9,
    maxIterations: 32,
    category: 'Number Theory',
    extraParams: [
      _floatParam(
          id: 'weight',
          label: 'Series Weight',
          min: 4,
          max: 6,
          step: 2,
          defaultValue: 4),
      _floatParam(
          id: 'mode',
          label: 'Field Mode',
          min: 0,
          max: 2,
          step: 1,
          defaultValue: 0),
    ],
  ),
  EscapeTimeConfig(
    id: 'gaussian_prime_lattice',
    name: 'Gaussian Prime Lattice',
    shaderAsset: 'shaders/number_theory/gaussian_prime_lattice_gpu.frag',
    defaultIterations: 64,
    defaultBailout: 4,
    defaultColorScheme: 2,
    defaultCenterX: 0,
    defaultCenterY: 0,
    defaultZoom: 1.0,
    maxIterations: 96,
    category: 'Number Theory',
    extraParams: [
      _floatParam(
          id: 'scale',
          label: 'Lattice Scale',
          min: 8,
          max: 80,
          step: 1,
          defaultValue: 30),
      _floatParam(
          id: 'mode',
          label: 'Lattice Mode',
          min: 0,
          max: 2,
          step: 1,
          defaultValue: 0),
    ],
  ),
  EscapeTimeConfig(
    id: 'thomae_popcorn_field',
    name: 'Thomae Popcorn Function',
    shaderAsset: 'shaders/number_theory/thomae_popcorn_field_gpu.frag',
    defaultIterations: 40,
    defaultBailout: 4,
    defaultColorScheme: 1,
    defaultCenterX: 0.5,
    defaultCenterY: 0.35,
    defaultZoom: 0.75,
    maxIterations: 64,
    category: 'Number Theory',
    extraParams: [
      _floatParam(
          id: 'mode',
          label: 'View Mode',
          min: 0,
          max: 2,
          step: 1,
          defaultValue: 0),
    ],
  ),
  EscapeTimeConfig(
    id: 'arnold_tongues',
    name: 'Arnold Tongues / Circle Map',
    shaderAsset: 'shaders/lyapunov_and_stability/arnold_tongues_gpu.frag',
    defaultIterations: 160,
    defaultBailout: 4,
    defaultColorScheme: 2,
    defaultCenterX: 0.5,
    defaultCenterY: 0.55,
    defaultZoom: 0.7,
    maxIterations: 240,
    category: 'Lyapunov / Stability',
    extraParams: [
      _floatParam(
          id: 'mode',
          label: 'Tongue Mode',
          min: 0,
          max: 2,
          step: 1,
          defaultValue: 0),
    ],
  ),
  EscapeTimeConfig(
    id: 'kicked_harper_map',
    name: 'Kicked Harper Resonance Web',
    shaderAsset: 'shaders/lyapunov_and_stability/kicked_harper_map_gpu.frag',
    defaultIterations: 160,
    defaultBailout: 8,
    defaultColorScheme: 0,
    defaultCenterX: 0,
    defaultCenterY: 0,
    defaultZoom: 0.7,
    maxIterations: 240,
    category: 'Lyapunov / Stability',
    extraParams: [
      _floatParam(
          id: 'kickX',
          label: 'Position Kick K',
          min: 0,
          max: 8,
          step: 0.05,
          defaultValue: 1.15),
      _floatParam(
          id: 'kickP',
          label: 'Momentum Kick L',
          min: 0,
          max: 8,
          step: 0.05,
          defaultValue: 1.0),
      _floatParam(
          id: 'mode',
          label: 'Resonance Mode',
          min: 0,
          max: 2,
          step: 1,
          defaultValue: 0),
    ],
  ),
  EscapeTimeConfig(
    id: 'henon_heiles_escape_basin',
    name: 'Hénon–Heiles Escape Basins',
    shaderAsset:
        'shaders/lyapunov_and_stability/henon_heiles_escape_basin_gpu.frag',
    defaultIterations: 180,
    defaultBailout: 4,
    defaultColorScheme: 2,
    defaultCenterX: 0,
    defaultCenterY: 0,
    defaultZoom: 0.75,
    maxIterations: 240,
    category: 'Lyapunov / Stability',
    extraParams: [
      _floatParam(
          id: 'energy',
          label: 'Hamiltonian Energy',
          min: 0.17,
          max: 0.5,
          step: 0.005,
          defaultValue: 0.22),
      _floatParam(
          id: 'stepSize',
          label: 'Integration Step',
          min: 0.002,
          max: 0.03,
          step: 0.001,
          defaultValue: 0.012),
    ],
  ),
  EscapeTimeConfig(
    id: 'talbot_fractal_carpet',
    name: 'Fractal Talbot Carpet',
    shaderAsset: 'shaders/number_theory/talbot_fractal_carpet_gpu.frag',
    defaultIterations: 32,
    defaultBailout: 4,
    defaultColorScheme: 2,
    defaultCenterX: 0.5,
    defaultCenterY: 0.5,
    defaultZoom: 0.8,
    maxIterations: 48,
    category: 'Scientific Visualization',
    extraParams: [
      _floatParam(
          id: 'aperture',
          label: 'Grating Aperture',
          min: 0.1,
          max: 1,
          step: 0.02,
          defaultValue: 0.7),
      _floatParam(
          id: 'mode',
          label: 'Diffraction Mode',
          min: 0,
          max: 2,
          step: 1,
          defaultValue: 0),
    ],
  ),
  EscapeTimeConfig(
    id: 'paperfolding_curve_atlas',
    name: 'Paperfolding Curve Atlas',
    shaderAsset: 'shaders/ifs_and_geometric/paperfolding_curve_atlas_gpu.frag',
    defaultIterations: 64,
    defaultBailout: 4,
    defaultColorScheme: 1,
    defaultCenterX: 0,
    defaultCenterY: 0,
    defaultZoom: 0.65,
    maxIterations: 72,
    category: 'IFS / Geometric Fractals',
    extraParams: [
      _floatParam(
          id: 'variant',
          label: 'Folding Variant',
          min: 0,
          max: 2,
          step: 1,
          defaultValue: 0),
      _floatParam(
          id: 'lineWeight',
          label: 'Line Weight',
          min: 0.002,
          max: 0.05,
          step: 0.002,
          defaultValue: 0.012),
    ],
  ),
  EscapeTimeConfig(
    id: 'de_rham_curve_family',
    name: 'de Rham Self-Affine Curve Family',
    shaderAsset: 'shaders/ifs_and_geometric/de_rham_curve_family_gpu.frag',
    defaultIterations: 32,
    defaultBailout: 4,
    defaultColorScheme: 2,
    defaultCenterX: 0.5,
    defaultCenterY: 0.5,
    defaultZoom: 0.75,
    maxIterations: 40,
    category: 'IFS / Geometric Fractals',
    extraParams: [
      _floatParam(
          id: 'alpha',
          label: 'Affine Weight',
          min: 0.08,
          max: 0.92,
          step: 0.01,
          defaultValue: 0.34),
      _floatParam(
          id: 'mode',
          label: 'Curve Mode',
          min: 0,
          max: 2,
          step: 1,
          defaultValue: 0),
    ],
  ),
  EscapeTimeConfig(
    id: 'substitution_diffraction_field',
    name: 'Substitution Diffraction Field',
    shaderAsset:
        'shaders/number_theory/substitution_diffraction_field_gpu.frag',
    defaultIterations: 96,
    defaultBailout: 4,
    defaultColorScheme: 0,
    defaultCenterX: 0.5,
    defaultCenterY: 0.45,
    defaultZoom: 0.75,
    maxIterations: 128,
    category: 'Number Theory',
    extraParams: [
      _floatParam(
          id: 'sequence',
          label: 'Substitution Sequence',
          min: 0,
          max: 2,
          step: 1,
          defaultValue: 0),
      _floatParam(
          id: 'mode',
          label: 'View Mode',
          min: 0,
          max: 2,
          step: 1,
          defaultValue: 0),
    ],
  ),
];
