part of '../escape_time_catalog.dart';

final List<EscapeTimeConfig> _batch19ResearchedAdditionsCatalog = [
  // Research-backed additions from research/fractal-types-to-add/report.md,
  // ordered from easiest/cheapest 2D shaders toward more geometric families.
  EscapeTimeConfig(
    id: 'pascal_ulam_number_fractals',
    name: 'Pascal / Ulam Number Fractals',
    shaderAsset: 'shaders/number_theory/pascal_ulam_gpu.frag',
    defaultIterations: 96,
    defaultBailout: 4.0,
    defaultColorScheme: 2,
    defaultZoom: 0.7,
    category: 'Number Theory',
    extraParams: [
      _floatParam(
        id: 'variant',
        label: 'Variant (0 Pascal, 1 Ulam)',
        min: 0,
        max: 1,
        step: 1,
        defaultValue: 0,
      ),
      _floatParam(
        id: 'cellScale',
        label: 'Cell Scale',
        min: 20,
        max: 160,
        step: 1,
        defaultValue: 72,
      ),
    ],
  ),
  EscapeTimeConfig(
    id: 'fractal_terrain_noise',
    name: 'Fractal Terrain Noise',
    shaderAsset:
        'shaders/cellular_and_stochastic/fractal_terrain_noise_gpu.frag',
    defaultIterations: 28,
    defaultBailout: 4.0,
    defaultColorScheme: 1,
    defaultCenterY: 0.05,
    defaultZoom: 0.9,
    maxIterations: 48,
    category: 'Procedural Fractals',
    extraParams: [
      _floatParam(
        id: 'roughness',
        label: 'Roughness',
        min: 0.25,
        max: 0.85,
        step: 0.01,
        defaultValue: 0.55,
      ),
      _floatParam(
        id: 'warp',
        label: 'Domain Warp',
        min: 0,
        max: 2,
        step: 0.05,
        defaultValue: 0.8,
      ),
    ],
  ),
  EscapeTimeConfig(
    id: 'circle_inversion_gasket',
    name: 'Circle Inversion Gasket',
    shaderAsset: 'shaders/ifs_and_geometric/circle_inversion_gasket_gpu.frag',
    defaultIterations: 32,
    defaultBailout: 4.0,
    defaultColorScheme: 5,
    defaultZoom: 0.85,
    maxIterations: 80,
    category: 'IFS / Geometric Fractals',
    extraParams: [
      _floatParam(
        id: 'radius',
        label: 'Inversion Radius',
        min: 0.35,
        max: 1.2,
        step: 0.01,
        defaultValue: 0.72,
      ),
      _floatParam(
        id: 'symmetry',
        label: 'Symmetry',
        min: 3,
        max: 8,
        step: 1,
        defaultValue: 4,
      ),
    ],
  ),
  EscapeTimeConfig(
    id: 'poincare_disk_tiling',
    name: 'Poincaré Disk Tiling',
    shaderAsset: 'shaders/ifs_and_geometric/poincare_disk_tiling_gpu.frag',
    defaultIterations: 40,
    defaultBailout: 4.0,
    defaultColorScheme: 0,
    defaultZoom: 0.95,
    maxIterations: 72,
    category: 'Aperiodic Tiling',
    extraParams: [
      _floatParam(
        id: 'pSides',
        label: 'Polygon Sides',
        min: 3,
        max: 12,
        step: 1,
        defaultValue: 7,
      ),
      _floatParam(
        id: 'qMeet',
        label: 'Tiles Around Vertex',
        min: 3,
        max: 9,
        step: 1,
        defaultValue: 3,
      ),
    ],
  ),
];
