part of '../escape_time_catalog.dart';

final List<EscapeTimeConfig> _batch24EighthWaveResearchCatalog = [
  // Eighth-wave additions from research/fractal-types-eighth-wave/report.md:
  // fixed-point iteration fractals, parabolic petals, modular forms, and the
  // unimplemented sixth/seventh-wave backlog (Möbius Julia, fractional cosine,
  // Herman rings, Sierpiński-curve Julia, meromorphic sine, Mandelbrot
  // percolation, Minkowski question-mark, Dedekind eta).
  EscapeTimeConfig(
    id: 'fixed_point_iteration',
    name: 'Fixed-Point Iteration Fractal',
    shaderAsset:
        'shaders/escape_time_family/families/iteration_schemes/fixed_point_iteration_gpu.frag',
    defaultIterations: 140,
    defaultBailout: 4.0,
    defaultColorScheme: 2,
    defaultZoom: 1.0,
    maxIterations: 240,
    category: 'Escape-Time',
    extraParams: [
      _floatParam(
        id: 'scheme',
        label: 'Iteration Scheme',
        min: 0,
        max: 3,
        step: 1,
        defaultValue: 2,
      ),
      _floatParam(
        id: 'alpha',
        label: 'Alpha Weight',
        min: 0.05,
        max: 1.0,
        step: 0.05,
        defaultValue: 0.8,
      ),
      _floatParam(
        id: 'beta',
        label: 'Beta Weight',
        min: 0.05,
        max: 1.0,
        step: 0.05,
        defaultValue: 0.8,
      ),
      _floatParam(
        id: 'gamma',
        label: 'Gamma Weight',
        min: 0.05,
        max: 1.0,
        step: 0.05,
        defaultValue: 0.8,
      ),
    ],
  ),
  EscapeTimeConfig(
    id: 'minkowski_question_mark',
    name: 'Minkowski Question-Mark / Stern-Brocot',
    shaderAsset: 'shaders/number_theory/minkowski_question_mark_gpu.frag',
    defaultIterations: 32,
    defaultBailout: 4.0,
    defaultColorScheme: 2,
    defaultCenterX: 0.0,
    defaultCenterY: 0.0,
    defaultZoom: 1.0,
    maxIterations: 32,
    category: 'Number Theory',
    extraParams: [
      _floatParam(
        id: 'mode',
        label: 'View Mode',
        min: 0,
        max: 2,
        step: 1,
        defaultValue: 0,
      ),
    ],
  ),
  EscapeTimeConfig(
    id: 'mobius_transformation_julia',
    name: 'Möbius Transformation Julia',
    shaderAsset:
        'shaders/escape_time_family/julia_variants/mobius_transformation_julia_gpu.frag',
    defaultIterations: 140,
    defaultBailout: 4.0,
    defaultColorScheme: 0,
    defaultCenterX: -0.4,
    defaultZoom: 0.9,
    maxIterations: 240,
    category: 'Complex Dynamics',
    extraParams: [
      _floatParam(
        id: 'paramP',
        label: 'Möbius p',
        min: 0.5,
        max: 2.0,
        step: 0.05,
        defaultValue: 1.0,
      ),
      _floatParam(
        id: 'paramQ',
        label: 'Möbius q',
        min: -0.5,
        max: 0.5,
        step: 0.01,
        defaultValue: 0.0,
      ),
      _floatParam(
        id: 'paramR',
        label: 'Möbius r',
        min: -0.5,
        max: 0.5,
        step: 0.01,
        defaultValue: 0.1,
      ),
      _floatParam(
        id: 'paramS',
        label: 'Möbius s',
        min: 0.5,
        max: 2.0,
        step: 0.05,
        defaultValue: 1.0,
      ),
    ],
  ),
  EscapeTimeConfig(
    id: 'fractional_complex_cosine',
    name: 'Fractional Complex Cosine Map',
    shaderAsset:
        'shaders/escape_time_family/transcendental_maps/fractional_complex_cosine_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
    defaultColorScheme: 2,
    defaultCenterX: 0.0,
    defaultCenterY: 0.0,
    defaultZoom: 1.2,
    maxIterations: 240,
    category: 'Complex Dynamics',
    extraParams: [
      _floatParam(
        id: 'order',
        label: 'Order',
        min: 0.3,
        max: 3.0,
        step: 0.1,
        defaultValue: 1.0,
      ),
      _floatParam(
        id: 'mode',
        label: 'Deform Mode',
        min: 0,
        max: 1,
        step: 1,
        defaultValue: 0,
      ),
    ],
  ),
  EscapeTimeConfig(
    id: 'parabolic_petal_julia',
    name: 'Parabolic Petal (Leau-Fatou) Julia',
    shaderAsset:
        'shaders/escape_time_family/julia_variants/parabolic_petal_julia_gpu.frag',
    defaultIterations: 160,
    defaultBailout: 4.0,
    defaultColorScheme: 1,
    defaultCenterX: 0.0,
    defaultZoom: 0.9,
    maxIterations: 240,
    category: 'Complex Dynamics',
    extraParams: [
      _floatParam(
        id: 'petals',
        label: 'Petal Count',
        min: 2,
        max: 8,
        step: 1,
        defaultValue: 4,
      ),
      _floatParam(
        id: 'rotation',
        label: 'Rotation Phase',
        min: 0.0,
        max: 1.0,
        step: 0.01,
        defaultValue: 0.0,
      ),
    ],
  ),
  EscapeTimeConfig(
    id: 'herman_ring_julia',
    name: 'Herman Ring / Toral-Band Fatou',
    shaderAsset:
        'shaders/escape_time_family/transcendental_maps/herman_ring_julia_gpu.frag',
    defaultIterations: 140,
    defaultBailout: 4.0,
    defaultColorScheme: 2,
    defaultCenterX: 0.0,
    defaultZoom: 1.0,
    maxIterations: 240,
    category: 'Complex Dynamics',
    extraParams: [
      _floatParam(
        id: 'theta',
        label: 'Rotation (turns)',
        min: 0.0,
        max: 1.0,
        step: 0.005,
        defaultValue: 0.293,
      ),
      _floatParam(
        id: 'a',
        label: 'Involution a',
        min: 0.0,
        max: 0.9,
        step: 0.01,
        defaultValue: 0.3,
      ),
    ],
  ),
  EscapeTimeConfig(
    id: 'sierpinski_curve_julia',
    name: 'Sierpiński-Curve Julia',
    shaderAsset:
        'shaders/escape_time_family/transcendental_maps/sierpinski_curve_julia_gpu.frag',
    defaultIterations: 140,
    defaultBailout: 4.0,
    defaultColorScheme: 0,
    defaultCenterX: 0.0,
    defaultZoom: 1.0,
    maxIterations: 240,
    category: 'Complex Dynamics',
    extraParams: [
      _floatParam(
        id: 'lambda',
        label: 'Critical Perturbation',
        min: -1.0,
        max: 1.0,
        step: 0.01,
        defaultValue: 0.3,
      ),
      _floatParam(
        id: 'mode',
        label: 'Color Mode',
        min: 0,
        max: 1,
        step: 1,
        defaultValue: 0,
      ),
    ],
  ),
  EscapeTimeConfig(
    id: 'meromorphic_sine_julia',
    name: 'Meromorphic Sine Julia (z·sin z)',
    shaderAsset:
        'shaders/escape_time_family/transcendental_maps/meromorphic_sine_julia_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 8.0,
    defaultColorScheme: 2,
    defaultCenterX: 0.0,
    defaultZoom: 1.0,
    maxIterations: 200,
    category: 'Complex Dynamics',
    extraParams: [
      _floatParam(
        id: 'mode',
        label: 'Map Variant',
        min: 0,
        max: 1,
        step: 1,
        defaultValue: 0,
      ),
    ],
  ),
  EscapeTimeConfig(
    id: 'mandelbrot_percolation_carpet',
    name: 'Mandelbrot Percolation Carpet',
    shaderAsset:
        'shaders/cellular_and_stochastic/mandelbrot_percolation_carpet_gpu.frag',
    defaultIterations: 24,
    defaultBailout: 4.0,
    defaultColorScheme: 1,
    defaultCenterX: 0.0,
    defaultCenterY: 0.0,
    defaultZoom: 1.0,
    maxIterations: 40,
    category: 'Cellular / Stochastic',
    extraParams: [
      _floatParam(
        id: 'probability',
        label: 'Keep Probability',
        min: 0.02,
        max: 1.0,
        step: 0.01,
        defaultValue: 0.7,
      ),
      _floatParam(
        id: 'seed',
        label: 'Random Seed',
        min: 0.0,
        max: 10.0,
        step: 0.1,
        defaultValue: 1.0,
      ),
    ],
  ),
  EscapeTimeConfig(
    id: 'dedekind_eta_field',
    name: 'Dedekind Eta Fractal Field',
    shaderAsset: 'shaders/number_theory/dedekind_eta_field_gpu.frag',
    defaultIterations: 24,
    defaultBailout: 4.0,
    defaultColorScheme: 2,
    defaultCenterX: 0.0,
    defaultCenterY: 0.0,
    defaultZoom: 1.0,
    maxIterations: 40,
    category: 'Number Theory',
    extraParams: [
      _floatParam(
        id: 'mode',
        label: 'View Mode',
        min: 0,
        max: 3,
        step: 1,
        defaultValue: 0,
      ),
    ],
  ),
];
