part of '../escape_time_catalog.dart';

List<FractalParameter> _fractalishMotionParams({
  required double motif,
  required double symmetry,
  required double detail,
  required double warp,
  required double motion,
  required double phase,
  required double paletteShift,
}) =>
    [
      _floatParam(
        id: 'motif',
        label: 'Motif Identity (fixed)',
        min: motif,
        max: motif,
        step: 1,
        defaultValue: motif,
      ),
      _floatParam(
        id: 'symmetry',
        label: 'Radial Symmetry',
        min: 3,
        max: 12,
        step: 1,
        defaultValue: symmetry,
      ),
      _floatParam(
        id: 'detail',
        label: 'Recursive Detail',
        min: 2,
        max: 9,
        step: 0.25,
        defaultValue: detail,
      ),
      _floatParam(
        id: 'warp',
        label: 'Domain Warp',
        min: 0,
        max: 2,
        step: 0.05,
        defaultValue: warp,
      ),
      _floatParam(
        id: 'motion',
        label: 'Motion Rate',
        min: 0,
        max: 3,
        step: 0.05,
        defaultValue: motion,
      ),
      _floatParam(
        id: 'phase',
        label: 'Keyframe Phase',
        min: -1,
        max: 1,
        step: 0.01,
        defaultValue: phase,
      ),
      _floatParam(
        id: 'paletteShift',
        label: 'Palette Shift',
        min: 0,
        max: 1,
        step: 0.01,
        defaultValue: paletteShift,
      ),
    ];

/// Original procedural interpretations of structural motifs from keyframed
/// generative animation. Research and licensing boundaries are documented in
/// `research/deforum-fractalish-motion/report.md`.
///
/// These entries do not run a diffusion model or bundle model output, prompts,
/// LoRAs, media, or textures. One runtime-effect shader synthesizes every pixel
/// from analytic geometry, fixed-seed fBm, orbit traps, and smooth interpolation.
final List<EscapeTimeConfig> _batch28FractalishMotionCatalog = [
  EscapeTimeConfig(
    id: 'chromatic_arachnid_lattice',
    name: 'Chromatic Arachnid Lattice',
    shaderAsset:
        'shaders/escape_time_family/experimental_named/procedural_motion/fractalish_motion_gpu.frag',
    defaultIterations: 48,
    defaultBailout: 4,
    defaultColorScheme: 4,
    defaultCenterX: 0,
    defaultCenterY: 0,
    defaultZoom: 0.88,
    maxIterations: 54,
    category: 'Fractalish Motion',
    animationCapability: FractalAnimationCapability.timeDriven,
    extraParams: _fractalishMotionParams(
      motif: 0,
      symmetry: 8,
      detail: 6.5,
      warp: 0.35,
      motion: 0.8,
      phase: 0,
      paletteShift: 0.06,
    ),
  ),
  EscapeTimeConfig(
    id: 'astral_sigil_loom',
    name: 'Astral Sigil Loom',
    shaderAsset:
        'shaders/escape_time_family/experimental_named/procedural_motion/fractalish_motion_gpu.frag',
    defaultIterations: 46,
    defaultBailout: 4,
    defaultColorScheme: 15,
    defaultCenterX: 0,
    defaultCenterY: 0,
    defaultZoom: 0.92,
    maxIterations: 54,
    category: 'Fractalish Motion',
    animationCapability: FractalAnimationCapability.timeDriven,
    extraParams: _fractalishMotionParams(
      motif: 1,
      symmetry: 7,
      detail: 5.5,
      warp: 0.2,
      motion: 0.65,
      phase: 0.12,
      paletteShift: 0.23,
    ),
  ),
  EscapeTimeConfig(
    id: 'recursive_arcana_frames',
    name: 'Recursive Arcana Frames',
    shaderAsset:
        'shaders/escape_time_family/experimental_named/procedural_motion/fractalish_motion_gpu.frag',
    defaultIterations: 50,
    defaultBailout: 4,
    defaultColorScheme: 27,
    defaultCenterX: 0,
    defaultCenterY: 0,
    defaultZoom: 0.82,
    maxIterations: 54,
    category: 'Fractalish Motion',
    animationCapability: FractalAnimationCapability.timeDriven,
    extraParams: _fractalishMotionParams(
      motif: 2,
      symmetry: 6,
      detail: 7,
      warp: 0.45,
      motion: 0.5,
      phase: -0.08,
      paletteShift: 0.41,
    ),
  ),
  EscapeTimeConfig(
    id: 'tempest_aurora_tides',
    name: 'Tempest Aurora Tides',
    shaderAsset:
        'shaders/escape_time_family/experimental_named/procedural_motion/fractalish_motion_gpu.frag',
    defaultIterations: 42,
    defaultBailout: 4,
    defaultColorScheme: 36,
    defaultCenterX: 0,
    defaultCenterY: 0.06,
    defaultZoom: 0.78,
    maxIterations: 54,
    category: 'Fractalish Motion',
    animationCapability: FractalAnimationCapability.timeDriven,
    extraParams: _fractalishMotionParams(
      motif: 3,
      symmetry: 5,
      detail: 5,
      warp: 1.1,
      motion: 1.35,
      phase: 0.18,
      paletteShift: 0.62,
    ),
  ),
  EscapeTimeConfig(
    id: 'fourfold_motif_metamorphosis',
    name: 'Fourfold Motif Metamorphosis',
    shaderAsset:
        'shaders/escape_time_family/experimental_named/procedural_motion/fractalish_motion_gpu.frag',
    defaultIterations: 44,
    defaultBailout: 4,
    defaultColorScheme: 48,
    defaultCenterX: 0,
    defaultCenterY: 0,
    defaultZoom: 0.84,
    maxIterations: 54,
    category: 'Fractalish Motion',
    animationCapability: FractalAnimationCapability.timeDriven,
    extraParams: _fractalishMotionParams(
      motif: 4,
      symmetry: 8,
      detail: 5.5,
      warp: 0.75,
      motion: 1.65,
      phase: 0,
      paletteShift: 0.83,
    ),
  ),
];
