part of '../escape_time_catalog.dart';

final List<EscapeTimeConfig> _batch22FourthWaveResearchCatalog = [
  // Fourth-wave additions from research/fractal-types-fourth-wave/report.md.
  EscapeTimeConfig(
    id: 'fractal_antenna_curves',
    name: 'Fractal Antenna / Minkowski / H-Tree',
    shaderAsset: 'shaders/ifs_and_geometric/fractal_antenna_curves_gpu.frag',
    defaultIterations: 72,
    defaultBailout: 4.0,
    defaultColorScheme: 3,
    defaultZoom: 0.78,
    maxIterations: 144,
    category: 'IFS / Geometric Fractals',
    extraParams: [
      _floatParam(
        id: 'mode',
        label: 'Mode',
        min: 0,
        max: 2,
        step: 1,
        defaultValue: 0,
      ),
      _floatParam(
        id: 'wireWidth',
        label: 'Wire Width',
        min: 0.004,
        max: 0.06,
        step: 0.001,
        defaultValue: 0.018,
      ),
    ],
  ),
  EscapeTimeConfig(
    id: 'levy_brownian_paths',
    name: 'Lévy Flight / Brownian Paths',
    shaderAsset: 'shaders/cellular_and_stochastic/levy_brownian_paths_gpu.frag',
    defaultIterations: 100,
    defaultBailout: 4.0,
    defaultColorScheme: 7,
    defaultZoom: 0.75,
    maxIterations: 180,
    category: 'Cellular / Stochastic',
    extraParams: [
      _floatParam(
        id: 'pathMode',
        label: 'Path Mode',
        min: 0,
        max: 2,
        step: 1,
        defaultValue: 1,
      ),
      _floatParam(
        id: 'jumpiness',
        label: 'Jumpiness',
        min: 0.2,
        max: 2.5,
        step: 0.05,
        defaultValue: 1.1,
      ),
    ],
  ),
  EscapeTimeConfig(
    id: 'basin_entropy_uncertainty',
    name: 'Basin Entropy / Uncertainty Map',
    shaderAsset: 'shaders/root_finding/basin_entropy_map_gpu.frag',
    defaultIterations: 64,
    defaultBailout: 4.0,
    defaultColorScheme: 2,
    defaultZoom: 0.85,
    maxIterations: 120,
    category: 'Root Finding',
    extraParams: [
      _floatParam(
        id: 'degree',
        label: 'Polynomial Degree',
        min: 3,
        max: 5,
        step: 1,
        defaultValue: 3,
      ),
      _floatParam(
        id: 'sampleRadius',
        label: 'Sample Radius',
        min: 0.002,
        max: 0.06,
        step: 0.001,
        defaultValue: 0.018,
      ),
    ],
  ),
  EscapeTimeConfig(
    id: 'ulam_warburton_toothpick',
    name: 'Ulam-Warburton / Toothpick Automata',
    shaderAsset:
        'shaders/cellular_and_stochastic/ulam_warburton_toothpick_gpu.frag',
    defaultIterations: 72,
    defaultBailout: 4.0,
    defaultColorScheme: 5,
    defaultZoom: 0.65,
    maxIterations: 128,
    category: 'Cellular / Stochastic',
    extraParams: [
      _floatParam(
        id: 'automatonMode',
        label: 'Automaton Mode',
        min: 0,
        max: 1,
        step: 1,
        defaultValue: 0,
      ),
      _floatParam(
        id: 'cellScale',
        label: 'Cell Scale',
        min: 20,
        max: 160,
        step: 1,
        defaultValue: 72,
      ),
    ],
  ),
  EscapeTimeConfig(
    id: 'circle_packing_conformal_map',
    name: 'Circle-Packing Conformal Map',
    shaderAsset:
        'shaders/ifs_and_geometric/circle_packing_conformal_map_gpu.frag',
    defaultIterations: 64,
    defaultBailout: 4.0,
    defaultColorScheme: 4,
    defaultZoom: 0.75,
    maxIterations: 120,
    category: 'IFS / Geometric Fractals',
    extraParams: [
      _floatParam(
        id: 'warp',
        label: 'Conformal Warp',
        min: 0,
        max: 2,
        step: 0.05,
        defaultValue: 0.9,
      ),
      _floatParam(
        id: 'packingScale',
        label: 'Packing Scale',
        min: 3,
        max: 14,
        step: 0.1,
        defaultValue: 7,
      ),
    ],
  ),
];
