part of '../escape_time_catalog.dart';

final List<EscapeTimeConfig> _batch18WebResearchedCatalog = [
// ── Batch 18: Web-researched additions ──────────────────────────────────

  EscapeTimeConfig(
    id: 'damped_newton',
    name: 'Damped Newton',
    shaderAsset: 'shaders/root_finding/damped_newton_gpu.frag',
    category: 'Convergent & Root-Finding',
    defaultIterations: 120,
    defaultBailout: 8.0,
    defaultZoom: 0.7,
    extraParams: [
      FractalParameter(
        id: 'damping',
        label: (l10n) => 'Damping',
        type: FractalParamType.float,
        min: 0.1,
        max: 2.0,
        step: 0.01,
        defaultValue: 1.0,
      ),
      FractalParameter(
        id: 'polynomial',
        label: (l10n) => 'Polynomial',
        type: FractalParamType.enumeration,
        min: 0,
        max: 2,
        step: 1,
        defaultValue: 0,
        options: [
          FractalParamOption(value: 0, label: (l10n) => 'z^3 - 1'),
          FractalParamOption(value: 1, label: (l10n) => 'z^4 - 1'),
          FractalParamOption(value: 2, label: (l10n) => 'z^5 - 1'),
        ],
      ),
    ],
    extraPresets: [
      catalogPreset(
        id: 'damped-newton-classic',
        moduleId: 'damped_newton',
        name: 'Cubic Basins',
        params: {
          'iterations': 120,
          'bailout': 8.0,
          'colorScheme': 2,
          'damping': 1.0,
          'polynomial': 0,
        },
        view: FractalViewState(
          pan: Vector2(0.0, 0.0),
          zoom: 0.7,
          rotation: Vector3.zero(),
        ),
      ),
      catalogPreset(
        id: 'damped-newton-relaxed',
        moduleId: 'damped_newton',
        name: 'Relaxed Quartic',
        params: {
          'iterations': 140,
          'bailout': 8.0,
          'colorScheme': 1,
          'damping': 0.75,
          'polynomial': 1,
        },
        view: FractalViewState(
          pan: Vector2(0.0, 0.0),
          zoom: 0.75,
          rotation: Vector3.zero(),
        ),
      ),
    ],
  ),

  EscapeTimeConfig(
    id: 'durand_kerner',
    name: 'Durand-Kerner',
    shaderAsset: 'shaders/root_finding/durand_kerner_gpu.frag',
    category: 'Convergent & Root-Finding',
    defaultIterations: 130,
    defaultBailout: 8.0,
    defaultZoom: 0.9,
    extraParams: [
      FractalParameter(
        id: 'degree',
        label: (l10n) => 'Degree',
        type: FractalParamType.integer,
        min: 3,
        max: 7,
        step: 1,
        defaultValue: 4,
      ),
      FractalParameter(
        id: 'trackRoot',
        label: (l10n) => 'Tracked Root',
        type: FractalParamType.integer,
        min: 0,
        max: 7,
        step: 1,
        defaultValue: 0,
      ),
    ],
    extraPresets: [
      catalogPreset(
        id: 'durand-kerner-quartic',
        moduleId: 'durand_kerner',
        name: 'Quartic Rings',
        params: {
          'iterations': 130,
          'bailout': 8.0,
          'colorScheme': 0,
          'degree': 4,
          'trackRoot': 0,
        },
        view: FractalViewState(
          pan: Vector2(0.0, 0.0),
          zoom: 0.9,
          rotation: Vector3.zero(),
        ),
      ),
      catalogPreset(
        id: 'durand-kerner-pentagonal',
        moduleId: 'durand_kerner',
        name: 'Pentagonal Basins',
        params: {
          'iterations': 150,
          'bailout': 8.0,
          'colorScheme': 2,
          'degree': 5,
          'trackRoot': 2,
        },
        view: FractalViewState(
          pan: Vector2(0.0, 0.0),
          zoom: 0.95,
          rotation: Vector3.zero(),
        ),
      ),
    ],
  ),

  EscapeTimeConfig(
    id: 'ehrlich_aberth',
    name: 'Ehrlich-Aberth',
    shaderAsset: 'shaders/root_finding/ehrlich_aberth_gpu.frag',
    category: 'Convergent & Root-Finding',
    defaultIterations: 120,
    defaultBailout: 8.0,
    defaultZoom: 0.85,
    extraParams: [
      FractalParameter(
        id: 'degree',
        label: (l10n) => 'Degree',
        type: FractalParamType.integer,
        min: 3,
        max: 8,
        step: 1,
        defaultValue: 4,
      ),
      FractalParameter(
        id: 'trackRoot',
        label: (l10n) => 'Tracked Root',
        type: FractalParamType.integer,
        min: 0,
        max: 7,
        step: 1,
        defaultValue: 0,
      ),
    ],
    extraPresets: [
      catalogPreset(
        id: 'ehrlich-aberth-quartic',
        moduleId: 'ehrlich_aberth',
        name: 'Quartic Attraction',
        params: {
          'iterations': 120,
          'bailout': 8.0,
          'colorScheme': 1,
          'degree': 4,
          'trackRoot': 0,
        },
        view: FractalViewState(
          pan: Vector2(0.0, 0.0),
          zoom: 0.85,
          rotation: Vector3.zero(),
        ),
      ),
      catalogPreset(
        id: 'ehrlich-aberth-octic',
        moduleId: 'ehrlich_aberth',
        name: 'Octic Crown',
        params: {
          'iterations': 160,
          'bailout': 8.0,
          'colorScheme': 3,
          'degree': 8,
          'trackRoot': 3,
        },
        view: FractalViewState(
          pan: Vector2(0.0, 0.0),
          zoom: 1.0,
          rotation: Vector3.zero(),
        ),
      ),
    ],
  ),

  EscapeTimeConfig(
    id: 'mcmullen_map',
    name: 'McMullen Map',
    shaderAsset:
        'shaders/escape_time_family/geometry_and_ifs/mcmullen_map_gpu.frag',
    category: 'Advanced Rational & Polynomial',
    defaultIterations: 180,
    defaultBailout: 6.0,
    defaultZoom: 0.9,
    extraParams: [
      FractalParameter(
        id: 'power',
        label: (l10n) => 'Power n',
        type: FractalParamType.integer,
        min: 2,
        max: 8,
        step: 1,
        defaultValue: 3,
      ),
      FractalParameter(
        id: 'aReal',
        label: (l10n) => 'a (real)',
        type: FractalParamType.float,
        min: -2.0,
        max: 2.0,
        step: 0.01,
        defaultValue: -0.1,
      ),
      FractalParameter(
        id: 'aImag',
        label: (l10n) => 'a (imag)',
        type: FractalParamType.float,
        min: -2.0,
        max: 2.0,
        step: 0.01,
        defaultValue: 0.0,
      ),
    ],
    extraPresets: [
      catalogPreset(
        id: 'mcmullen-classic',
        moduleId: 'mcmullen_map',
        name: 'Classic m=3',
        params: {
          'iterations': 180,
          'bailout': 6.0,
          'colorScheme': 0,
          'power': 3,
          'aReal': -0.1,
          'aImag': 0.0,
        },
        view: FractalViewState(
          pan: Vector2(0.0, 0.0),
          zoom: 0.9,
          rotation: Vector3.zero(),
        ),
      ),
      catalogPreset(
        id: 'mcmullen-spiral',
        moduleId: 'mcmullen_map',
        name: 'Spiral Web',
        params: {
          'iterations': 220,
          'bailout': 6.0,
          'colorScheme': 2,
          'power': 5,
          'aReal': -0.2,
          'aImag': 0.18,
        },
        view: FractalViewState(
          pan: Vector2(0.0, 0.0),
          zoom: 1.05,
          rotation: Vector3.zero(),
        ),
      ),
    ],
  ),

  EscapeTimeConfig(
    id: 'generalized_mcmullen',
    name: 'Generalized McMullen',
    shaderAsset:
        'shaders/escape_time_family/geometry_and_ifs/generalized_mcmullen_gpu.frag',
    category: 'Advanced Rational & Polynomial',
    defaultIterations: 200,
    defaultBailout: 6.0,
    defaultZoom: 0.95,
    extraParams: [
      FractalParameter(
        id: 'powerN',
        label: (l10n) => 'Power n',
        type: FractalParamType.integer,
        min: 2,
        max: 8,
        step: 1,
        defaultValue: 3,
      ),
      FractalParameter(
        id: 'powerM',
        label: (l10n) => 'Power m',
        type: FractalParamType.integer,
        min: 1,
        max: 8,
        step: 1,
        defaultValue: 3,
      ),
      FractalParameter(
        id: 'aReal',
        label: (l10n) => 'a (real)',
        type: FractalParamType.float,
        min: -2.0,
        max: 2.0,
        step: 0.01,
        defaultValue: -0.1,
      ),
      FractalParameter(
        id: 'aImag',
        label: (l10n) => 'a (imag)',
        type: FractalParamType.float,
        min: -2.0,
        max: 2.0,
        step: 0.01,
        defaultValue: 0.0,
      ),
      FractalParameter(
        id: 'bReal',
        label: (l10n) => 'b (real)',
        type: FractalParamType.float,
        min: -2.0,
        max: 2.0,
        step: 0.01,
        defaultValue: 0.0,
      ),
      FractalParameter(
        id: 'bImag',
        label: (l10n) => 'b (imag)',
        type: FractalParamType.float,
        min: -2.0,
        max: 2.0,
        step: 0.01,
        defaultValue: 0.0,
      ),
    ],
    extraPresets: [
      catalogPreset(
        id: 'generalized-mcmullen-symmetric',
        moduleId: 'generalized_mcmullen',
        name: 'Symmetric (n=3,m=3)',
        params: {
          'iterations': 200,
          'bailout': 6.0,
          'colorScheme': 1,
          'powerN': 3,
          'powerM': 3,
          'aReal': -0.1,
          'aImag': 0.0,
          'bReal': 0.0,
          'bImag': 0.0,
        },
        view: FractalViewState(
          pan: Vector2(0.0, 0.0),
          zoom: 0.95,
          rotation: Vector3.zero(),
        ),
      ),
      catalogPreset(
        id: 'generalized-mcmullen-asymmetric',
        moduleId: 'generalized_mcmullen',
        name: 'Asymmetric (n=5,m=2)',
        params: {
          'iterations': 240,
          'bailout': 6.0,
          'colorScheme': 2,
          'powerN': 5,
          'powerM': 2,
          'aReal': -0.2,
          'aImag': 0.15,
          'bReal': 0.05,
          'bImag': -0.03,
        },
        view: FractalViewState(
          pan: Vector2(0.0, 0.0),
          zoom: 1.0,
          rotation: Vector3.zero(),
        ),
      ),
    ],
  ),

  EscapeTimeConfig(
    id: 'fractal_flame',
    name: 'Fractal Flame',
    shaderAsset:
        'shaders/escape_time_family/geometry_and_ifs/fractal_flame_gpu.frag',
    category: 'IFS / Geometric Fractals',
    defaultIterations: 140,
    defaultBailout: 8.0,
    defaultZoom: 1.0,
    maxIterations: 200,
    extraParams: [
      FractalParameter(
        id: 'variation',
        label: (l10n) => 'Variation',
        type: FractalParamType.enumeration,
        min: 0,
        max: 4,
        step: 1,
        defaultValue: 3,
        options: [
          FractalParamOption(value: 0, label: (l10n) => 'Linear'),
          FractalParamOption(value: 1, label: (l10n) => 'Sinusoidal'),
          FractalParamOption(value: 2, label: (l10n) => 'Spherical'),
          FractalParamOption(value: 3, label: (l10n) => 'Swirl'),
          FractalParamOption(value: 4, label: (l10n) => 'Horseshoe'),
        ],
      ),
      FractalParameter(
        id: 'symmetry',
        label: (l10n) => 'Symmetry',
        type: FractalParamType.enumeration,
        min: 0,
        max: 3,
        step: 1,
        defaultValue: 2,
        options: [
          FractalParamOption(value: 0, label: (l10n) => 'None'),
          FractalParamOption(value: 1, label: (l10n) => 'Bilateral'),
          FractalParamOption(value: 2, label: (l10n) => '3-fold'),
          FractalParamOption(value: 3, label: (l10n) => '6-fold'),
        ],
      ),
    ],
    extraPresets: [
      catalogPreset(
        id: 'flame-swirl-triad',
        moduleId: 'fractal_flame',
        name: 'Swirl Triad',
        params: {
          'iterations': 140,
          'bailout': 8.0,
          'colorScheme': 2,
          'variation': 3,
          'symmetry': 2,
        },
        view: FractalViewState(
          pan: Vector2(0.0, 0.0),
          zoom: 1.0,
          rotation: Vector3.zero(),
        ),
      ),
      catalogPreset(
        id: 'flame-horseshoe-kaleidoscope',
        moduleId: 'fractal_flame',
        name: 'Horseshoe Kaleidoscope',
        params: {
          'iterations': 180,
          'bailout': 8.0,
          'colorScheme': 0,
          'variation': 4,
          'symmetry': 3,
        },
        view: FractalViewState(
          pan: Vector2(0.0, 0.0),
          zoom: 1.1,
          rotation: Vector3.zero(),
        ),
      ),
    ],
  ),

  EscapeTimeConfig(
    id: 'dielectric_breakdown',
    name: 'Dielectric Breakdown',
    shaderAsset:
        'shaders/cellular_and_stochastic/dielectric_breakdown_gpu.frag',
    category: 'Cellular & Stochastic Growth',
    defaultIterations: 30,
    defaultBailout: 4.0,
    defaultZoom: 1.0,
    maxIterations: 40,
    extraParams: [
      FractalParameter(
        id: 'branchDensity',
        label: (l10n) => 'Branch Density',
        type: FractalParamType.float,
        min: 0.1,
        max: 1.0,
        step: 0.01,
        defaultValue: 0.5,
      ),
      FractalParameter(
        id: 'eta',
        label: (l10n) => 'Eta',
        type: FractalParamType.float,
        min: 0.5,
        max: 3.0,
        step: 0.01,
        defaultValue: 1.0,
      ),
      FractalParameter(
        id: 'seed',
        label: (l10n) => 'Seed',
        type: FractalParamType.float,
        min: 0.0,
        max: 10.0,
        step: 0.1,
        defaultValue: 0.0,
      ),
    ],
    extraPresets: [
      catalogPreset(
        id: 'dielectric-lightning',
        moduleId: 'dielectric_breakdown',
        name: 'Lightning Tree',
        params: {
          'iterations': 30,
          'bailout': 4.0,
          'colorScheme': 1,
          'branchDensity': 0.6,
          'eta': 1.3,
          'seed': 0.0,
        },
        view: FractalViewState(
          pan: Vector2(0.0, 0.0),
          zoom: 1.0,
          rotation: Vector3.zero(),
        ),
      ),
      catalogPreset(
        id: 'dielectric-filament',
        moduleId: 'dielectric_breakdown',
        name: 'Filament Storm',
        params: {
          'iterations': 40,
          'bailout': 4.0,
          'colorScheme': 2,
          'branchDensity': 0.85,
          'eta': 2.2,
          'seed': 3.0,
        },
        view: FractalViewState(
          pan: Vector2(0.0, 0.0),
          zoom: 1.15,
          rotation: Vector3.zero(),
        ),
      ),
    ],
  ),
  EscapeTimeConfig(
    id: 'lichtenberg_growth',
    name: 'Lichtenberg Growth',
    shaderAsset: 'shaders/cellular_and_stochastic/lichtenberg_growth_gpu.frag',
    category: 'Cellular & Stochastic Growth',
    defaultIterations: 30,
    defaultBailout: 4.0,
    defaultZoom: 1.0,
    maxIterations: 40,
    extraParams: [
      FractalParameter(
        id: 'growthSpeed',
        label: (l10n) => 'Growth Speed',
        type: FractalParamType.float,
        min: 0.1,
        max: 1.0,
        step: 0.01,
        defaultValue: 0.3,
      ),
      FractalParameter(
        id: 'branchAngle',
        label: (l10n) => 'Branch Angle',
        type: FractalParamType.float,
        min: 0.1,
        max: 1.5,
        step: 0.01,
        defaultValue: 0.5,
      ),
      FractalParameter(
        id: 'complexity',
        label: (l10n) => 'Complexity',
        type: FractalParamType.integer,
        min: 3,
        max: 8,
        step: 1,
        defaultValue: 5,
      ),
    ],
    extraPresets: [
      catalogPreset(
        id: 'lichtenberg-dendrite',
        moduleId: 'lichtenberg_growth',
        name: 'Dendrite Growth',
        params: {
          'iterations': 35,
          'bailout': 4.0,
          'colorScheme': 1,
          'growthSpeed': 0.4,
          'branchAngle': 0.6,
          'complexity': 6,
        },
        view: FractalViewState(
          pan: Vector2(0.0, 0.0),
          zoom: 1.2,
          rotation: Vector3.zero(),
        ),
      ),
      catalogPreset(
        id: 'lichtenberg-lichen',
        moduleId: 'lichtenberg_growth',
        name: 'Lichen Pattern',
        params: {
          'iterations': 25,
          'bailout': 4.0,
          'colorScheme': 3,
          'growthSpeed': 0.2,
          'branchAngle': 0.3,
          'complexity': 4,
        },
        view: FractalViewState(
          pan: Vector2(0.0, 0.0),
          zoom: 1.0,
          rotation: Vector3.zero(),
        ),
      ),
    ],
  ),
];
