part of '../escape_time_catalog.dart';

final List<EscapeTimeConfig> _batch25NinthWaveResearchCatalog = [
  // Ninth-wave additions from research/fractal-types-ninth-wave/report.md:
  // Truchet mosaics, Bessel zero fields, fractal interpolation relief,
  // hidden/hyperchaotic attractors, rep-tiles, Baker/wandering domains,
  // superfractal morphing, and p-adic annuli. (SNA was skipped: an
  // strange_nonchaotic_attractor module already exists from wave 3.)
  EscapeTimeConfig(
    id: 'truchet_fractal_mosaic',
    name: 'Truchet Fractal Mosaic',
    shaderAsset: 'shaders/ifs_and_geometric/truchet_fractal_mosaic_gpu.frag',
    defaultIterations: 32,
    defaultBailout: 4.0,
    defaultColorScheme: 1,
    defaultCenterX: 0.0,
    defaultCenterY: 0.0,
    defaultZoom: 1.0,
    maxIterations: 40,
    category: 'IFS / Geometric Fractals',
    extraParams: [
      _floatParam(
        id: 'tileScale',
        label: 'Tile Scale',
        min: 2,
        max: 64,
        step: 1,
        defaultValue: 8,
      ),
      _floatParam(
        id: 'seed',
        label: 'Random Seed',
        min: 0.0,
        max: 10.0,
        step: 0.1,
        defaultValue: 1.0,
      ),
      _floatParam(
        id: 'thickness',
        label: 'Line Thickness',
        min: 0.02,
        max: 0.5,
        step: 0.01,
        defaultValue: 0.18,
      ),
      _floatParam(
        id: 'mode',
        label: 'Mosaic Mode',
        min: 0,
        max: 1,
        step: 1,
        defaultValue: 0,
      ),
    ],
  ),
  EscapeTimeConfig(
    id: 'bessel_zero_field',
    name: 'Bessel Zero Field',
    shaderAsset: 'shaders/number_theory/bessel_zero_field_gpu.frag',
    defaultIterations: 24,
    defaultBailout: 4.0,
    defaultColorScheme: 2,
    defaultCenterX: 10.0,
    defaultCenterY: 0.0,
    defaultZoom: 0.9,
    maxIterations: 40,
    category: 'Number Theory',
    extraParams: [
      _floatParam(
        id: 'order',
        label: 'Order (nu)',
        min: 0.0,
        max: 6.0,
        step: 0.1,
        defaultValue: 0.0,
      ),
      _floatParam(
        id: 'mode',
        label: 'Field Mode',
        min: 0,
        max: 2,
        step: 1,
        defaultValue: 0,
      ),
    ],
  ),
  EscapeTimeConfig(
    id: 'fractal_interpolation_relief',
    name: 'Fractal Interpolation Relief',
    shaderAsset:
        'shaders/ifs_and_geometric/fractal_interpolation_relief_gpu.frag',
    defaultIterations: 32,
    defaultBailout: 4.0,
    defaultColorScheme: 2,
    defaultCenterX: 0.0,
    defaultCenterY: 0.0,
    defaultZoom: 1.0,
    maxIterations: 40,
    category: 'IFS / Geometric Fractals',
    extraParams: [
      _floatParam(
        id: 'roughness',
        label: 'Roughness',
        min: 0.15,
        max: 0.95,
        step: 0.01,
        defaultValue: 0.55,
      ),
      _floatParam(
        id: 'seed',
        label: 'Seed',
        min: 0.0,
        max: 10.0,
        step: 0.1,
        defaultValue: 3.0,
      ),
      _floatParam(
        id: 'mode',
        label: 'Shading',
        min: 0,
        max: 1,
        step: 1,
        defaultValue: 0,
      ),
    ],
  ),
  EscapeTimeConfig(
    id: 'hidden_hyperchaotic_attractor',
    name: 'Hidden Hyperchaotic Attractor',
    shaderAsset:
        'shaders/strange_attractors/hidden_hyperchaotic_attractor_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 8.0,
    defaultColorScheme: 0,
    defaultCenterX: 0.0,
    defaultCenterY: 0.0,
    defaultZoom: 0.7,
    maxIterations: 240,
    category: 'Strange Attractors',
    extraParams: [
      _floatParam(
        id: 'variant',
        label: 'System Variant',
        min: 0,
        max: 1,
        step: 1,
        defaultValue: 0,
      ),
      _floatParam(
        id: 'dwell',
        label: 'Orbit Dwell',
        min: 8,
        max: 96,
        step: 1,
        defaultValue: 24,
      ),
    ],
  ),
  EscapeTimeConfig(
    id: 'rep_tile_explorer',
    name: 'Rep-Tile Explorer',
    shaderAsset: 'shaders/ifs_and_geometric/rep_tile_explorer_gpu.frag',
    defaultIterations: 32,
    defaultBailout: 4.0,
    defaultColorScheme: 1,
    defaultCenterX: 0.0,
    defaultCenterY: 0.0,
    defaultZoom: 1.2,
    maxIterations: 40,
    category: 'IFS / Geometric Fractals',
    extraParams: [
      _floatParam(
        id: 'shape',
        label: 'Tile Shape',
        min: 0,
        max: 1,
        step: 1,
        defaultValue: 0,
      ),
      _floatParam(
        id: 'lineWeight',
        label: 'Edge Weight',
        min: 0.01,
        max: 0.2,
        step: 0.005,
        defaultValue: 0.05,
      ),
    ],
  ),
  EscapeTimeConfig(
    id: 'baker_wandering_domain',
    name: 'Baker / Wandering-Domain Map',
    shaderAsset:
        'shaders/escape_time_family/transcendental_maps/baker_wandering_domain_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 8.0,
    defaultColorScheme: 2,
    defaultCenterX: 0.0,
    defaultCenterY: 0.0,
    defaultZoom: 1.0,
    maxIterations: 200,
    category: 'Complex Dynamics',
    extraParams: [
      _floatParam(
        id: 'lambdaRe',
        label: 'Lambda Re',
        min: -2.0,
        max: 2.0,
        step: 0.01,
        defaultValue: 0.5,
      ),
      _floatParam(
        id: 'lambdaIm',
        label: 'Lambda Im',
        min: -2.0,
        max: 2.0,
        step: 0.01,
        defaultValue: 0.35,
      ),
    ],
  ),
  EscapeTimeConfig(
    id: 'superfractal_morph',
    name: 'Superfractal Morph (Random IFS)',
    shaderAsset: 'shaders/ifs_and_geometric/superfractal_morph_gpu.frag',
    defaultIterations: 96,
    defaultBailout: 4.0,
    defaultColorScheme: 2,
    defaultCenterX: 0.0,
    defaultCenterY: 0.15,
    defaultZoom: 1.4,
    maxIterations: 240,
    category: 'IFS / Geometric Fractals',
    extraParams: [
      _floatParam(
        id: 'mix',
        label: 'Family Mix',
        min: 0.0,
        max: 1.0,
        step: 0.01,
        defaultValue: 0.55,
      ),
      _floatParam(
        id: 'seed',
        label: 'Random Seed',
        min: 0.0,
        max: 10.0,
        step: 0.1,
        defaultValue: 2.0,
      ),
    ],
  ),
  EscapeTimeConfig(
    id: 'p_adic_mandelbrot',
    name: 'p-adic Mandelbrot Annuli',
    shaderAsset: 'shaders/number_theory/p_adic_mandelbrot_gpu.frag',
    defaultIterations: 32,
    defaultBailout: 4.0,
    defaultColorScheme: 2,
    defaultCenterX: 0.0,
    defaultCenterY: 0.0,
    defaultZoom: 1.0,
    maxIterations: 40,
    category: 'Number Theory',
    extraParams: [
      _floatParam(
        id: 'prime',
        label: 'Prime p',
        min: 2,
        max: 7,
        step: 1,
        defaultValue: 3,
      ),
      _floatParam(
        id: 'mode',
        label: 'View Mode',
        min: 0,
        max: 1,
        step: 1,
        defaultValue: 0,
      ),
    ],
  ),
];
