part of '../escape_time_catalog.dart';

final List<EscapeTimeConfig> _batch20NextWaveResearchCatalog = [
  // Next-wave additions from research/fractal-types-next-wave/report.md.
  EscapeTimeConfig(
    id: 'quasicrystal_interference',
    name: 'Quasicrystal Interference',
    shaderAsset: 'shaders/ifs_and_geometric/quasicrystal_interference_gpu.frag',
    defaultIterations: 80,
    defaultBailout: 4.0,
    defaultColorScheme: 7,
    defaultZoom: 0.8,
    category: 'Aperiodic Tiling',
    extraParams: [
      _floatParam(
        id: 'symmetry',
        label: 'Symmetry',
        min: 5,
        max: 14,
        step: 1,
        defaultValue: 10,
      ),
      _floatParam(
        id: 'sharpness',
        label: 'Sharpness',
        min: 0.5,
        max: 8,
        step: 0.1,
        defaultValue: 3.2,
      ),
      _floatParam(
        id: 'phase',
        label: 'Phase',
        min: 0,
        max: 6.28318,
        step: 0.05,
        defaultValue: 0,
      ),
    ],
  ),
  EscapeTimeConfig(
    id: 'l_system_plants_trees',
    name: 'L-System Plants / Trees',
    shaderAsset: 'shaders/ifs_and_geometric/l_system_plants_gpu.frag',
    defaultIterations: 72,
    defaultBailout: 4.0,
    defaultColorScheme: 1,
    defaultCenterY: 0.15,
    defaultZoom: 0.9,
    maxIterations: 120,
    category: 'L-Systems',
    extraParams: [
      _floatParam(
        id: 'branchAngle',
        label: 'Branch Angle',
        min: 0.25,
        max: 1.15,
        step: 0.01,
        defaultValue: 0.58,
      ),
      _floatParam(
        id: 'canopy',
        label: 'Canopy Spread',
        min: 0.25,
        max: 1.4,
        step: 0.01,
        defaultValue: 0.82,
      ),
    ],
  ),
  EscapeTimeConfig(
    id: 'brownian_tree_dla',
    name: 'Brownian Tree / DLA',
    shaderAsset: 'shaders/cellular_and_stochastic/brownian_tree_dla_gpu.frag',
    defaultIterations: 96,
    defaultBailout: 4.0,
    defaultColorScheme: 2,
    defaultZoom: 0.85,
    maxIterations: 180,
    category: 'Cellular / Stochastic',
    extraParams: [
      _floatParam(
        id: 'branchDensity',
        label: 'Branch Density',
        min: 0.4,
        max: 2.5,
        step: 0.05,
        defaultValue: 1.15,
      ),
      _floatParam(
        id: 'jitter',
        label: 'Walker Jitter',
        min: 0,
        max: 2,
        step: 0.05,
        defaultValue: 0.9,
      ),
    ],
  ),
  EscapeTimeConfig(
    id: 'multifractal_plasma_cascade',
    name: 'Multifractal Plasma Cascade',
    shaderAsset: 'shaders/cellular_and_stochastic/multifractal_plasma_gpu.frag',
    defaultIterations: 40,
    defaultBailout: 4.0,
    defaultColorScheme: 5,
    defaultZoom: 0.85,
    maxIterations: 96,
    category: 'Procedural Fractals',
    extraParams: [
      _floatParam(
        id: 'lacunarity',
        label: 'Lacunarity',
        min: 1.5,
        max: 3.5,
        step: 0.05,
        defaultValue: 2.1,
      ),
      _floatParam(
        id: 'intermittency',
        label: 'Intermittency',
        min: 0.2,
        max: 1.2,
        step: 0.02,
        defaultValue: 0.72,
      ),
    ],
  ),
  EscapeTimeConfig(
    id: 'kleinian_schottky_necklace',
    name: 'Kleinian / Schottky Necklace',
    shaderAsset:
        'shaders/ifs_and_geometric/kleinian_schottky_necklace_gpu.frag',
    defaultIterations: 48,
    defaultBailout: 4.0,
    defaultColorScheme: 4,
    defaultZoom: 0.75,
    maxIterations: 96,
    category: 'IFS / Geometric Fractals',
    extraParams: [
      _floatParam(
        id: 'circleRadius',
        label: 'Circle Radius',
        min: 0.28,
        max: 1.1,
        step: 0.01,
        defaultValue: 0.62,
      ),
      _floatParam(
        id: 'twist',
        label: 'Loxodromic Twist',
        min: -1.5,
        max: 1.5,
        step: 0.02,
        defaultValue: 0.35,
      ),
    ],
  ),
];
