part of '../escape_time_catalog.dart';

final List<EscapeTimeConfig> _batch21ThirdWaveResearchCatalog = [
  // Third-wave additions from research/fractal-types-third-wave/report.md.
  EscapeTimeConfig(
    id: 'bifurcation_diagram_explorer',
    name: 'Bifurcation Diagram Explorer',
    shaderAsset: 'shaders/lyapunov_and_stability/bifurcation_diagram_gpu.frag',
    defaultIterations: 160,
    defaultBailout: 4.0,
    defaultColorScheme: 2,
    defaultCenterX: 0.0,
    defaultCenterY: 0.0,
    defaultZoom: 0.9,
    maxIterations: 240,
    category: 'Lyapunov / Stability',
    extraParams: [
      _floatParam(
        id: 'mapVariant',
        label: 'Map Variant',
        min: 0,
        max: 2,
        step: 1,
        defaultValue: 0,
      ),
      _floatParam(
        id: 'settle',
        label: 'Settle Steps',
        min: 8,
        max: 96,
        step: 1,
        defaultValue: 48,
      ),
    ],
  ),
  EscapeTimeConfig(
    id: 'voronoi_fractal_crackle',
    name: 'Voronoi Fractal Crackle',
    shaderAsset: 'shaders/ifs_and_geometric/voronoi_fractal_crackle_gpu.frag',
    defaultIterations: 56,
    defaultBailout: 4.0,
    defaultColorScheme: 4,
    defaultZoom: 0.8,
    maxIterations: 96,
    category: 'Procedural Fractals',
    extraParams: [
      _floatParam(
        id: 'cellScale',
        label: 'Cell Scale',
        min: 1.5,
        max: 8,
        step: 0.1,
        defaultValue: 3.4,
      ),
      _floatParam(
        id: 'jitter',
        label: 'Cell Jitter',
        min: 0.1,
        max: 1.2,
        step: 0.02,
        defaultValue: 0.72,
      ),
    ],
  ),
  EscapeTimeConfig(
    id: 'takagi_blancmange_staircase',
    name: 'Takagi / Blancmange / Devil Staircase',
    shaderAsset: 'shaders/number_theory/takagi_blancmange_staircase_gpu.frag',
    defaultIterations: 96,
    defaultBailout: 4.0,
    defaultColorScheme: 6,
    defaultZoom: 0.8,
    maxIterations: 160,
    category: 'Number Theory',
    extraParams: [
      _floatParam(
        id: 'mode',
        label: 'Mode',
        min: 0,
        max: 2,
        step: 1,
        defaultValue: 0,
      ),
      _floatParam(
        id: 'thickness',
        label: 'Graph Thickness',
        min: 0.004,
        max: 0.05,
        step: 0.001,
        defaultValue: 0.018,
      ),
    ],
  ),
  EscapeTimeConfig(
    id: 'fractal_interpolation_curves',
    name: 'Fractal Interpolation Curves',
    shaderAsset: 'shaders/number_theory/fractal_interpolation_curves_gpu.frag',
    defaultIterations: 72,
    defaultBailout: 4.0,
    defaultColorScheme: 1,
    defaultZoom: 0.85,
    maxIterations: 144,
    category: 'Procedural Fractals',
    extraParams: [
      _floatParam(
        id: 'roughness',
        label: 'Roughness',
        min: 0.2,
        max: 0.9,
        step: 0.01,
        defaultValue: 0.58,
      ),
      _floatParam(
        id: 'seed',
        label: 'Control Seed',
        min: 0,
        max: 12,
        step: 0.1,
        defaultValue: 2.4,
      ),
    ],
  ),
  EscapeTimeConfig(
    id: 'strange_nonchaotic_attractor',
    name: 'Strange Nonchaotic Attractor',
    shaderAsset: 'shaders/strange_attractors/strange_nonchaotic_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
    defaultColorScheme: 7,
    defaultZoom: 0.9,
    maxIterations: 220,
    category: 'Strange Attractors',
    extraParams: [
      _floatParam(
        id: 'forcing',
        label: 'Quasiperiodic Forcing',
        min: 0.1,
        max: 1.2,
        step: 0.01,
        defaultValue: 0.62,
      ),
      _floatParam(
        id: 'folding',
        label: 'Folding',
        min: 0.4,
        max: 2.4,
        step: 0.02,
        defaultValue: 1.25,
      ),
    ],
  ),
];
