part of '../escape_time_catalog.dart';

final List<EscapeTimeConfig> _cellularStochasticCatalog = [
// ── XII. Cellular Automata & Stochastic Growth ─────────
  EscapeTimeConfig(
    id: 'wolfram_rule30',
    name: 'Wolfram Rule 30',
    shaderAsset: 'shaders/cellular_and_stochastic/wolfram_rule30_gpu.frag',
    defaultIterations: 240,
    defaultBailout: 4.0,
    extraParams: [
      _floatParam(
        id: 'rule',
        label: 'Rule',
        min: 0,
        max: 255,
        step: 1,
        defaultValue: 30.0,
      ),
    ],
  ),
  EscapeTimeConfig(
    id: 'rule90_linear_ca',
    name: 'Rule 90 Linear CA',
    shaderAsset: 'shaders/cellular_and_stochastic/wolfram_rule30_gpu.frag',
    defaultIterations: 256,
    defaultBailout: 4.0,
    category: 'Cellular Automata',
    extraParams: [
      _floatParam(
        id: 'rule',
        label: 'Rule',
        min: 0,
        max: 255,
        step: 1,
        defaultValue: 90.0,
      ),
    ],
  ),
  EscapeTimeConfig(
    id: 'rule150_linear_ca',
    name: 'Rule 150 Linear CA',
    shaderAsset: 'shaders/cellular_and_stochastic/wolfram_rule30_gpu.frag',
    defaultIterations: 256,
    defaultBailout: 4.0,
    category: 'Cellular Automata',
    extraParams: [
      _floatParam(
        id: 'rule',
        label: 'Rule',
        min: 0,
        max: 255,
        step: 1,
        defaultValue: 150.0,
      ),
    ],
  ),
  EscapeTimeConfig(
    id: 'cyclic_cellular_automaton',
    name: 'Cyclic Cellular Automaton',
    shaderAsset:
        'shaders/cellular_and_stochastic/cyclic_cellular_automaton_gpu.frag',
    defaultIterations: 64,
    defaultBailout: 4.0,
    category: 'Cellular Automata',
    extraParams: [
      _floatParam(
        id: 'states',
        label: 'States',
        min: 3,
        max: 16,
        step: 1,
        defaultValue: 8.0,
      ),
      _floatParam(
        id: 'threshold',
        label: 'Threshold',
        min: 1,
        max: 8,
        step: 1,
        defaultValue: 1.0,
      ),
    ],
  ),
  EscapeTimeConfig(
    id: 'greenberg_hastings_ca',
    name: 'Greenberg-Hastings CA',
    shaderAsset:
        'shaders/cellular_and_stochastic/greenberg_hastings_ca_gpu.frag',
    defaultIterations: 64,
    defaultBailout: 4.0,
    category: 'Cellular Automata',
    extraParams: [
      _floatParam(
        id: 'threshold',
        label: 'Threshold',
        min: 1,
        max: 8,
        step: 1,
        defaultValue: 1.0,
      ),
      _floatParam(
        id: 'refractoryPeriod',
        label: 'Refractory Period',
        min: 2,
        max: 16,
        step: 1,
        defaultValue: 8.0,
      ),
    ],
  ),
  EscapeTimeConfig(
    id: 'klausmeier_vegetation',
    name: 'Klausmeier Vegetation',
    shaderAsset:
        'shaders/cellular_and_stochastic/klausmeier_vegetation_gpu.frag',
    defaultIterations: 64,
    defaultBailout: 4.0,
    category: 'Reaction-Diffusion',
    extraParams: [
      _floatParam(
        id: 'rainfall',
        label: 'Rainfall',
        min: 0.1,
        max: 5,
        step: 0.1,
        defaultValue: 2.0,
      ),
      _floatParam(
        id: 'mortality',
        label: 'Mortality',
        min: 0.05,
        max: 2,
        step: 0.05,
        defaultValue: 0.45,
      ),
      _floatParam(
        id: 'waterDiffusion',
        label: 'Water Diffusion',
        min: 0,
        max: 20,
        step: 0.5,
        defaultValue: 10.0,
      ),
      _floatParam(
        id: 'plantDiffusion',
        label: 'Plant Diffusion',
        min: 0,
        max: 5,
        step: 0.1,
        defaultValue: 1.0,
      ),
      _floatParam(
        id: 'advection',
        label: 'Advection',
        min: 0,
        max: 2,
        step: 0.05,
        defaultValue: 0.2,
      ),
    ],
  ),
  EscapeTimeConfig(
    id: 'gerhardt_schuster_tyson_ca',
    name: 'Gerhardt-Schuster-Tyson CA',
    shaderAsset:
        'shaders/cellular_and_stochastic/gerhardt_schuster_tyson_ca_gpu.frag',
    defaultIterations: 64,
    defaultBailout: 4.0,
    category: 'Cellular Automata',
    extraParams: [
      _floatParam(
        id: 'threshold',
        label: 'Threshold',
        min: 1,
        max: 8,
        step: 1,
        defaultValue: 1.0,
      ),
      _floatParam(
        id: 'refractoryPeriod',
        label: 'Refractory Period',
        min: 2,
        max: 16,
        step: 1,
        defaultValue: 8.0,
      ),
      _floatParam(
        id: 'curvatureWeight',
        label: 'Curvature',
        min: 0,
        max: 1,
        step: 0.05,
        defaultValue: 0.3,
      ),
      _floatParam(
        id: 'dispersion',
        label: 'Dispersion',
        min: 0,
        max: 2,
        step: 0.05,
        defaultValue: 0.2,
      ),
    ],
  ),
  EscapeTimeConfig(
    id: 'mimura_murray_predator_prey',
    name: 'Mimura-Murray Predator-Prey',
    shaderAsset:
        'shaders/cellular_and_stochastic/mimura_murray_predator_prey_gpu.frag',
    defaultIterations: 64,
    defaultBailout: 4.0,
    category: 'Reaction-Diffusion',
    extraParams: [
      _floatParam(
        id: 'preyGrowth',
        label: 'Prey Growth',
        min: 0,
        max: 3,
        step: 0.05,
        defaultValue: 1.0,
      ),
      _floatParam(
        id: 'predation',
        label: 'Predation',
        min: 0,
        max: 3,
        step: 0.05,
        defaultValue: 1.0,
      ),
      _floatParam(
        id: 'predatorDeath',
        label: 'Predator Death',
        min: 0,
        max: 2,
        step: 0.05,
        defaultValue: 0.5,
      ),
      _floatParam(
        id: 'preyDiffusion',
        label: 'Prey Diffusion',
        min: 0,
        max: 2,
        step: 0.05,
        defaultValue: 0.05,
      ),
      _floatParam(
        id: 'predatorDiffusion',
        label: 'Predator Diffusion',
        min: 0,
        max: 3,
        step: 0.05,
        defaultValue: 1.0,
      ),
    ],
  ),
  EscapeTimeConfig(
    id: 'stable_square_turing_model',
    name: 'Stable-Square Turing Model',
    shaderAsset:
        'shaders/cellular_and_stochastic/stable_square_turing_model_gpu.frag',
    defaultIterations: 80,
    defaultBailout: 4.0,
    category: 'Reaction-Diffusion',
    extraParams: [
      _floatParam(
        id: 'diffusionU',
        label: 'Diffusion U',
        min: 0,
        max: 2,
        step: 0.05,
        defaultValue: 0.08,
      ),
      _floatParam(
        id: 'diffusionV',
        label: 'Diffusion V',
        min: 0,
        max: 3,
        step: 0.05,
        defaultValue: 1.0,
      ),
    ],
  ),
  EscapeTimeConfig(
    id: 'flow_lenia',
    name: 'Flow-Lenia',
    shaderAsset: 'shaders/cellular_and_stochastic/flow_lenia_gpu.frag',
    defaultIterations: 80,
    defaultBailout: 4.0,
    category: 'Cellular Automata',
    extraParams: [
      _floatParam(
        id: 'kernelRadius',
        label: 'Kernel Radius',
        min: 1,
        max: 32,
        step: 1,
        defaultValue: 13.0,
      ),
      _floatParam(
        id: 'growthCenter',
        label: 'Growth Center',
        min: 0,
        max: 1,
        step: 0.01,
        defaultValue: 0.15,
      ),
      _floatParam(
        id: 'growthWidth',
        label: 'Growth Width',
        min: 0.001,
        max: 0.2,
        step: 0.001,
        defaultValue: 0.015,
      ),
      _floatParam(
        id: 'dt',
        label: 'Dt',
        min: 0.01,
        max: 1,
        step: 0.01,
        defaultValue: 0.1,
      ),
    ],
  ),
  EscapeTimeConfig(
    id: 'coupled_logistic_map_lattice',
    name: 'Coupled Logistic Map Lattice',
    shaderAsset:
        'shaders/cellular_and_stochastic/coupled_logistic_map_lattice_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
    category: 'Spatiotemporal Chaos',
    extraParams: [
      _floatParam(
        id: 'r',
        label: 'R',
        min: 0,
        max: 4,
        step: 0.05,
        defaultValue: 3.9,
      ),
      _floatParam(
        id: 'coupling',
        label: 'Coupling',
        min: 0,
        max: 1,
        step: 0.01,
        defaultValue: 0.18,
      ),
    ],
  ),
  EscapeTimeConfig(
    id: 'langton_ant',
    name: "Langton's Ant",
    shaderAsset: 'shaders/cellular_and_stochastic/langton_ant_gpu.frag',
    defaultIterations: 260,
    defaultBailout: 4.0,
  ),
  EscapeTimeConfig(
    id: 'turmite',
    name: 'Turmite',
    shaderAsset: 'shaders/cellular_and_stochastic/turmite_gpu.frag',
    defaultIterations: 280,
    defaultBailout: 4.0,
  ),
  EscapeTimeConfig(
    id: 'wireworld',
    name: 'Wireworld',
    shaderAsset: 'shaders/cellular_and_stochastic/wireworld_gpu.frag',
    defaultIterations: 220,
    defaultBailout: 4.0,
  ),
  EscapeTimeConfig(
    id: 'sandpile',
    name: 'Abelian Sandpile',
    shaderAsset: 'shaders/cellular_and_stochastic/sandpile_gpu.frag',
    defaultIterations: 280,
    defaultBailout: 4.0,
  ),
  EscapeTimeConfig(
    id: 'dla',
    name: 'DLA (Approximation)',
    shaderAsset: 'shaders/cellular_and_stochastic/dla_gpu.frag',
    defaultIterations: 220,
    defaultBailout: 4.0,
  ),
  EscapeTimeConfig(
    id: 'forest_fire',
    name: 'Forest Fire Model',
    shaderAsset: 'shaders/cellular_and_stochastic/forest_fire_gpu.frag',
    defaultIterations: 220,
    defaultBailout: 4.0,
  ),
  EscapeTimeConfig(
    id: 'percolation',
    name: 'Percolation Cluster',
    shaderAsset: 'shaders/cellular_and_stochastic/percolation_gpu.frag',
    defaultIterations: 240,
    defaultBailout: 4.0,
  ),
  EscapeTimeConfig(
    id: 'brian_brain',
    name: "Brian's Brain",
    shaderAsset: 'shaders/cellular_and_stochastic/brian_brain_gpu.frag',
    defaultIterations: 260,
    defaultBailout: 4.0,
  ),
  EscapeTimeConfig(
    id: 'highlife',
    name: 'HighLife',
    shaderAsset: 'shaders/cellular_and_stochastic/highlife_gpu.frag',
    defaultIterations: 260,
    defaultBailout: 4.0,
  ),
  EscapeTimeConfig(
    id: 'day_night',
    name: 'Day & Night',
    shaderAsset: 'shaders/cellular_and_stochastic/day_night_gpu.frag',
    defaultIterations: 260,
    defaultBailout: 4.0,
  ),
  EscapeTimeConfig(
    id: 'seeds_ca',
    name: 'Seeds CA',
    shaderAsset: 'shaders/cellular_and_stochastic/seeds_ca_gpu.frag',
    defaultIterations: 240,
    defaultBailout: 4.0,
  ),
  EscapeTimeConfig(
    id: 'maze_ca',
    name: 'Maze CA',
    shaderAsset: 'shaders/cellular_and_stochastic/maze_ca_gpu.frag',
    defaultIterations: 260,
    defaultBailout: 4.0,
    extraParams: [
      _floatParam(
        id: 'birthMask',
        label: 'Birth mask',
        min: 0,
        max: 511,
        step: 1,
        defaultValue: 8.0,
      ),
      _floatParam(
        id: 'survivalMask',
        label: 'Survival mask',
        min: 0,
        max: 511,
        step: 1,
        defaultValue: 62.0,
      ),
    ],
  ),
  EscapeTimeConfig(
    id: 'cyclic_ca',
    name: 'Cyclic CA',
    shaderAsset: 'shaders/cellular_and_stochastic/cyclic_ca_gpu.frag',
    defaultIterations: 260,
    defaultBailout: 4.0,
    extraParams: [
      _floatParam(
        id: 'states',
        label: 'States',
        min: 2,
        max: 32,
        step: 1,
        defaultValue: 8.0,
      ),
    ],
  ),
  EscapeTimeConfig(
    id: 'replicator_ca',
    name: 'Replicator CA',
    shaderAsset: 'shaders/cellular_and_stochastic/replicator_ca_gpu.frag',
    defaultIterations: 260,
    defaultBailout: 4.0,
    extraParams: [
      _floatParam(
        id: 'birthMask',
        label: 'Birth mask',
        min: 0,
        max: 511,
        step: 1,
        defaultValue: 170.0,
      ),
      _floatParam(
        id: 'survivalMask',
        label: 'Survival mask',
        min: 0,
        max: 511,
        step: 1,
        defaultValue: 170.0,
      ),
    ],
  ),
  EscapeTimeConfig(
    id: 'hodgepodge_machine',
    name: 'Hodgepodge Machine',
    shaderAsset: 'shaders/cellular_and_stochastic/hodgepodge_machine_gpu.frag',
    defaultIterations: 260,
    defaultBailout: 4.0,
  ),
  EscapeTimeConfig(
    id: 'eden_growth',
    name: 'Eden Growth Model',
    shaderAsset: 'shaders/cellular_and_stochastic/eden_growth_gpu.frag',
    defaultIterations: 280,
    defaultBailout: 4.0,
  ),

// All remaining fractals already registered by subagent batches above.

  EscapeTimeConfig(
    id: 'farey_diagram',
    name: 'Farey Diagram',
    shaderAsset:
        'shaders/escape_time_family/geometry_and_ifs/farey_diagram_gpu.frag',
    defaultIterations: 140,
    defaultCenterX: 0.0,
    defaultCenterY: 0.2,
    defaultBailout: 4.0,
  ),
  EscapeTimeConfig(
    id: 'cayley_graph',
    name: 'Cayley Graph Fractal',
    shaderAsset: 'shaders/ifs_and_geometric/cayley_graph_gpu.frag',
    defaultIterations: 180,
    defaultBailout: 4.0,
  ),
  EscapeTimeConfig(
    id: 'sierpinski_arrowhead',
    name: 'Sierpinski Arrowhead',
    shaderAsset: 'shaders/ifs_and_geometric/sierpinski_arrowhead_gpu.frag',
    defaultIterations: 180,
    defaultBailout: 4.0,
  ),
  EscapeTimeConfig(
    id: 'mcworter_pentigree',
    name: "McWorter's Pentigree",
    shaderAsset: 'shaders/ifs_and_geometric/mcworter_pentigree_gpu.frag',
    defaultIterations: 180,
    defaultBailout: 4.0,
  ),
  EscapeTimeConfig(
    id: 'ammann_beenker',
    name: 'Ammann-Beenker Tiling',
    shaderAsset: 'shaders/ifs_and_geometric/ammann_beenker_gpu.frag',
    defaultIterations: 180,
    defaultBailout: 4.0,
  ),
  EscapeTimeConfig(
    id: 'moore_curve',
    name: 'Moore Curve',
    shaderAsset: 'shaders/ifs_and_geometric/moore_curve_gpu.frag',
    defaultIterations: 180,
    defaultBailout: 4.0,
  ),
  EscapeTimeConfig(
    id: 'lambda_w',
    name: 'Lambda W Fractal',
    shaderAsset:
        'shaders/escape_time_family/transcendental_maps/lambda_w_gpu.frag',
    defaultIterations: 100,
    defaultBailout: 8.0,
    extraPresets: [
      catalogPreset(
        id: 'lambda_w-relief',
        moduleId: 'lambda_w',
        name: 'Lambert W Relief',
        params: {'iterations': 100, 'bailout': 8.0, 'colorScheme': 59},
        view: FractalViewState(
            pan: Vector2(0.0, 0.0), zoom: 1.0, rotation: Vector3.zero()),
      ),
    ],
  ),
  EscapeTimeConfig(
    id: 'riemann_zeta',
    name: 'Riemann Zeta Fractal',
    shaderAsset:
        'shaders/trigonometric_and_transcendental/special_functions/zeta_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 8.0,
    extraPresets: [
      catalogPreset(
        id: 'riemann_zeta-relief',
        moduleId: 'riemann_zeta',
        name: 'Zeta Relief',
        params: {'iterations': 120, 'bailout': 8.0, 'colorScheme': 51},
        view: FractalViewState(
            pan: Vector2(0.0, 0.0), zoom: 1.0, rotation: Vector3.zero()),
      ),
    ],
  ),
  EscapeTimeConfig(
    id: 'manair_fire',
    name: 'Man-Air-Fire',
    shaderAsset:
        'shaders/escape_time_family/experimental_named/physical_simulation/manair_fire_gpu.frag',
    defaultIterations: 160,
  ),
  EscapeTimeConfig(
    id: 'spider_x',
    name: 'Spider-X',
    shaderAsset:
        'shaders/escape_time_family/experimental_named/coupled_orbits/spider_x_gpu.frag',
    defaultIterations: 160,
    extraPresets: [
      catalogPreset(
        id: 'spider_x-relief',
        moduleId: 'spider_x',
        name: 'Spider Relief',
        params: {'iterations': 160, 'bailout': 4.0, 'colorScheme': 56},
        view: FractalViewState(
            pan: Vector2(0.0, 0.0), zoom: 1.0, rotation: Vector3.zero()),
      ),
    ],
  ),
  EscapeTimeConfig(
    id: 'popcorn2',
    name: 'Popcorn II',
    shaderAsset:
        'shaders/escape_time_family/transcendental_maps/popcorn2_gpu.frag',
    defaultIterations: 160,
    defaultBailout: 4.0,
  ),
  EscapeTimeConfig(
    id: 'chebyshev',
    name: 'Chebyshev Fractal',
    shaderAsset:
        'shaders/escape_time_family/newton_and_orthogonal/orthogonal_polynomial_maps/chebyshev_gpu.frag',
    defaultIterations: 140,
    defaultBailout: 6.0,
    extraPresets: [
      catalogPreset(
        id: 'chebyshev-relief',
        moduleId: 'chebyshev',
        name: 'Chebyshev Relief',
        params: {'iterations': 140, 'bailout': 6.0, 'colorScheme': 54},
        view: FractalViewState(
            pan: Vector2(0.0, 0.0), zoom: 1.0, rotation: Vector3.zero()),
      ),
    ],
  ),
  EscapeTimeConfig(
    id: 'legendre',
    name: 'Legendre Fractal',
    shaderAsset:
        'shaders/escape_time_family/newton_and_orthogonal/orthogonal_polynomial_maps/legendre_gpu.frag',
    defaultIterations: 140,
    defaultBailout: 6.0,
  ),
  EscapeTimeConfig(
    id: 'laguerre',
    name: 'Laguerre Fractal',
    shaderAsset:
        'shaders/escape_time_family/newton_and_orthogonal/orthogonal_polynomial_maps/laguerre_gpu.frag',
    defaultIterations: 110,
    defaultBailout: 6.0,
  ),
  EscapeTimeConfig(
    id: 'hermite',
    name: 'Hermite Fractal',
    shaderAsset:
        'shaders/escape_time_family/newton_and_orthogonal/orthogonal_polynomial_maps/hermite_gpu.frag',
    defaultIterations: 140,
    defaultBailout: 6.0,
  ),
  EscapeTimeConfig(
    id: 'virial',
    name: 'Virial Fractal',
    shaderAsset:
        'shaders/escape_time_family/newton_and_orthogonal/series_maps/virial_gpu.frag',
    defaultIterations: 150,
    extraPresets: [
      catalogPreset(
        id: 'virial-relief',
        moduleId: 'virial',
        name: 'Virial Relief',
        params: {'iterations': 150, 'bailout': 4.0, 'colorScheme': 55},
        view: FractalViewState(
            pan: Vector2(0.0, 0.0), zoom: 1.0, rotation: Vector3.zero()),
      ),
    ],
  ),
  EscapeTimeConfig(
    id: 'newton_sin',
    name: 'Newton sin(z)',
    shaderAsset: 'shaders/root_finding/newton_sin_gpu.frag',
    defaultIterations: 90,
    defaultBailout: 4.0,
  ),
  EscapeTimeConfig(
    id: 'newton_general',
    name: 'Newton Fractal (z⁴ - 1)',
    shaderAsset: 'shaders/root_finding/newton_general_gpu.frag',
    defaultIterations: 90,
    defaultBailout: 4.0,
  ),
  EscapeTimeConfig(
    id: 'multibrot4',
    name: 'Multibrot d=4',
    shaderAsset:
        'shaders/escape_time_family/families/multibrot/integer_powers/multibrot4_gpu.frag',
    defaultIterations: 160,
    extraPresets: [
      catalogPreset(
        id: 'multibrot4-relief-quad',
        moduleId: 'multibrot4',
        name: 'Bas-Relief: Quad',
        params: {'iterations': 200, 'bailout': 4.0, 'colorScheme': 50},
        view: FractalViewState(
            pan: Vector2(0.0, 0.0), zoom: 1.0, rotation: Vector3.zero()),
      ),
    ],
  ),
  EscapeTimeConfig(
    id: 'multibrot5',
    name: 'Multibrot d=5',
    shaderAsset:
        'shaders/escape_time_family/families/multibrot/multibrot5_gpu.frag',
    defaultIterations: 170,
    extraPresets: [
      catalogPreset(
        id: 'multibrot5-relief-quint',
        moduleId: 'multibrot5',
        name: 'Bas-Relief: Quint',
        params: {'iterations': 200, 'bailout': 4.0, 'colorScheme': 50},
        view: FractalViewState(
            pan: Vector2(0.0, 0.0), zoom: 1.0, rotation: Vector3.zero()),
      ),
    ],
  ),
  EscapeTimeConfig(
    id: 'sierpinski_tetrahedron',
    name: 'Sierpinski Tetrahedron (2D Projection)',
    shaderAsset: 'shaders/ifs_and_geometric/sierpinski_tetrahedron_gpu.frag',
    defaultIterations: 160,
    defaultBailout: 4.0,
  ),
  EscapeTimeConfig(
    id: 'jerusalem_cube',
    name: 'Jerusalem Cube (2D Cross-Section)',
    shaderAsset: 'shaders/ifs_and_geometric/jerusalem_cube_gpu.frag',
    defaultIterations: 160,
    defaultBailout: 4.0,
  ),
  EscapeTimeConfig(
    id: 'menger_3d_slice',
    name: 'Menger Sponge (3D Slice)',
    shaderAsset:
        'shaders/ifs_and_geometric/self_similar_sets/menger_3d_slice_gpu.frag',
    defaultIterations: 150,
    defaultBailout: 4.0,
  ),
  EscapeTimeConfig(
    id: 'pola_sierpinski',
    name: 'Pola-Sierpinski Hybrid',
    shaderAsset: 'shaders/ifs_and_geometric/pola_sierpinski_gpu.frag',
    defaultIterations: 170,
    defaultBailout: 4.0,
  ),
  EscapeTimeConfig(
    id: 'fibonacci_spiral',
    name: 'Fibonacci Spiral Fractal',
    shaderAsset: 'shaders/ifs_and_geometric/fibonacci_spiral_gpu.frag',
    defaultIterations: 180,
    defaultBailout: 4.0,
  ),
];
