part of '../escape_time_catalog.dart';

final List<EscapeTimeConfig> _ifsGeometricFractalsCatalog = [
// ── XI. IFS / Geometric Fractals ───────────────────────
  EscapeTimeConfig(
    id: 'sierpinski_triangle',
    name: 'Sierpinski Triangle',
    shaderAsset: 'shaders/ifs_and_geometric/sierpinski_triangle_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
  ),
  EscapeTimeConfig(
    id: 'sierpinski_carpet',
    name: 'Sierpinski Carpet',
    shaderAsset: 'shaders/ifs_and_geometric/sierpinski_carpet_gpu.frag',
    defaultIterations: 100,
    defaultBailout: 4.0,
  ),
  EscapeTimeConfig(
    id: 'koch_snowflake',
    name: 'Koch Snowflake',
    shaderAsset: 'shaders/ifs_and_geometric/koch_snowflake_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 6.0,
  ),
  EscapeTimeConfig(
    id: 'dragon_curve',
    name: 'Dragon Curve',
    shaderAsset: 'shaders/ifs_and_geometric/dragon_curve_gpu.frag',
    defaultIterations: 140,
    defaultBailout: 8.0,
  ),
  EscapeTimeConfig(
    id: 'barnsley_fern',
    name: 'Barnsley Fern',
    shaderAsset: 'shaders/ifs_and_geometric/barnsley_fern_gpu.frag',
    defaultIterations: 120,
    defaultCenterY: 0.2,
    defaultBailout: 6.0,
  ),
  EscapeTimeConfig(
    id: 'pythagorean_tree',
    name: 'Pythagorean Tree',
    shaderAsset: 'shaders/ifs_and_geometric/pythagorean_tree_gpu.frag',
    defaultIterations: 120,
    defaultCenterY: -0.15,
    defaultBailout: 6.0,
  ),
  EscapeTimeConfig(
    id: 'hilbert_curve',
    name: 'Hilbert Curve',
    shaderAsset: 'shaders/ifs_and_geometric/hilbert_curve_gpu.frag',
    defaultIterations: 160,
    defaultBailout: 4.0,
  ),
  EscapeTimeConfig(
    id: 'peano_curve',
    name: 'Peano Curve',
    shaderAsset: 'shaders/ifs_and_geometric/peano_curve_gpu.frag',
    defaultIterations: 140,
    defaultBailout: 4.0,
  ),
  EscapeTimeConfig(
    id: 'gosper_curve',
    name: 'Gosper Curve',
    shaderAsset: 'shaders/ifs_and_geometric/gosper_curve_gpu.frag',
    defaultIterations: 180,
    defaultBailout: 6.0,
  ),
  EscapeTimeConfig(
    id: 'levy_c_curve',
    name: 'Lévy C Curve',
    shaderAsset: 'shaders/ifs_and_geometric/levy_c_gpu.frag',
    defaultIterations: 180,
    defaultBailout: 6.0,
  ),
  EscapeTimeConfig(
    id: 'levy_tapestry',
    name: 'Lévy Tapestry',
    shaderAsset: 'shaders/ifs_and_geometric/levy_tapestry_gpu.frag',
    defaultIterations: 220,
    defaultBailout: 6.0,
  ),
  EscapeTimeConfig(
    id: 'golden_dragon',
    name: 'Golden Dragon',
    shaderAsset: 'shaders/ifs_and_geometric/golden_dragon_gpu.frag',
    defaultIterations: 170,
    defaultBailout: 8.0,
    defaultCenterX: 0.56,
    defaultCenterY: 0.4,
    defaultZoom: 0.75,
  ),
  EscapeTimeConfig(
    id: 'twin_dragon',
    name: 'Twin Dragon',
    shaderAsset: 'shaders/ifs_and_geometric/twin_dragon_gpu.frag',
    defaultIterations: 170,
    defaultBailout: 8.0,
  ),
  EscapeTimeConfig(
    id: 'terdragon',
    name: 'Terdragon',
    shaderAsset: 'shaders/ifs_and_geometric/terdragon_gpu.frag',
    defaultIterations: 170,
    defaultBailout: 8.0,
  ),
  EscapeTimeConfig(
    id: 'chair_tiling',
    name: 'Chair Tiling',
    shaderAsset: 'shaders/ifs_and_geometric/chair_tiling_gpu.frag',
    defaultIterations: 150,
    defaultBailout: 6.0,
  ),
  EscapeTimeConfig(
    id: 'koch_anti_snowflake',
    name: 'Koch Anti-Snowflake',
    shaderAsset: 'shaders/ifs_and_geometric/koch_anti_snowflake_gpu.frag',
    defaultIterations: 150,
    defaultBailout: 6.0,
  ),
  EscapeTimeConfig(
    id: 'quadratic_koch_island',
    name: 'Quadratic Koch Island',
    shaderAsset:
        'shaders/escape_time_family/geometry_and_ifs/quadratic_koch_gpu.frag',
    defaultIterations: 160,
    defaultBailout: 6.0,
  ),
  EscapeTimeConfig(
    id: 'cyclosorus_fern',
    name: 'Cyclosorus Fern',
    shaderAsset: 'shaders/ifs_and_geometric/cyclosorus_fern_gpu.frag',
    defaultIterations: 200,
    defaultCenterY: 0.2,
    defaultBailout: 6.0,
  ),
  EscapeTimeConfig(
    id: 'menger_sponge_2d',
    name: 'Menger Sponge (2D Cross-Section)',
    shaderAsset:
        'shaders/ifs_and_geometric/self_similar_sets/menger_sponge_gpu.frag',
    defaultIterations: 140,
    defaultBailout: 4.0,
  ),
  EscapeTimeConfig(
    id: 'vicsek_fractal',
    name: 'Vicsek Fractal',
    shaderAsset: 'shaders/ifs_and_geometric/vicsek_gpu.frag',
    defaultIterations: 140,
    defaultBailout: 4.0,
  ),
  EscapeTimeConfig(
    id: 'penrose_tiling',
    name: 'Penrose Tiling (P3)',
    shaderAsset: 'shaders/ifs_and_geometric/penrose_tiling_gpu.frag',
    defaultIterations: 180,
    defaultBailout: 4.0,
  ),
  EscapeTimeConfig(
    id: 'fibonacci_word',
    name: 'Fibonacci Word Fractal',
    shaderAsset: 'shaders/ifs_and_geometric/fibonacci_word_gpu.frag',
    defaultIterations: 160,
    defaultBailout: 4.0,
    defaultCenterX: 0.2,
    defaultZoom: 0.4,
  ),
  EscapeTimeConfig(
    id: 'rauzy_fractal',
    name: 'Rauzy Fractal',
    shaderAsset: 'shaders/ifs_and_geometric/rauzy_gpu.frag',
    defaultIterations: 200,
    defaultBailout: 4.0,
  ),
  EscapeTimeConfig(
    id: 'arnoux_rauzy_fractal',
    name: 'Arnoux-Rauzy Fractal',
    shaderAsset: 'shaders/ifs_and_geometric/arnoux_rauzy_fractal_gpu.frag',
    defaultIterations: 160,
    defaultBailout: 4.0,
    category: 'Aperiodic Tiling',
    extraParams: [
      _floatParam(
        id: 'depth',
        label: 'Depth',
        min: 3,
        max: 18,
        step: 1,
        defaultValue: 12.0,
      ),
    ],
    extraPresets: [
      catalogPreset(
        id: 'arnoux-rauzy-window',
        moduleId: 'arnoux_rauzy_fractal',
        name: 'Rauzy Window',
        params: {
          'iterations': 160,
          'bailout': 4.0,
          'colorScheme': 0,
          'depth': 12.0,
        },
        view: FractalViewState(
            pan: Vector2(0.0, 0.0), zoom: 1.0, rotation: Vector3.zero()),
      ),
    ],
  ),
  EscapeTimeConfig(
    id: 'dual_substitution_tiling',
    name: 'Dual Substitution Tiling',
    shaderAsset: 'shaders/ifs_and_geometric/dual_substitution_tiling_gpu.frag',
    defaultIterations: 10,
    defaultBailout: 4.0,
    category: 'Aperiodic Tiling',
    extraParams: [
      _floatParam(
        id: 'depth',
        label: 'Depth',
        min: 3,
        max: 14,
        step: 1,
        defaultValue: 8.0,
      ),
    ],
  ),
  EscapeTimeConfig(
    id: 'bedford_mcmullen_carpet',
    name: 'Bedford-McMullen Carpet',
    shaderAsset: 'shaders/ifs_and_geometric/bedford_mcmullen_carpet_gpu.frag',
    defaultIterations: 10,
    defaultBailout: 4.0,
    category: 'Self-Affine IFS',
    extraParams: [
      _floatParam(
        id: 'depth',
        label: 'Depth',
        min: 1,
        max: 14,
        step: 1,
        defaultValue: 10.0,
      ),
    ],
  ),
  EscapeTimeConfig(
    id: 'self_affine_finite_type',
    name: 'Self-Affine Finite-Type Fractal',
    shaderAsset: 'shaders/ifs_and_geometric/self_affine_finite_type_gpu.frag',
    defaultIterations: 12,
    defaultBailout: 4.0,
    category: 'Self-Affine IFS',
    extraParams: [
      _floatParam(
        id: 'depth',
        label: 'Depth',
        min: 2,
        max: 16,
        step: 1,
        defaultValue: 12.0,
      ),
    ],
  ),
  EscapeTimeConfig(
    id: 'pinwheel_tiling',
    name: 'Pinwheel Tiling',
    shaderAsset: 'shaders/ifs_and_geometric/pinwheel_gpu.frag',
    defaultIterations: 180,
    defaultBailout: 4.0,
  ),
  EscapeTimeConfig(
    id: 'z_order_curve',
    name: 'Z-Order Curve (Morton)',
    shaderAsset: 'shaders/ifs_and_geometric/z_order_curve_gpu.frag',
    defaultIterations: 180,
    defaultBailout: 4.0,
  ),
  EscapeTimeConfig(
    id: 'greek_cross_fractal',
    name: 'Greek Cross Fractal',
    shaderAsset: 'shaders/ifs_and_geometric/greek_cross_gpu.frag',
    defaultIterations: 160,
    defaultBailout: 4.0,
  ),
  EscapeTimeConfig(
    id: 'sierpinski_pentagon',
    name: 'Sierpinski Pentagon',
    shaderAsset: 'shaders/ifs_and_geometric/sierpinski_pentagon_gpu.frag',
    defaultIterations: 140,
    defaultBailout: 4.0,
  ),
  EscapeTimeConfig(
    id: 'hexaflake',
    name: 'Hexaflake',
    shaderAsset: 'shaders/ifs_and_geometric/hexaflake_gpu.frag',
    defaultIterations: 140,
    defaultBailout: 4.0,
  ),
  EscapeTimeConfig(
    id: 'pentaflake',
    name: 'Pentaflake',
    shaderAsset: 'shaders/ifs_and_geometric/pentaflake_gpu.frag',
    defaultIterations: 140,
    defaultBailout: 4.0,
  ),
  EscapeTimeConfig(
    id: 'cantor_dust',
    name: 'Cantor Dust',
    shaderAsset: 'shaders/ifs_and_geometric/cantor_dust_gpu.frag',
    defaultIterations: 160,
    defaultBailout: 4.0,
  ),
  EscapeTimeConfig(
    id: 'apollonian_gasket',
    name: 'Apollonian Gasket',
    shaderAsset: 'shaders/ifs_and_geometric/apollonian_gasket_gpu.frag',
    defaultIterations: 180,
    defaultBailout: 4.0,
  ),
  EscapeTimeConfig(
    id: 'ford_circles',
    name: 'Ford Circles',
    shaderAsset: 'shaders/ifs_and_geometric/ford_circles_gpu.frag',
    defaultIterations: 140,
    defaultBailout: 4.0,
  ),
  EscapeTimeConfig(
    id: 'steiner_chain',
    name: 'Steiner Chain',
    shaderAsset: 'shaders/ifs_and_geometric/steiner_chain_gpu.frag',
    defaultIterations: 160,
    defaultBailout: 4.0,
  ),
  EscapeTimeConfig(
    id: 'cesaro_fractal',
    name: 'Cesàro Fractal',
    shaderAsset: 'shaders/ifs_and_geometric/cesaro_gpu.frag',
    defaultIterations: 180,
    defaultBailout: 4.0,
  ),
  EscapeTimeConfig(
    id: 'cantor_set',
    name: 'Cantor Set',
    shaderAsset: 'shaders/ifs_and_geometric/cantor_set_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
  ),
  EscapeTimeConfig(
    id: 'fractal_canopy',
    name: 'Fractal Canopy',
    shaderAsset: 'shaders/ifs_and_geometric/fractal_canopy_gpu.frag',
    defaultIterations: 80,
    // Keep canopy iteration cap lower than generic escape-time modules to
    // avoid runaway branch expansion on mobile GPUs.
    maxIterations: 120,
    defaultCenterY: -0.15,
    defaultBailout: 4.0,
  ),
  EscapeTimeConfig(
    id: 'benesi',
    name: 'Benesi Fractal',
    shaderAsset: 'shaders/escape_time_family/polynomial_maps/benesi_gpu.frag',
    defaultIterations: 220,
    defaultBailout: 8.0,
  ),
  EscapeTimeConfig(
    id: 'pseudo_kleinian',
    name: 'Pseudo-Kleinian',
    shaderAsset: 'shaders/ifs_and_geometric/pseudo_kleinian_gpu.frag',
    defaultIterations: 220,
    defaultBailout: 10.0,
  ),
  EscapeTimeConfig(
    id: 'schottky_limit_set',
    name: 'Schottky Limit Set',
    shaderAsset: 'shaders/ifs_and_geometric/schottky_limit_set_gpu.frag',
    defaultIterations: 120,
    defaultCenterX: 0.0,
    defaultCenterY: 0.0,
    defaultZoom: 0.85,
    defaultBailout: 4.0,
    maxIterations: 160,
  ),
];
