part of '../escape_time_catalog.dart';

final List<EscapeTimeConfig> _kaleidoscopesCatalog = [
// ── XVI. Kaleidoscopes ────────────────────────────────
  EscapeTimeConfig(
    id: 'kaleidoscope_basic',
    name: 'Kaleidoscope Basic',
    displayName: (l10n) => 'Kaleidoscope Basic',
    category: 'Kaleidoscopes',
    shaderAsset:
        'shaders/kaleidoscopes/classic_symmetry/kaleidoscope_basic_gpu.frag',
    defaultIterations: 1,
    defaultBailout: 4.0,
    defaultColorScheme: 0,
    defaultZoom: 1.0,
    defaultCenterX: 0.0,
    defaultCenterY: 0.0,
  ),
  EscapeTimeConfig(
    id: 'kaleidoscope_rays',
    name: 'Kaleidoscope Rays',
    displayName: (l10n) => 'Kaleidoscope Rays',
    category: 'Kaleidoscopes',
    shaderAsset:
        'shaders/kaleidoscopes/radial_ornaments/kaleidoscope_rays_gpu.frag',
    defaultIterations: 1,
    defaultBailout: 4.0,
    defaultColorScheme: 1,
    defaultZoom: 1.0,
    defaultCenterX: 0.0,
    defaultCenterY: 0.0,
  ),
  EscapeTimeConfig(
    id: 'kaleidoscope_mandala',
    name: 'Kaleidoscope Mandala',
    displayName: (l10n) => 'Kaleidoscope Mandala',
    category: 'Kaleidoscopes',
    shaderAsset:
        'shaders/kaleidoscopes/classic_symmetry/kaleidoscope_mandala_gpu.frag',
    defaultIterations: 1,
    defaultBailout: 4.0,
    defaultColorScheme: 2,
    defaultZoom: 1.0,
    defaultCenterX: 0.0,
    defaultCenterY: 0.0,
  ),
  EscapeTimeConfig(
    id: 'kaleidoscope_star',
    name: 'Kaleidoscope Star',
    displayName: (l10n) => 'Kaleidoscope Star',
    category: 'Kaleidoscopes',
    shaderAsset:
        'shaders/kaleidoscopes/radial_ornaments/kaleidoscope_star_gpu.frag',
    defaultIterations: 1,
    defaultBailout: 4.0,
    defaultColorScheme: 0,
    defaultZoom: 1.0,
    defaultCenterX: 0.0,
    defaultCenterY: 0.0,
  ),
  EscapeTimeConfig(
    id: 'kaleidoscope_snowflake',
    name: 'Kaleidoscope Snowflake',
    displayName: (l10n) => 'Kaleidoscope Snowflake',
    category: 'Kaleidoscopes',
    shaderAsset:
        'shaders/kaleidoscopes/classic_symmetry/kaleidoscope_snowflake_gpu.frag',
    defaultIterations: 1,
    defaultBailout: 4.0,
    defaultColorScheme: 3,
    defaultZoom: 1.0,
    defaultCenterX: 0.0,
    defaultCenterY: 0.0,
  ),
  EscapeTimeConfig(
    id: 'kaleidoscope_flower',
    name: 'Kaleidoscope Flower',
    displayName: (l10n) => 'Kaleidoscope Flower',
    category: 'Kaleidoscopes',
    shaderAsset:
        'shaders/kaleidoscopes/radial_ornaments/kaleidoscope_flower_gpu.frag',
    defaultIterations: 1,
    defaultBailout: 4.0,
    defaultColorScheme: 1,
    defaultZoom: 1.0,
    defaultCenterX: 0.0,
    defaultCenterY: 0.0,
  ),
  EscapeTimeConfig(
    id: 'kaleidoscope_jewel',
    name: 'Kaleidoscope Jewel',
    displayName: (l10n) => 'Kaleidoscope Jewel',
    category: 'Kaleidoscopes',
    shaderAsset:
        'shaders/kaleidoscopes/textured_light/kaleidoscope_jewel_gpu.frag',
    defaultIterations: 1,
    defaultBailout: 4.0,
    defaultColorScheme: 2,
    defaultZoom: 1.0,
    defaultCenterX: 0.0,
    defaultCenterY: 0.0,
  ),
  EscapeTimeConfig(
    id: 'kaleidoscope_spiral',
    name: 'Kaleidoscope Spiral',
    displayName: (l10n) => 'Kaleidoscope Spiral',
    category: 'Kaleidoscopes',
    shaderAsset:
        'shaders/kaleidoscopes/radial_ornaments/kaleidoscope_spiral_gpu.frag',
    defaultIterations: 1,
    defaultBailout: 4.0,
    defaultColorScheme: 0,
    defaultZoom: 1.0,
    defaultCenterX: 0.0,
    defaultCenterY: 0.0,
  ),
  EscapeTimeConfig(
    id: 'kaleidoscope_geometric',
    name: 'Kaleidoscope Geometric',
    displayName: (l10n) => 'Kaleidoscope Geometric',
    category: 'Kaleidoscopes',
    shaderAsset:
        'shaders/kaleidoscopes/classic_symmetry/kaleidoscope_geometric_gpu.frag',
    defaultIterations: 1,
    defaultBailout: 4.0,
    defaultColorScheme: 1,
    defaultZoom: 1.0,
    defaultCenterX: 0.0,
    defaultCenterY: 0.0,
  ),
  EscapeTimeConfig(
    id: 'kaleidoscope_crystal',
    name: 'Kaleidoscope Crystal',
    displayName: (l10n) => 'Kaleidoscope Crystal',
    category: 'Kaleidoscopes',
    shaderAsset:
        'shaders/kaleidoscopes/classic_symmetry/kaleidoscope_crystal_gpu.frag',
    defaultIterations: 1,
    defaultBailout: 4.0,
    defaultColorScheme: 2,
    defaultZoom: 1.0,
    defaultCenterX: 0.0,
    defaultCenterY: 0.0,
  ),
  EscapeTimeConfig(
    id: 'kaleidoscope_wave',
    name: 'Kaleidoscope Wave',
    displayName: (l10n) => 'Kaleidoscope Wave',
    category: 'Kaleidoscopes',
    shaderAsset:
        'shaders/kaleidoscopes/radial_ornaments/kaleidoscope_wave_gpu.frag',
    defaultIterations: 1,
    defaultBailout: 4.0,
    defaultColorScheme: 0,
    defaultZoom: 1.0,
    defaultCenterX: 0.0,
    defaultCenterY: 0.0,
  ),
  EscapeTimeConfig(
    id: 'kaleidoscope_fractal',
    name: 'Kaleidoscope Fractal',
    displayName: (l10n) => 'Kaleidoscope Fractal',
    category: 'Kaleidoscopes',
    shaderAsset:
        'shaders/kaleidoscopes/textured_light/kaleidoscope_fractal_gpu.frag',
    defaultIterations: 1,
    defaultBailout: 4.0,
    defaultColorScheme: 1,
    defaultZoom: 1.0,
    defaultCenterX: 0.0,
    defaultCenterY: 0.0,
  ),
  EscapeTimeConfig(
    id: 'kaleidoscope_rosette',
    name: 'Kaleidoscope Rosette',
    displayName: (l10n) => 'Kaleidoscope Rosette',
    category: 'Kaleidoscopes',
    shaderAsset:
        'shaders/kaleidoscopes/classic_symmetry/kaleidoscope_rosette_gpu.frag',
    defaultIterations: 1,
    defaultBailout: 4.0,
    defaultColorScheme: 2,
    defaultZoom: 1.0,
    defaultCenterX: 0.0,
    defaultCenterY: 0.0,
  ),
  EscapeTimeConfig(
    id: 'kaleidoscope_ring',
    name: 'Kaleidoscope Ring',
    displayName: (l10n) => 'Kaleidoscope Ring',
    category: 'Kaleidoscopes',
    shaderAsset:
        'shaders/kaleidoscopes/radial_ornaments/kaleidoscope_ring_gpu.frag',
    defaultIterations: 1,
    defaultBailout: 4.0,
    defaultColorScheme: 0,
    defaultZoom: 1.0,
    defaultCenterX: 0.0,
    defaultCenterY: 0.0,
  ),
  EscapeTimeConfig(
    id: 'kaleidoscope_nebula',
    name: 'Kaleidoscope Nebula',
    displayName: (l10n) => 'Kaleidoscope Nebula',
    category: 'Kaleidoscopes',
    shaderAsset:
        'shaders/kaleidoscopes/textured_light/kaleidoscope_nebula_gpu.frag',
    defaultIterations: 1,
    defaultBailout: 4.0,
    defaultColorScheme: 3,
    defaultZoom: 1.0,
    defaultCenterX: 0.0,
    defaultCenterY: 0.0,
  ),

// === Merged from pre-force-update local catalog ===
  EscapeTimeConfig(
    id: 'alternated_iteration',
    name: 'Alternated Iteration',
    shaderAsset:
        'shaders/escape_time_family/experimental_named/coupled_orbits/alternated_iteration_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
    category: 'Escape-Time',
  ),
  EscapeTimeConfig(
    id: 'bedhead',
    name: 'Bedhead',
    shaderAsset:
        'shaders/escape_time_family/experimental_named/discrete_attractors/bedhead_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
    category: 'Escape-Time',
  ),
  EscapeTimeConfig(
    id: 'bogdanov_map',
    name: 'Bogdanov Map',
    shaderAsset: 'shaders/strange_attractors/bogdanov_map_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
    category: 'Escape-Time',
  ),
  EscapeTimeConfig(
    id: 'buddhabrot_full',
    name: 'Buddhabrot Full',
    shaderAsset:
        'shaders/escape_time_family/families/buddhabrot/buddhabrot_full_gpu.frag',
    defaultIterations: 160,
    defaultBailout: 4.0,
    category: 'Escape-Time',
    extraParams: [
      _floatParam(
        id: 'samples',
        label: 'Samples',
        min: 4.0,
        max: 32.0,
        step: 1.0,
        defaultValue: 18.0,
      ),
      _floatParam(
        id: 'minIter',
        label: 'Min escape iterations',
        min: 1.0,
        max: 80.0,
        step: 1.0,
        defaultValue: 10.0,
      ),
    ],
  ),
  EscapeTimeConfig(
    id: 'buffalo2',
    name: 'Buffalo2',
    shaderAsset:
        'shaders/escape_time_family/families/buffalo/buffalo2_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
    category: 'Escape-Time',
  ),
  EscapeTimeConfig(
    id: 'buffalo_power7',
    name: 'Buffalo Power7',
    shaderAsset:
        'shaders/escape_time_family/families/buffalo/buffalo_power7_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
    category: 'Escape-Time',
  ),
  EscapeTimeConfig(
    id: 'burning_ship_power7',
    name: 'Burning Ship Power7',
    shaderAsset:
        'shaders/escape_time_family/families/burning_ship/parameter_plane/burning_ship_power7_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
    category: 'Escape-Time',
  ),
  EscapeTimeConfig(
    id: 'burning_ship_power7_julia',
    name: 'Burning Ship Power7 Julia',
    shaderAsset:
        'shaders/escape_time_family/families/burning_ship/julia_sets/burning_ship_power7_julia_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
    category: 'Escape-Time',
  ),
  EscapeTimeConfig(
    id: 'celtic2',
    name: 'Celtic2',
    shaderAsset: 'shaders/escape_time_family/families/celtic/celtic2_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
    category: 'Escape-Time',
  ),
  EscapeTimeConfig(
    id: 'celtic_power7',
    name: 'Celtic Power7',
    shaderAsset:
        'shaders/escape_time_family/families/celtic/celtic_power7_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
    category: 'Escape-Time',
  ),
  EscapeTimeConfig(
    id: 'chebyshev_fractal',
    name: 'Chebyshev Fractal',
    shaderAsset:
        'shaders/escape_time_family/newton_and_orthogonal/high_order_root_methods/chebyshev_fractal_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
    category: 'Escape-Time',
  ),
  EscapeTimeConfig(
    id: 'chebyshev_halley_param',
    name: 'Chebyshev Halley Param',
    shaderAsset: 'shaders/root_finding/chebyshev_halley_param_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
    category: 'Escape-Time',
  ),
  EscapeTimeConfig(
    id: 'cosecant_julia',
    name: 'Cosecant Julia',
    shaderAsset:
        'shaders/trigonometric_and_transcendental/elementary_trig/cosecant_julia_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
    category: 'Escape-Time',
  ),
  EscapeTimeConfig(
    id: 'cosecant_mandelbrot',
    name: 'Cosecant Mandelbrot',
    shaderAsset:
        'shaders/trigonometric_and_transcendental/elementary_trig/cosecant_mandelbrot_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
    category: 'Escape-Time',
  ),
  EscapeTimeConfig(
    id: 'cotangent_julia',
    name: 'Cotangent Julia',
    shaderAsset:
        'shaders/trigonometric_and_transcendental/elementary_trig/cotangent_julia_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
    category: 'Escape-Time',
  ),
  EscapeTimeConfig(
    id: 'cotangent_mandelbrot',
    name: 'Cotangent Mandelbrot',
    shaderAsset:
        'shaders/trigonometric_and_transcendental/elementary_trig/cotangent_mandelbrot_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
    category: 'Escape-Time',
  ),
  EscapeTimeConfig(
    id: 'dirichlet_eta',
    name: 'Dirichlet Eta',
    shaderAsset:
        'shaders/trigonometric_and_transcendental/special_functions/dirichlet_eta_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
    category: 'Escape-Time',
  ),
  EscapeTimeConfig(
    id: 'domain_coloring',
    name: 'Domain Coloring',
    shaderAsset:
        'shaders/escape_time_family/orbit_and_domain/domain_coloring_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
    category: 'Escape-Time',
  ),
  EscapeTimeConfig(
    id: 'exp_additive_mandelbrot',
    name: 'Exp Additive Mandelbrot',
    shaderAsset:
        'shaders/escape_time_family/mandelbrot_variants/iterative_maps/exp_additive_mandelbrot_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
    category: 'Escape-Time',
  ),
  EscapeTimeConfig(
    id: 'fractal_dream',
    name: 'Fractal Dream',
    shaderAsset:
        'shaders/escape_time_family/experimental_named/discrete_attractors/fractal_dream_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
    category: 'Escape-Time',
  ),
  EscapeTimeConfig(
    id: 'gray_scott_rd',
    name: 'Gray Scott Rd',
    shaderAsset: 'shaders/cellular_and_stochastic/gray_scott_rd_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
    category: 'Escape-Time',
  ),
  EscapeTimeConfig(
    id: 'implicit_affine_fractal_surface',
    name: 'Implicit Affine Fractal Surface',
    shaderAsset:
        'shaders/ifs_and_geometric/raymarched_3d/implicit_affine_fractal_surface_gpu.frag',
    defaultIterations: 12,
    defaultBailout: 4.0,
    category: '3D Fractals',
    extraParams: [
      _floatParam(
        id: 'epsilon',
        label: 'Epsilon',
        min: 0.0005,
        max: 0.02,
        step: 0.0005,
        defaultValue: 0.002,
      ),
    ],
  ),
  EscapeTimeConfig(
    id: 'hofstadter_butterfly',
    name: 'Hofstadter Butterfly',
    shaderAsset:
        'shaders/escape_time_family/geometry_and_ifs/hofstadter_butterfly_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
    category: 'Escape-Time',
  ),
  EscapeTimeConfig(
    id: 'inverse_quadratic',
    name: 'Inverse Quadratic',
    shaderAsset:
        'shaders/escape_time_family/polynomial_maps/inverse_quadratic_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
    category: 'Escape-Time',
  ),
  EscapeTimeConfig(
    id: 'jacobi_sn',
    name: 'Jacobi Sn',
    shaderAsset:
        'shaders/trigonometric_and_transcendental/special_functions/jacobi_sn_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
    category: 'Escape-Time',
    extraParams: [
      _floatParam(
        id: 'k',
        label: 'Modulus k',
        min: 0.0,
        max: 1.0,
        step: 0.01,
        defaultValue: 0.5,
      ),
    ],
  ),
  EscapeTimeConfig(
    id: 'jarratt',
    name: 'Jarratt',
    shaderAsset: 'shaders/root_finding/jarratt_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
    category: 'Escape-Time',
  ),
  EscapeTimeConfig(
    id: 'jason_rampe_1',
    name: 'Jason Rampe 1',
    shaderAsset:
        'shaders/escape_time_family/experimental_named/discrete_attractors/jason_rampe_1_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
    category: 'Escape-Time',
  ),
  EscapeTimeConfig(
    id: 'jason_rampe_2',
    name: 'Jason Rampe 2',
    shaderAsset:
        'shaders/escape_time_family/experimental_named/discrete_attractors/jason_rampe_2_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
    category: 'Escape-Time',
    extraParams: [
      FractalParameter(
        id: 'paramA',
        label: (_) => 'A',
        type: FractalParamType.float,
        min: -4.0,
        max: 4.0,
        step: 0.01,
        defaultValue: 2.1,
      ),
      FractalParameter(
        id: 'paramB',
        label: (_) => 'B',
        type: FractalParamType.float,
        min: -4.0,
        max: 4.0,
        step: 0.01,
        defaultValue: -2.3,
      ),
      FractalParameter(
        id: 'paramC',
        label: (_) => 'C',
        type: FractalParamType.float,
        min: -4.0,
        max: 4.0,
        step: 0.01,
        defaultValue: 0.8,
      ),
      FractalParameter(
        id: 'paramD',
        label: (_) => 'D',
        type: FractalParamType.float,
        min: -4.0,
        max: 4.0,
        step: 0.01,
        defaultValue: -0.7,
      ),
    ],
  ),
  EscapeTimeConfig(
    id: 'julia',
    name: 'Julia',
    shaderAsset: 'shaders/escape_time_family/core/julia_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
    category: 'Escape-Time',
  ),
  EscapeTimeConfig(
    id: 'king',
    name: 'King',
    shaderAsset:
        'shaders/escape_time_family/experimental_named/discrete_attractors/king_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
    category: 'Escape-Time',
  ),
  EscapeTimeConfig(
    id: 'kleinian_limit_set',
    name: 'Kleinian Limit Set',
    shaderAsset: 'shaders/ifs_and_geometric/kleinian_limit_set_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
    category: 'Escape-Time',
  ),
  EscapeTimeConfig(
    id: 'laguerre_fractal',
    name: 'Laguerre Fractal',
    shaderAsset:
        'shaders/escape_time_family/newton_and_orthogonal/high_order_root_methods/laguerre_fractal_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
    category: 'Escape-Time',
  ),
  EscapeTimeConfig(
    id: 'magnetic_pendulum',
    name: 'Magnetic Pendulum',
    shaderAsset:
        'shaders/escape_time_family/experimental_named/physical_simulation/magnetic_pendulum_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
    category: 'Escape-Time',
  ),
  EscapeTimeConfig(
    id: 'mandelbrot_df2',
    name: 'Mandelbrot Df2',
    shaderAsset: 'shaders/legacy/precision/mandelbrot_df2.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
    category: 'Escape-Time',
  ),
  EscapeTimeConfig(
    id: 'mandelbrot_et',
    name: 'Mandelbrot Et',
    shaderAsset: 'shaders/legacy/escape_time/mandelbrot_et.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
    category: 'Escape-Time',
  ),
  EscapeTimeConfig(
    id: 'mandelbrot_hardgrad',
    name: 'Mandelbrot Hardgrad',
    shaderAsset: 'shaders/legacy/diagnostics/mandelbrot_hardgrad.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
    category: 'Escape-Time',
  ),
  EscapeTimeConfig(
    id: 'mandelbrot_simple',
    name: 'Mandelbrot Simple',
    shaderAsset: 'shaders/legacy/diagnostics/mandelbrot_simple.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
    category: 'Escape-Time',
  ),
  EscapeTimeConfig(
    id: 'mandelbrot_tex',
    name: 'Mandelbrot Tex',
    shaderAsset: 'shaders/legacy/escape_time/mandelbrot_tex.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
    category: 'Escape-Time',
    usesPaletteSampler: true,
  ),
  EscapeTimeConfig(
    id: 'mandel_julia_dual',
    name: 'Mandel Julia Dual',
    shaderAsset: 'shaders/escape_time_family/core/mandel_julia_dual_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
    category: 'Escape-Time',
  ),
  EscapeTimeConfig(
    id: 'mandel_step_escape',
    name: 'Mandel Step Escape',
    shaderAsset: 'shaders/legacy/escape_time/mandel_step_escape.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
    category: 'Escape-Time',
  ),
  EscapeTimeConfig(
    id: 'mittag_leffler',
    name: 'Mittag Leffler',
    shaderAsset:
        'shaders/trigonometric_and_transcendental/special_functions/mittag_leffler_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
    category: 'Escape-Time',
  ),
  EscapeTimeConfig(
    id: 'muller',
    name: 'Muller',
    shaderAsset: 'shaders/root_finding/muller_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
    category: 'Escape-Time',
  ),
  EscapeTimeConfig(
    id: 'neta_order16',
    name: 'Neta Order16',
    shaderAsset: 'shaders/root_finding/neta_order16_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
    category: 'Escape-Time',
  ),
  EscapeTimeConfig(
    id: 'noor_newton',
    name: 'Noor Newton',
    shaderAsset: 'shaders/root_finding/noor_newton_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
    category: 'Escape-Time',
  ),
  EscapeTimeConfig(
    id: 'nova_degree5',
    name: 'Nova Degree5',
    shaderAsset:
        'shaders/escape_time_family/families/nova/parameter_plane/nova_degree5_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
    category: 'Escape-Time',
  ),
  EscapeTimeConfig(
    id: 'nova_degree5_julia',
    name: 'Nova Degree5 Julia',
    shaderAsset:
        'shaders/escape_time_family/families/nova/julia_sets/nova_degree5_julia_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
    category: 'Escape-Time',
  ),
  EscapeTimeConfig(
    id: 'nova',
    name: 'Nova',
    shaderAsset:
        'shaders/escape_time_family/families/nova/parameter_plane/nova_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
    category: 'Escape-Time',
  ),
  EscapeTimeConfig(
    id: 'nova_mandelbrot',
    name: 'Nova Mandelbrot',
    shaderAsset:
        'shaders/escape_time_family/families/nova/parameter_plane/nova_mandelbrot_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
    category: 'Escape-Time',
  ),
  EscapeTimeConfig(
    id: 'orbit_trap_cross',
    name: 'Orbit Trap Cross',
    shaderAsset:
        'shaders/escape_time_family/orbit_and_domain/orbit_trap_cross_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
    category: 'Escape-Time',
  ),
  EscapeTimeConfig(
    id: 'orbit_trap_point',
    name: 'Orbit Trap Point',
    shaderAsset:
        'shaders/escape_time_family/orbit_and_domain/orbit_trap_point_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
    category: 'Escape-Time',
  ),
  EscapeTimeConfig(
    id: 'orbit_trap_ring',
    name: 'Orbit Trap Ring',
    shaderAsset:
        'shaders/escape_time_family/orbit_and_domain/orbit_trap_ring_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
    category: 'Escape-Time',
  ),
  EscapeTimeConfig(
    id: 'ostrowski',
    name: 'Ostrowski',
    shaderAsset: 'shaders/root_finding/ostrowski_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
    category: 'Escape-Time',
  ),
  EscapeTimeConfig(
    id: 'phase_portrait',
    name: 'Phase Portrait',
    shaderAsset:
        'shaders/escape_time_family/orbit_and_domain/phase_portrait_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
    category: 'Escape-Time',
  ),
  EscapeTimeConfig(
    id: 'phoenix',
    name: 'Phoenix',
    shaderAsset: 'shaders/escape_time_family/core/phoenix_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
    category: 'Escape-Time',
  ),
  EscapeTimeConfig(
    id: 'picard_mann_newton',
    name: 'Picard Mann Newton',
    shaderAsset: 'shaders/root_finding/picard_mann_newton_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
    category: 'Escape-Time',
  ),
  EscapeTimeConfig(
    id: 'schroeder_z5',
    name: 'Schroeder Z5',
    shaderAsset: 'shaders/root_finding/schroeder_z5_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
    category: 'Escape-Time',
  ),
  EscapeTimeConfig(
    id: 'schroeder_z6',
    name: 'Schroeder Z6',
    shaderAsset: 'shaders/root_finding/schroeder_z6_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
    category: 'Escape-Time',
  ),
  EscapeTimeConfig(
    id: 'secant_julia',
    name: 'Secant Julia',
    shaderAsset:
        'shaders/trigonometric_and_transcendental/elementary_trig/secant_julia_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
    category: 'Escape-Time',
  ),
  EscapeTimeConfig(
    id: 'secant_mandelbrot',
    name: 'Secant Mandelbrot',
    shaderAsset:
        'shaders/trigonometric_and_transcendental/elementary_trig/secant_mandelbrot_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
    category: 'Escape-Time',
  ),
  EscapeTimeConfig(
    id: 'shape_modulus_julia',
    name: 'Shape Modulus Julia',
    shaderAsset:
        'shaders/escape_time_family/julia_variants/shape_modulus_julia_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
    category: 'Escape-Time',
  ),
  EscapeTimeConfig(
    id: 'sierpinski_julia_rational',
    name: 'Sierpinski Julia Rational',
    shaderAsset: 'shaders/ifs_and_geometric/sierpinski_julia_rational_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
    category: 'Escape-Time',
  ),
  EscapeTimeConfig(
    id: 'sprott_g',
    name: 'Sprott G',
    shaderAsset: 'shaders/strange_attractors/sprott_g_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
    category: 'Escape-Time',
  ),
  EscapeTimeConfig(
    id: 'sprott_h',
    name: 'Sprott H',
    shaderAsset: 'shaders/strange_attractors/sprott_h_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
    category: 'Escape-Time',
  ),
  EscapeTimeConfig(
    id: 'sprott_i',
    name: 'Sprott I',
    shaderAsset: 'shaders/strange_attractors/sprott_i_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
    category: 'Escape-Time',
  ),
  EscapeTimeConfig(
    id: 'sprott_k',
    name: 'Sprott K',
    shaderAsset: 'shaders/strange_attractors/sprott_k_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
    category: 'Escape-Time',
  ),
  EscapeTimeConfig(
    id: 'sprott_l',
    name: 'Sprott L',
    shaderAsset: 'shaders/strange_attractors/sprott_l_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
    category: 'Escape-Time',
  ),
  EscapeTimeConfig(
    id: 'sprott_m',
    name: 'Sprott M',
    shaderAsset: 'shaders/strange_attractors/sprott_m_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
    category: 'Escape-Time',
  ),
  EscapeTimeConfig(
    id: 'sprott_n',
    name: 'Sprott N',
    shaderAsset: 'shaders/strange_attractors/sprott_n_gpu.frag',
    defaultIterations: 133,
    defaultBailout: 4.9,
    defaultCenterX: -0.11033250391483307,
    defaultCenterY: -1.1267447471618652,
    defaultZoom: 0.2,
    category: 'Escape-Time',
  ),
  EscapeTimeConfig(
    id: 'sprott_o',
    name: 'Sprott O',
    shaderAsset: 'shaders/strange_attractors/sprott_o_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
    category: 'Escape-Time',
  ),
  EscapeTimeConfig(
    id: 'sprott_s',
    name: 'Sprott S',
    shaderAsset: 'shaders/strange_attractors/sprott_s_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
    category: 'Escape-Time',
  ),
  EscapeTimeConfig(
    id: 'steffensen',
    name: 'Steffensen',
    shaderAsset: 'shaders/root_finding/steffensen_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
    category: 'Escape-Time',
  ),
  EscapeTimeConfig(
    id: 'steffensen_order8',
    name: 'Steffensen Order8',
    shaderAsset: 'shaders/root_finding/steffensen_order8_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
    category: 'Escape-Time',
  ),
  EscapeTimeConfig(
    id: 'higher_order_root_basin_family',
    name: 'Higher-Order Root Basin Family',
    shaderAsset: 'shaders/root_finding/higher_order_root_basin_family_gpu.frag',
    defaultIterations: 80,
    defaultBailout: 64.0,
    category: 'Root-Finding',
    extraParams: [
      _floatParam(
        id: 'alpha',
        label: 'Alpha',
        min: 0,
        max: 2,
        step: 0.05,
        defaultValue: 0.5,
      ),
    ],
  ),
  EscapeTimeConfig(
    id: 'superexponential',
    name: 'Superexponential',
    shaderAsset:
        'shaders/trigonometric_and_transcendental/exponential_iteration/superexponential_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
    category: 'Escape-Time',
  ),
  EscapeTimeConfig(
    id: 'super_halley',
    name: 'Super Halley',
    shaderAsset: 'shaders/root_finding/super_halley_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
    category: 'Escape-Time',
  ),
  EscapeTimeConfig(
    id: 'symmetric_icon',
    name: 'Symmetric Icon',
    shaderAsset:
        'shaders/escape_time_family/geometry_and_ifs/symmetric_icon_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
    category: 'Escape-Time',
  ),
  EscapeTimeConfig(
    id: 'transcendental_sin',
    name: 'Transcendental Sin',
    shaderAsset:
        'shaders/trigonometric_and_transcendental/elementary_trig/transcendental_sin_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
    category: 'Escape-Time',
  ),
  EscapeTimeConfig(
    id: 'traub_ostrowski',
    name: 'Traub Ostrowski',
    shaderAsset: 'shaders/root_finding/traub_ostrowski_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
    category: 'Escape-Time',
  ),
  EscapeTimeConfig(
    id: 'weierstrass_elliptic',
    name: 'Weierstrass Elliptic',
    shaderAsset:
        'shaders/trigonometric_and_transcendental/special_functions/weierstrass_elliptic_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
    defaultCenterX: -0.311764705882353,
    defaultCenterY: 0.0039215686274509665,
    defaultZoom: 1.0876470588235294,
    category: 'Escape-Time',
  ),
  EscapeTimeConfig(
    id: 'weierstrass_function',
    name: 'Weierstrass Function',
    shaderAsset:
        'shaders/trigonometric_and_transcendental/special_functions/weierstrass_function_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
    category: 'Escape-Time',
    extraParams: [
      _floatParam(
        id: 'a',
        label: 'a',
        min: 0.01,
        max: 0.99,
        step: 0.01,
        defaultValue: 0.5,
      ),
      _floatParam(
        id: 'b',
        label: 'b',
        min: 2,
        max: 15,
        step: 1,
        defaultValue: 7.0,
      ),
    ],
  ),
  EscapeTimeConfig(
    id: 'quaternion_julia_3d',
    name: 'Quaternion Julia 3D',
    shaderAsset:
        'shaders/3d_and_hypercomplex/raymarched_volumes/quaternion_julia_3d_gpu.frag',
    defaultIterations: 150,
    defaultBailout: 4.0,
    defaultZoom: 0.6,
    category: '3D & Hypercomplex',
    extraParams: [
      FractalParameter(
        id: 'juliaCReal',
        label: (l10n) => l10n.paramJuliaCReal,
        type: FractalParamType.float,
        min: -1.5,
        max: 1.5,
        step: 0.01,
        defaultValue: -0.8,
      ),
      FractalParameter(
        id: 'juliaCImag',
        label: (l10n) => l10n.paramJuliaCImag,
        type: FractalParamType.float,
        min: -1.5,
        max: 1.5,
        step: 0.01,
        defaultValue: 0.156,
      ),
    ],
    extraPresets: [
      catalogPreset(
        id: 'quaternion-julia-3d-classic',
        moduleId: 'quaternion_julia_3d',
        name: 'Classic',
        params: {
          'iterations': 150,
          'bailout': 4.0,
          'colorScheme': 0,
          'juliaCReal': -0.8,
          'juliaCImag': 0.156
        },
        view: FractalViewState(
            pan: Vector2(0, 0), zoom: 0.6, rotation: Vector3.zero()),
      ),
      catalogPreset(
        id: 'quaternion-julia-3d-organic',
        moduleId: 'quaternion_julia_3d',
        name: 'Organic',
        params: {
          'iterations': 200,
          'bailout': 4.0,
          'colorScheme': 1,
          'juliaCReal': -0.4,
          'juliaCImag': 0.6
        },
        view: FractalViewState(
            pan: Vector2(0, 0), zoom: 0.8, rotation: Vector3.zero()),
      ),
    ],
  ),
  EscapeTimeConfig(
    id: 'dual_quaternion_julia',
    name: 'Dual Quaternion Julia',
    shaderAsset:
        'shaders/3d_and_hypercomplex/raymarched_volumes/dual_quaternion_julia_gpu.frag',
    defaultIterations: 150,
    defaultBailout: 4.0,
    defaultZoom: 0.6,
    category: '3D & Hypercomplex',
    extraParams: [
      FractalParameter(
        id: 'juliaCReal',
        label: (l10n) => l10n.paramJuliaCReal,
        type: FractalParamType.float,
        min: -1.5,
        max: 1.5,
        step: 0.01,
        defaultValue: -0.8,
      ),
      FractalParameter(
        id: 'juliaCImag',
        label: (l10n) => l10n.paramJuliaCImag,
        type: FractalParamType.float,
        min: -1.5,
        max: 1.5,
        step: 0.01,
        defaultValue: 0.156,
      ),
    ],
    extraPresets: [
      catalogPreset(
        id: 'dual-quaternion-julia-classic',
        moduleId: 'dual_quaternion_julia',
        name: 'Classic',
        params: {
          'iterations': 150,
          'bailout': 4.0,
          'colorScheme': 0,
          'juliaCReal': -0.8,
          'juliaCImag': 0.156
        },
        view: FractalViewState(
            pan: Vector2(0, 0), zoom: 0.6, rotation: Vector3.zero()),
      ),
    ],
  ),

  EscapeTimeConfig(
    id: 'newton_z3_nova',
    name: 'Newton z³ Nova',
    shaderAsset: 'shaders/root_finding/newton_z3_gpu.frag',
    defaultIterations: 80,
    defaultBailout: 8.0,
    defaultZoom: 0.7,
    category: 'Convergent & Root-Finding',
    extraParams: [
      FractalParameter(
        id: 'relaxation',
        label: (l10n) => 'Relaxation',
        type: FractalParamType.float,
        min: 0.1,
        max: 2.0,
        step: 0.05,
        defaultValue: 1.0,
      ),
    ],
    extraPresets: [
      catalogPreset(
        id: 'newton-z3-nova-classic',
        moduleId: 'newton_z3_nova',
        name: 'Classic',
        params: {
          'iterations': 80,
          'bailout': 8.0,
          'colorScheme': 0,
          'relaxation': 1.0
        },
        view: FractalViewState(
            pan: Vector2(0, 0), zoom: 0.7, rotation: Vector3.zero()),
      ),
      catalogPreset(
        id: 'newton-z3-nova-relaxed',
        moduleId: 'newton_z3_nova',
        name: 'Relaxed',
        params: {
          'iterations': 100,
          'bailout': 8.0,
          'colorScheme': 1,
          'relaxation': 1.5
        },
        view: FractalViewState(
            pan: Vector2(0, 0), zoom: 0.8, rotation: Vector3.zero()),
      ),
    ],
  ),

  EscapeTimeConfig(
    id: 'newton_z4_nova',
    name: 'Newton z⁴ Nova',
    shaderAsset: 'shaders/root_finding/newton_z4_gpu.frag',
    defaultIterations: 80,
    defaultBailout: 8.0,
    defaultZoom: 0.7,
    category: 'Convergent & Root-Finding',
    extraParams: [
      FractalParameter(
        id: 'relaxation',
        label: (l10n) => 'Relaxation',
        type: FractalParamType.float,
        min: 0.1,
        max: 2.0,
        step: 0.05,
        defaultValue: 1.0,
      ),
    ],
    extraPresets: [
      catalogPreset(
        id: 'newton-z4-nova-classic',
        moduleId: 'newton_z4_nova',
        name: 'Classic',
        params: {
          'iterations': 80,
          'bailout': 8.0,
          'colorScheme': 0,
          'relaxation': 1.0
        },
        view: FractalViewState(
            pan: Vector2(0, 0), zoom: 0.7, rotation: Vector3.zero()),
      ),
    ],
  ),

  EscapeTimeConfig(
    id: 'newton_z5_nova',
    name: 'Newton z⁵ Nova',
    shaderAsset: 'shaders/root_finding/newton_z5_gpu.frag',
    defaultIterations: 80,
    defaultBailout: 8.0,
    defaultZoom: 0.7,
    category: 'Convergent & Root-Finding',
    extraParams: [
      FractalParameter(
        id: 'relaxation',
        label: (l10n) => 'Relaxation',
        type: FractalParamType.float,
        min: 0.1,
        max: 2.0,
        step: 0.05,
        defaultValue: 1.0,
      ),
    ],
    extraPresets: [
      catalogPreset(
        id: 'newton-z5-nova-classic',
        moduleId: 'newton_z5_nova',
        name: 'Classic',
        params: {
          'iterations': 80,
          'bailout': 8.0,
          'colorScheme': 0,
          'relaxation': 1.0
        },
        view: FractalViewState(
            pan: Vector2(0, 0), zoom: 0.7, rotation: Vector3.zero()),
      ),
    ],
  ),

  EscapeTimeConfig(
    id: 'newton_z6_nova',
    name: 'Newton z⁶ Nova',
    shaderAsset: 'shaders/root_finding/newton_z6_gpu.frag',
    defaultIterations: 80,
    defaultBailout: 8.0,
    defaultZoom: 0.7,
    category: 'Convergent & Root-Finding',
    extraParams: [
      FractalParameter(
        id: 'relaxation',
        label: (l10n) => 'Relaxation',
        type: FractalParamType.float,
        min: 0.1,
        max: 2.0,
        step: 0.05,
        defaultValue: 1.0,
      ),
    ],
    extraPresets: [
      catalogPreset(
        id: 'newton-z6-nova-classic',
        moduleId: 'newton_z6_nova',
        name: 'Classic',
        params: {
          'iterations': 80,
          'bailout': 8.0,
          'colorScheme': 0,
          'relaxation': 1.0
        },
        view: FractalViewState(
            pan: Vector2(0, 0), zoom: 0.7, rotation: Vector3.zero()),
      ),
    ],
  ),

  EscapeTimeConfig(
    id: 'halley_nova',
    name: 'Halley Nova',
    shaderAsset: 'shaders/root_finding/halley_gpu.frag',
    defaultIterations: 80,
    defaultBailout: 8.0,
    defaultZoom: 0.7,
    category: 'Convergent & Root-Finding',
    extraParams: [
      FractalParameter(
        id: 'relaxation',
        label: (l10n) => 'Relaxation',
        type: FractalParamType.float,
        min: 0.1,
        max: 2.0,
        step: 0.05,
        defaultValue: 1.0,
      ),
    ],
    extraPresets: [
      catalogPreset(
        id: 'halley-nova-classic',
        moduleId: 'halley_nova',
        name: 'Classic',
        params: {
          'iterations': 80,
          'bailout': 8.0,
          'colorScheme': 0,
          'relaxation': 1.0
        },
        view: FractalViewState(
            pan: Vector2(0, 0), zoom: 0.7, rotation: Vector3.zero()),
      ),
    ],
  ),

  EscapeTimeConfig(
    id: 'schroeder_nova',
    name: 'Schröder Nova',
    shaderAsset: 'shaders/root_finding/schroeder_gpu.frag',
    defaultIterations: 80,
    defaultBailout: 8.0,
    defaultZoom: 0.7,
    category: 'Convergent & Root-Finding',
    extraParams: [
      FractalParameter(
        id: 'relaxation',
        label: (l10n) => 'Relaxation',
        type: FractalParamType.float,
        min: 0.1,
        max: 2.0,
        step: 0.05,
        defaultValue: 1.0,
      ),
    ],
    extraPresets: [
      catalogPreset(
        id: 'schroeder-nova-classic',
        moduleId: 'schroeder_nova',
        name: 'Classic',
        params: {
          'iterations': 80,
          'bailout': 8.0,
          'colorScheme': 0,
          'relaxation': 1.0
        },
        view: FractalViewState(
            pan: Vector2(0, 0), zoom: 0.7, rotation: Vector3.zero()),
      ),
    ],
  ),

  EscapeTimeConfig(
    id: 'householder_nova',
    name: 'Householder Nova',
    shaderAsset: 'shaders/root_finding/householder_gpu.frag',
    defaultIterations: 80,
    defaultBailout: 8.0,
    defaultZoom: 0.7,
    category: 'Convergent & Root-Finding',
    extraParams: [
      FractalParameter(
        id: 'relaxation',
        label: (l10n) => 'Relaxation',
        type: FractalParamType.float,
        min: 0.1,
        max: 2.0,
        step: 0.05,
        defaultValue: 1.0,
      ),
    ],
    extraPresets: [
      catalogPreset(
        id: 'householder-nova-classic',
        moduleId: 'householder_nova',
        name: 'Classic',
        params: {
          'iterations': 80,
          'bailout': 8.0,
          'colorScheme': 0,
          'relaxation': 1.0
        },
        view: FractalViewState(
            pan: Vector2(0, 0), zoom: 0.7, rotation: Vector3.zero()),
      ),
    ],
  ),
  EscapeTimeConfig(
    id: 'phoenix_julia',
    name: 'Phoenix Julia',
    shaderAsset: 'shaders/escape_time_family/core/phoenix_gpu.frag',
    defaultIterations: 180,
    defaultBailout: 4.0,
    category: 'Escape-Time',
    extraParams: [
      FractalParameter(
        id: 'juliaCReal',
        label: (l10n) => l10n.paramJuliaCReal,
        type: FractalParamType.float,
        min: -1.5,
        max: 1.5,
        step: 0.01,
        defaultValue: -0.8,
      ),
      FractalParameter(
        id: 'juliaCImag',
        label: (l10n) => l10n.paramJuliaCImag,
        type: FractalParamType.float,
        min: -1.5,
        max: 1.5,
        step: 0.01,
        defaultValue: 0.156,
      ),
    ],
    extraPresets: [
      catalogPreset(
        id: 'phoenix-julia-classic',
        moduleId: 'phoenix_julia',
        name: 'Classic',
        params: {
          'iterations': 180,
          'bailout': 4.0,
          'colorScheme': 0,
          'juliaCReal': -0.8,
          'juliaCImag': 0.156
        },
        view: FractalViewState(
            pan: Vector2(0, 0), zoom: 1.0, rotation: Vector3.zero()),
      ),
    ],
  ),
];
