// Batch export service (generated by OpenClaw)
import 'dart:io';
import 'dart:typed_data';
import 'package:flutter/foundation.dart' show kDebugMode, kIsWeb;
import 'package:flutter/material.dart';
import 'package:image/image.dart' as img;
import 'package:flutter_fractals/core/models/export_options.dart';
import 'package:flutter_fractals/core/models/fractal_preset.dart';
import 'package:flutter_fractals/core/services/export_service.dart';

class BatchExportItemResult {
  final FractalPreset preset;
  final File file;
  final int index;

  const BatchExportItemResult({
    required this.preset,
    required this.file,
    required this.index,
  });
}

class BatchExportResult {
  final Directory directory;
  final List<BatchExportItemResult> items;
  final File? contactSheet;

  const BatchExportResult({
    required this.directory,
    required this.items,
    this.contactSheet,
  });
}

class BatchExportPlanEntry {
  final FractalPreset preset;
  final int sourceIndex;
  final int exportIndex;

  const BatchExportPlanEntry({
    required this.preset,
    required this.sourceIndex,
    required this.exportIndex,
  });
}

class BatchExportPlan {
  final List<BatchExportPlanEntry> entries;

  const BatchExportPlan._(this.entries);

  int get total => entries.length;

  static BatchExportPlan forModule({
    required String moduleId,
    required List<FractalPreset> presets,
  }) {
    final entries = <BatchExportPlanEntry>[];
    for (var sourceIndex = 0; sourceIndex < presets.length; sourceIndex++) {
      final preset = presets[sourceIndex];
      if (preset.moduleId != moduleId) continue;
      entries.add(
        BatchExportPlanEntry(
          preset: preset,
          sourceIndex: sourceIndex,
          exportIndex: entries.length,
        ),
      );
    }
    return BatchExportPlan._(List.unmodifiable(entries));
  }
}

/// Clock contract for replayable batch export directory naming.
abstract class BatchExportClock {
  DateTime now();
}

class SystemBatchExportClock implements BatchExportClock {
  const SystemBatchExportClock();

  @override
  DateTime now() => DateTime.now();
}

/// Frame-pump contract for replayable batch export tests.
abstract class BatchExportFramePump {
  Future<void> waitForPresetRender();
}

class WidgetsBindingBatchExportFramePump implements BatchExportFramePump {
  const WidgetsBindingBatchExportFramePump();

  @override
  Future<void> waitForPresetRender() async {
    await WidgetsBinding.instance.endOfFrame;
    await WidgetsBinding.instance.endOfFrame;
  }
}

class BatchExportService {
  final ExportService _exportService;
  final BatchExportClock _clock;
  final BatchExportFramePump _framePump;

  const BatchExportService({
    ExportService exportService = const ExportService(),
    BatchExportClock clock = const SystemBatchExportClock(),
    BatchExportFramePump framePump = const WidgetsBindingBatchExportFramePump(),
  })  : _exportService = exportService,
        _clock = clock,
        _framePump = framePump;

  Future<BatchExportResult> exportPresets({
    required GlobalKey boundaryKey,
    required Future<void> Function(FractalPreset preset) applyPreset,
    required List<FractalPreset> presets,
    required ExportOptions options,
    required double screenWidth,
    required double screenHeight,
    required String moduleId,
    required String moduleDisplayName,
    required Map<String, Object> Function() currentParameters,
    required void Function(double overallProgress, String status)? onProgress,
    required void Function(BatchExportItemResult item)? onItemDone,
    required bool Function() isCancelled,
  }) async {
    if (kIsWeb) throw UnsupportedError('exportPresets is not supported on web');
    final directory = await _createBatchDirectory(moduleId: moduleId);
    final results = <BatchExportItemResult>[];
    final plan =
        BatchExportPlan.forModule(moduleId: moduleId, presets: presets);

    for (final entry in plan.entries) {
      if (isCancelled()) break;

      final preset = entry.preset;
      onProgress?.call(
        entry.exportIndex / plan.total,
        'Exporting ${entry.exportIndex + 1}/${plan.total}: ${preset.name}',
      );

      await applyPreset(preset);
      await _framePump.waitForPresetRender();

      final metadata = options.embedMetadata
          ? ExportMetadata(
              title: preset.name,
              description: 'Preset export from $moduleDisplayName',
              fractalType: moduleId,
              parameters: Map<String, Object>.from(currentParameters()),
              createdAt: DateTime.now(),
            )
          : null;

      final bytes = await _exportService.captureWithOptions(
        boundaryKey,
        options: options.copyWith(metadata: metadata),
        screenWidth: screenWidth,
        screenHeight: screenHeight,
      );

      final filename = _presetFilename(
        moduleId: moduleId,
        index: entry.exportIndex,
        presetName: preset.name,
        format: options.format,
      );
      final file = File('${directory.path}/$filename');
      await file.writeAsBytes(bytes, flush: true);

      final item = BatchExportItemResult(
        preset: preset,
        file: file,
        index: entry.exportIndex,
      );
      results.add(item);
      onItemDone?.call(item);
    }

    File? contactSheet;
    if (results.isNotEmpty && !isCancelled()) {
      onProgress?.call(0.95, 'Building contact sheet…');
      try {
        final pngBytes = await _buildContactSheet(
          results.map((e) => e.file).toList(),
          columns: 4,
          tileSize: 512,
          padding: 16,
        );
        final name = 'contact_sheet_${_safeSlug(moduleId)}.png';
        final out = File('${directory.path}/$name');
        await out.writeAsBytes(pngBytes, flush: true);
        contactSheet = out;
      } catch (e) {
        if (kDebugMode) debugPrint('[FF] silent catch: $e');
      }
    }

    onProgress?.call(1.0, 'Done');
    return BatchExportResult(
        directory: directory, items: results, contactSheet: contactSheet);
  }

  Future<Directory> _createBatchDirectory({required String moduleId}) async {
    final base = await _exportService.getExportDirectory();
    final ts = _clock.now();
    final stamp =
        '${ts.year.toString().padLeft(4, '0')}${ts.month.toString().padLeft(2, '0')}${ts.day.toString().padLeft(2, '0')}_${ts.hour.toString().padLeft(2, '0')}${ts.minute.toString().padLeft(2, '0')}${ts.second.toString().padLeft(2, '0')}';
    final prefix = '${base.path}/batch_${_safeSlug(moduleId)}_$stamp';

    for (var attempt = 1;; attempt++) {
      final suffix =
          attempt == 1 ? '' : '_${attempt.toString().padLeft(2, '0')}';
      final dir = Directory('$prefix$suffix');
      if (await dir.exists()) continue;
      await dir.create(recursive: true);
      return dir;
    }
  }

  String _presetFilename({
    required String moduleId,
    required int index,
    required String presetName,
    required ExportFormat format,
  }) {
    final idx = (index + 1).toString().padLeft(3, '0');
    final slug = _safeSlug(presetName);
    return '${_safeSlug(moduleId)}_${idx}_$slug.${format.extension}';
  }

  String _safeSlug(String input) {
    final trimmed = input.trim().toLowerCase();
    final replaced = trimmed
        .replaceAll(RegExp(r'[^a-z0-9]+'), '_')
        .replaceAll(RegExp(r'_+'), '_')
        .replaceAll(RegExp(r'^_'), '')
        .replaceAll(RegExp(r'_$'), '');
    return replaced.isEmpty ? 'untitled' : replaced;
  }

  Future<Uint8List> _buildContactSheet(
    List<File> files, {
    required int columns,
    required int tileSize,
    required int padding,
  }) async {
    final thumbs = <img.Image>[];
    for (final f in files) {
      final bytes = await f.readAsBytes();
      final decoded = img.decodeImage(bytes);
      if (decoded == null) continue;
      thumbs.add(img.copyResize(decoded,
          width: tileSize,
          height: tileSize,
          interpolation: img.Interpolation.cubic));
    }
    if (thumbs.isEmpty) throw StateError('No images');

    final cols = columns.clamp(1, 12);
    final rows = ((thumbs.length + cols - 1) / cols).floor();
    final width = padding + cols * (tileSize + padding);
    final height = padding + rows * (tileSize + padding);

    final sheet = img.Image(width: width, height: height, numChannels: 4);
    img.fill(sheet, color: img.ColorRgba8(12, 12, 12, 255));

    for (var i = 0; i < thumbs.length; i++) {
      final r = i ~/ cols;
      final c = i % cols;
      final x = padding + c * (tileSize + padding);
      final y = padding + r * (tileSize + padding);
      img.compositeImage(sheet, thumbs[i], dstX: x, dstY: y);
    }

    return Uint8List.fromList(img.encodePng(sheet, level: 6));
  }
}
