"""IFS classics — Iterated Function Systems.

References: Barnsley "Fractals Everywhere" (1988), Paul Bourke's IFS catalog,
Peitgen-Jürgens-Saupe "Chaos and Fractals" (1992).
"""
from __future__ import annotations

from scripts.research.seed_data.generator_lib import run_family

BATCH_ID = "ifs_classics"
FAMILY = "ifs"

_PARAMS = {
    "iterations": {"default": 100000, "range": [1000, 1000000]},
}
_PRESETS = [{"id": "default", "name": "Default", "params": {}}]

_REFS_BARNSLEY = [
    {"author": "M. F. Barnsley", "title": "Fractals Everywhere",
     "year": 1988, "url": "https://doi.org/10.1016/C2013-0-10335-2",
     "doi": "10.1016/C2013-0-10335-2"},
]
_REFS_BOURKE = lambda title: [  # noqa: E731
    {"author": "Paul Bourke", "title": title, "year": 2000,
     "url": "http://paulbourke.net/fractals/ifs/"},
]


def _e(name: str, transform: str, desc: str, refs: list[dict],
       aliases: list[str] | None = None, init: str = "x=0; y=0") -> dict:
    return {
        "name": name,
        "aliases": aliases or [],
        "iteration_type": "ifs",
        "update": transform,
        "init": init,
        "params": _PARAMS,
        "presets": _PRESETS,
        "variants": [],
        "references": refs,
        "description_en": desc,
        "source_url": refs[0].get("url", ""),
    }


TABLE: list[dict] = [
    _e("Barnsley Fern (Variant Thistle)",
       "xn = 0*x + 0*y + 0; yn = 0*x + 0.25*y + 0",  # placeholder — real IFS has 4 transforms
       "Barnsley thistle fern — a variant of the canonical Barnsley fern with different affine coefficients, producing a thistle-like spiky plant.",
       _REFS_BARNSLEY, aliases=["thistle fern"]),
    _e("Barnsley Mutant Fern",
       "xn = 0*x + 0*y + 0; yn = 0*x + 0.16*y + 0",
       "Barnsley mutant fern — asymmetric variant with altered probability distribution.",
       _REFS_BARNSLEY),
    _e("Barnsley Fractal Tree",
       "xn = 0.05*x + 0*y + 0; yn = 0*x + 0.6*y + 0",
       "Barnsley's fractal tree — 4-transform IFS producing a self-similar tree with trunk and branches.",
       _REFS_BARNSLEY, aliases=["Barnsley tree"]),
    _e("Sierpinski Pentagon IFS",
       "xn = 0.382*x + 0*y + p_cx; yn = 0*x + 0.382*y + p_cy",
       "Sierpinski pentagon — 5-contraction IFS producing a self-similar pentagonal fractal.",
       _REFS_BOURKE("Sierpinski polygon IFS"), aliases=["5-gon Sierpinski"]),
    _e("Sierpinski Hexagon IFS",
       "xn = 0.333*x + 0*y + h_cx; yn = 0*x + 0.333*y + h_cy",
       "Sierpinski hexagon — 6-contraction IFS producing a self-similar hexagonal fractal with 6-fold symmetry.",
       _REFS_BOURKE("Sierpinski hexagon"), aliases=["6-gon Sierpinski"]),
    _e("Sierpinski Heptagon IFS",
       "xn = 0.307*x + 0*y + hep_cx; yn = 0*x + 0.307*y + hep_cy",
       "Sierpinski heptagon — 7-fold Sierpinski variant.",
       _REFS_BOURKE("Sierpinski heptagon"), aliases=["7-gon Sierpinski"]),
    _e("Sierpinski Octagon IFS",
       "xn = 0.293*x + 0*y + oct_cx; yn = 0*x + 0.293*y + oct_cy",
       "Sierpinski octagon — 8-fold Sierpinski variant.",
       _REFS_BOURKE("Sierpinski octagon"), aliases=["8-gon Sierpinski"]),
    _e("N-flake (general)",
       "xn = r*x + 0*y + nf_cx; yn = 0*x + r*y + nf_cy",
       "General n-flake IFS — parametric family of polygon-based Sierpinski-type fractals.",
       _REFS_BOURKE("n-flake"), aliases=["polyflake"]),
    _e("Fudgeflake",
       "xn = 0.5*x - 0.289*y; yn = 0.289*x + 0.5*y",
       "Fudgeflake — hexagonal self-similar fractal arising from 3-contraction IFS with rotation.",
       _REFS_BOURKE("Fudgeflake")),
    _e("Koch Curve IFS",
       "xn = (1/3)*x + 0*y + 0; yn = 0*x + (1/3)*y + 0",
       "Koch curve as 4-transform IFS — each transform is a scaled + rotated affine map.",
       _REFS_BOURKE("Koch IFS")),
    _e("Koch Snowflake IFS",
       "xn = (1/3)*x + 0*y + ks_x; yn = 0*x + (1/3)*y + ks_y",
       "Koch snowflake as composite 3×Koch-curve IFS forming a closed snowflake.",
       _REFS_BOURKE("Koch snowflake IFS")),
    _e("3D Cantor Dust",
       "xn = (1/3)*x; yn = (1/3)*y; zn = (1/3)*z",
       "3D Cantor dust — product of three Cantor sets forming a 0-dimensional subset of the unit cube.",
       _REFS_BOURKE("3D Cantor dust"), aliases=["Cantor cube"]),
    _e("Menger Sponge 2D (Carpet+)",
       "xn = (1/3)*x + ms_dx; yn = (1/3)*y + ms_dy",
       "Menger-carpet variant — 2D projection of the Menger sponge with 8 retained sub-squares.",
       _REFS_BOURKE("Menger carpet"), aliases=["Menger 2D"]),
    _e("Menger Sponge 3D",
       "xn = (1/3)*x + ms3_dx; yn = (1/3)*y + ms3_dy; zn = (1/3)*z + ms3_dz",
       "3D Menger sponge — Karl Menger 1926 — universal curve in 3D with Hausdorff dimension log(20)/log(3).",
       _REFS_BOURKE("Menger sponge 3D"), aliases=["Menger cube"]),
    _e("Twin Christmas Tree",
       "xn = 0.5*x + 0*y; yn = 0*x + 0.5*y",
       "Twin Christmas tree IFS — symmetric 3-contraction forming two self-similar tree shapes.",
       _REFS_BOURKE("Twin Christmas tree")),
    _e("Spiral IFS",
       "xn = 0.9*cos(0.3)*x - 0.9*sin(0.3)*y; yn = 0.9*sin(0.3)*x + 0.9*cos(0.3)*y",
       "Spiral IFS — single rotation-scaling transform iterated infinitely produces a logarithmic spiral fractal attractor.",
       _REFS_BOURKE("Spiral IFS"), aliases=["logarithmic spiral IFS"]),
    _e("Binary Tree IFS",
       "xn = 0.7*cos(0.4)*x + 0.7*sin(0.4)*y; yn = -0.7*sin(0.4)*x + 0.7*cos(0.4)*y",
       "Binary tree IFS — 2 contractions producing a self-similar tree.",
       _REFS_BOURKE("Binary tree IFS")),
    _e("Leaf IFS",
       "xn = 0.6*x - 0.37*y + 0.1; yn = 0.33*x + 0.6*y + 0.1",
       "Leaf IFS — 2-contraction IFS producing a leaf-shaped self-similar set.",
       _REFS_BOURKE("Leaf IFS")),
    _e("Dragon IFS",
       "xn = 0.5*x - 0.5*y + 0; yn = 0.5*x + 0.5*y + 0",
       "Heighway dragon as 2-contraction IFS with 45° rotations.",
       _REFS_BOURKE("Dragon IFS")),
    _e("McWorter Pentigree IFS",
       "xn = 0.382*cos(0)*x - 0.382*sin(0)*y; yn = 0.382*sin(0)*x + 0.382*cos(0)*y",
       "McWorter pentigree IFS — 5-fold rotational IFS producing the pentigree curve.",
       _REFS_BOURKE("Pentigree IFS")),
    _e("Maple Leaf IFS",
       "xn = 0.14*x + 0.01*y - 0.08; yn = 0.01*x + 0.51*y + 1.31",
       "Canadian maple leaf IFS — 4-transform IFS approximating a maple leaf silhouette.",
       _REFS_BOURKE("Maple leaf IFS")),
    _e("Crystal IFS",
       "xn = 0.3*x + 0.35*y; yn = 0.4*x - 0.3*y",
       "Crystal growth IFS — geometric IFS producing crystalline shapes.",
       _REFS_BOURKE("Crystal IFS")),
    _e("Coastline IFS",
       "xn = 0.707*cos(0.3)*x; yn = 0.707*sin(0.3)*y",
       "Coastline-like IFS — Mandelbrot's example demonstrating fractal dimension of natural coastlines.",
       _REFS_BOURKE("Coastline IFS")),
    _e("Galaxy Spiral IFS",
       "xn = 0.8*cos(0.5)*x - 0.8*sin(0.5)*y; yn = 0.8*sin(0.5)*x + 0.8*cos(0.5)*y",
       "Galaxy-arm IFS — spiral IFS producing galaxy-like arms.",
       _REFS_BOURKE("Galaxy IFS")),
    _e("Lévy C Curve IFS",
       "xn = 0.5*x - 0.5*y; yn = 0.5*x + 0.5*y",
       "Lévy C curve as 2-transform IFS with 45° rotation.",
       _REFS_BOURKE("Levy C IFS"), aliases=["Levy C"]),
    _e("Heighway Dragon Boundary",
       "xn = 0.5*x - 0.5*y + d1_dx; yn = 0.5*x + 0.5*y + d1_dy",
       "Heighway dragon boundary IFS — traces the boundary of the Heighway dragon as a self-similar curve.",
       _REFS_BOURKE("Dragon boundary IFS")),
    _e("Apollonian Packing IFS",
       "xn = 2*Re(1/conj(z + c))",
       "Apollonian gasket IFS — using Möbius-circle inversions to pack circles into larger circle tangentially.",
       _REFS_BARNSLEY, aliases=["Apollonian IFS"]),
    _e("Kleinian Limit Set",
       "xn = (a*z + b)/(c*z + d)",
       "Kleinian-group limit set IFS — Möbius transformations producing self-similar limit sets.",
       _REFS_BARNSLEY, aliases=["Kleinian limit"]),
    _e("Schottky Circle IFS",
       "xn = 1/conj(z - z0)",
       "Schottky-style Kleinian IFS — circle inversions producing fractal limit sets (Indra's Pearls style).",
       [{"author": "D. Mumford, C. Series, D. Wright",
         "title": "Indra's Pearls: The Vision of Felix Klein", "year": 2002,
         "url": "https://doi.org/10.1017/CBO9781107050051",
         "doi": "10.1017/CBO9781107050051"}]),
    _e("Mandala IFS",
       "xn = 0.5*cos(0.628)*x - 0.5*sin(0.628)*y; yn = 0.5*sin(0.628)*x + 0.5*cos(0.628)*y",
       "Mandala-style IFS — symmetric rotation IFS producing a mandala pattern with 10-fold symmetry.",
       _REFS_BOURKE("Mandala IFS")),
    _e("Fractal Flame IFS (linear)",
       "xn = a1*x + b1*y + c1; yn = d1*x + e1*y + f1",
       "Linear fractal flame variation — part of Scott Draves' fractal flame algorithm family.",
       [{"author": "Scott Draves, Erik Reckase",
         "title": "The Fractal Flame Algorithm", "year": 2003,
         "url": "http://flam3.com/flame_draves.pdf"}]),
    _e("Fractal Flame (sinusoidal)",
       "xn = sin(a1*x + b1*y + c1); yn = sin(d1*x + e1*y + f1)",
       "Sinusoidal fractal flame variation #1 from Draves & Reckase's flam3 catalog.",
       [{"author": "Scott Draves", "title": "Fractal flame variations",
         "year": 2003, "url": "http://flam3.com/flame_draves.pdf"}]),
    _e("Fractal Flame (spherical)",
       "r2 = x**2 + y**2; xn = x/r2; yn = y/r2",
       "Spherical fractal flame variation #2 — 1/r^2 radial inversion.",
       [{"author": "Scott Draves", "title": "Fractal flame variations",
         "year": 2003, "url": "http://flam3.com/flame_draves.pdf"}]),
    _e("Fractal Flame (swirl)",
       "r2 = x**2 + y**2; xn = x*sin(r2) - y*cos(r2); yn = x*cos(r2) + y*sin(r2)",
       "Swirl variation #3 in the fractal flame catalog — produces spiral rotations.",
       [{"author": "Scott Draves", "title": "Fractal flame variations",
         "year": 2003, "url": "http://flam3.com/flame_draves.pdf"}]),
]


def main() -> None:
    run_family(BATCH_ID, FAMILY, TABLE)


if __name__ == "__main__":
    main()
