"""Named Julia c-values: each distinct c produces a distinct Julia set.

Sources:
  - Wikipedia "Julia set", Robert Munafo's Mu-Ency (mrob.com/pub/muency/julia.html),
    Paul Bourke, Peitgen-Richter catalog.
"""
from __future__ import annotations

from scripts.research.seed_data.generator_lib import run_family

BATCH_ID = "julia_c_values"
FAMILY = "julia_c"

_PARAMS = {
    "iterations": {"default": 500, "range": [10, 5000]},
    "bailout": {"default": 4.0, "range": [2.0, 1024.0]},
    "power": {"default": 2.0, "range": [2.0, 8.0]},
}
_REFS_JULIA = [
    {"author": "Wikipedia", "title": "Julia set", "year": 2024,
     "url": "https://en.wikipedia.org/wiki/Julia_set"},
    {"author": "Robert Munafo", "title": "Mu-Ency: Julia set catalog",
     "year": 2023, "url": "https://mrob.com/pub/muency/julia.html"},
]
_REFS_DOUADY = [
    {"author": "A. Douady, J. H. Hubbard",
     "title": "Étude dynamique des polynômes complexes",
     "year": 1984, "url": "https://www.math.cornell.edu/~hubbard/OrsayFrench.pdf"},
]


# (name, c_real, c_imag, description_snippet, aliases, [optional refs override])
JULIA_C = [
    ("Douady's Rabbit", -0.123, 0.745,
     "The classic 'Douady rabbit' Julia set c ≈ -0.123 + 0.745i — a c-value in the period-3 bulb of the Mandelbrot set, producing three self-similar 'ears'.",
     ["Rabbit Julia", "period-3 rabbit"], _REFS_DOUADY),
    ("Dendrite Julia", 0.0, 1.0,
     "Dendrite Julia set c = i — a tree-like fractal without interior (fully disconnected Fatou set).",
     ["dendrite", "c=i Julia"], None),
    ("Airplane Julia", -1.7548776662, 0.0,
     "Airplane Julia set at c ≈ -1.7548776662 (real root of z^3 + 2z^2 + 2z + 2 = 0) — superattracting period-3 cycle with aeroplane-like silhouette.",
     ["airplane"], None),
    ("Seahorse Valley Julia", -0.75, 0.1,
     "Julia set c = -0.75 + 0.1i near the seahorse valley — produces elongated spiral tail structures.",
     ["seahorse"], None),
    ("Basilica Julia", -1.0, 0.0,
     "Basilica Julia set c = -1 — superattracting period-2 cycle; resembles two touching cardioids.",
     ["basilica", "c=-1 Julia"], None),
    ("San Marco Julia", -0.75, 0.0,
     "San Marco Julia set c = -0.75 — parabolic parameter on the boundary between main cardioid and period-2 bulb.",
     ["San Marco", "parabolic Julia"], None),
    ("Kaleidoscope Julia", -0.4, 0.6,
     "Julia set c = -0.4 + 0.6i — kaleidoscopic multi-spiral structure popular in fractal art.",
     [], None),
    ("Cactus Julia", 0.285, 0.0,
     "Cactus Julia set c = 0.285 — cactus-like branched fractal near the cusp of the main cardioid.",
     ["cactus"], None),
    ("Fatou Dust Julia", 0.4, 0.4,
     "Julia set c = 0.4 + 0.4i — totally disconnected 'Fatou dust' Cantor-set-like structure.",
     ["Fatou dust", "Cantor dust Julia"], None),
    ("Siegel Disk Julia", -0.391, -0.587,
     "Julia set c ≈ -0.391 - 0.587i corresponding to a Siegel disk parameter — the Fatou component contains an irrationally neutral fixed point.",
     ["Siegel Julia"], None),
    ("Galaxy Julia", 0.285, 0.01,
     "Galaxy Julia c = 0.285 + 0.01i — slight imaginary perturbation of cactus produces a spiral galaxy texture.",
     ["galaxy spiral"], None),
    ("Dragon Julia", -0.8, 0.156,
     "Dragon Julia c = -0.8 + 0.156i — dragon-shaped curve with recursive spiraling arms.",
     ["dragon Julia"], None),
    ("Period-3 Julia", -0.12, 0.74,
     "Period-3 bulb Julia — classical parameter in the northern period-3 bulb of the Mandelbrot set.",
     ["period 3"], None),
    ("Period-4 Julia", 0.27334, 0.00742,
     "Period-4 Julia set at c ≈ 0.27334 + 0.00742i — superattracting period-4 cycle.",
     ["period 4"], None),
    ("Period-5 Julia", -0.5046, 0.5631,
     "Period-5 Julia — superattracting period-5 cycle in the northern bulb.",
     ["period 5"], None),
    ("Period-6 Julia", -1.3107, 0.0,
     "Period-6 Julia — superattracting period-6 cycle on the real axis of the Mandelbrot set.",
     ["period 6"], None),
    ("Period-7 Julia", 0.4388, 0.3499,
     "Period-7 Julia — superattracting period-7 parameter.",
     ["period 7"], None),
    ("Rabbit Baby", -0.122, 0.739,
     "Julia c = -0.122 + 0.739i — 'baby rabbit' slightly off Douady's value.",
     ["baby rabbit"], None),
    ("Rabbit (classic)", -0.7, 0.27015,
     "Julia c = -0.7 + 0.27015i — the classic 'rabbit' used in countless textbook illustrations.",
     ["classic rabbit"], None),
    ("Swirl Julia", -0.54, 0.54,
     "Julia c = -0.54 + 0.54i — swirling multi-armed structure.",
     ["swirl"], None),
    ("Lightning Julia", -0.7269, 0.1889,
     "Julia c = -0.7269 + 0.1889i — lightning-bolt filament pattern.",
     ["lightning"], None),
    ("Filigree Julia", 0.355, 0.355,
     "Julia c = 0.355 + 0.355i — delicate filigree of connecting filaments.",
     ["filigree"], None),
    ("Spiral Julia", -0.75, 0.11,
     "Spiral Julia c = -0.75 + 0.11i — slow spiral near seahorse valley.",
     ["spiral"], None),
    ("Unit Circle", 0.0, 0.0,
     "Julia set for c = 0: the iteration z → z^2 has the unit circle as its Julia set — the simplest non-trivial Julia set.",
     ["unit circle Julia"], None),
    ("Chebyshev Julia", 2.0, 0.0,
     "Julia set c = 2 — iteration corresponds to a Chebyshev polynomial and the Julia set is the real interval [-2, 2].",
     ["real interval Julia"], None),
    ("Cauliflower Bulb Julia", -1.25, 0.0,
     "Julia c = -1.25 — inside the period-2 cauliflower bulb.",
     ["cauliflower"], None),
    ("Misiurewicz M_{2,1}", -2.0, 0.0,
     "Misiurewicz parameter c=-2 (pre-periodic): Julia set is the real interval [-2, 2] with a specific pre-periodic critical orbit.",
     ["Misiurewicz -2"], None),
    ("Misiurewicz M_{3,1}", -1.5436890126921, 0.0,
     "Misiurewicz parameter — real-valued pre-periodic c where the critical orbit lands on a periodic cycle after 3 iterations.",
     ["Misiurewicz"], None),
    ("Feigenbaum Point", -1.401155, 0.0,
     "Feigenbaum accumulation point c ≈ -1.401155 — onset of chaos in the real logistic family; Julia set at this point is a Cantor-like self-similar attractor.",
     ["Feigenbaum"], None),
    ("Western Rabbit", -0.15, 0.65,
     "Julia c = -0.15 + 0.65i — 'western' variant of the rabbit.",
     [], None),
    ("Eastern Rabbit", -0.25, 0.75,
     "Julia c = -0.25 + 0.75i — 'eastern' rabbit with tighter spirals.",
     [], None),
    ("Mini-Brot Julia", 0.3, 0.5,
     "Julia c = 0.3 + 0.5i — located near a Mandelbrot mini-copy.",
     [], None),
    ("Elephant Valley Julia", 0.25, 0.0,
     "Julia c = 0.25 — parabolic parameter at the cusp of the main cardioid; boundary of Mandelbrot set.",
     ["elephant valley"], None),
    ("Near-Elephant Julia", 0.251, 0.0001,
     "Julia just inside elephant valley — filamented structure near the Mandelbrot cusp.",
     [], None),
    ("Dendritic Tree Julia", -0.8, 0.2,
     "Julia c = -0.8 + 0.2i — dendritic tree fractal.",
     ["dendritic tree"], None),
    ("Mink Julia", -0.12, -0.77,
     "Julia c = -0.12 - 0.77i — 'mink' furry asymmetric structure.",
     ["mink"], None),
    ("Star Julia", -0.835, -0.2321,
     "Julia c = -0.835 - 0.2321i — five-pointed star-like structure.",
     ["star"], None),
    ("Misiurewicz M_{4,1}", -0.1011, 0.9563,
     "Misiurewicz parameter M(4,1) — pre-periodic with period 1 after 4 pre-iterations.",
     ["Misiurewicz 4,1"], None),
    ("Jumping Jack Julia", 0.285, -0.01,
     "Julia c = 0.285 - 0.01i — 'jumping jack' stretched symmetric form.",
     [], None),
    ("Twin Spiral Julia", -0.74543, 0.11301,
     "Julia c = -0.74543 + 0.11301i — deep double-spiral zoomed Julia.",
     ["twin spiral"], None),
    ("Hyperbolic Julia", -0.1, 0.75,
     "Hyperbolic Julia c = -0.1 + 0.75i — fully hyperbolic parameter with simply-connected Fatou components.",
     ["hyperbolic"], None),
    ("Critical Period-3", -0.7545, 0.1182,
     "Julia c = -0.7545 + 0.1182i — critical parameter on the period-3 bulb boundary.",
     [], None),
    ("Centrally Symmetric Julia", -0.8, 0.0,
     "Julia c = -0.8 — real parameter in the period-2 bulb producing bilateral symmetry.",
     ["symmetric"], None),
    ("Thistle Julia", -0.1015352, 0.6333312,
     "Julia c = -0.1015352 + 0.6333312i — thistle-like spiky structure.",
     ["thistle"], None),
    ("Zig-Zag Julia", -0.39054, -0.58679,
     "Julia c = -0.39054 - 0.58679i — zig-zag connected structure.",
     [], None),
    ("Spider Julia", -0.235125, 0.827215,
     "Julia c = -0.235125 + 0.827215i — spider-leg filament structure.",
     ["spider"], None),
    ("Flower Julia", 0.38, 0.295,
     "Julia c = 0.38 + 0.295i — flower-petal structure.",
     ["flower"], None),
    ("Medusa Julia", 0.25, 0.52,
     "Julia c = 0.25 + 0.52i — 'medusa' entangled strands.",
     ["medusa"], None),
    ("Broccoli Julia", -0.158, 1.033,
     "Julia c = -0.158 + 1.033i — broccoli-like branched structure.",
     ["broccoli"], None),
    ("Spring Julia", -1.04, 0.27,
     "Julia c = -1.04 + 0.27i — coiled spring structure.",
     [], None),
    ("Maze Julia", 0.37, 0.10,
     "Julia c = 0.37 + 0.10i — maze-like connected structure.",
     ["maze"], None),
    ("Gossamer Julia", -0.162, 1.04,
     "Julia c = -0.162 + 1.04i — delicate gossamer filaments.",
     ["gossamer"], None),
    ("Sparse Dust Julia", 0.6, 0.3,
     "Julia c = 0.6 + 0.3i — sparse Cantor-dust Julia outside Mandelbrot set.",
     [], None),
    ("Period-8 Julia", -1.3761, 0.0,
     "Period-8 Julia — superattracting period-8 real parameter.",
     ["period 8"], None),
    ("Period-9 Julia", -1.3811, 0.0,
     "Period-9 Julia — superattracting period-9 real parameter.",
     ["period 9"], None),
    ("Near-Boundary Julia", -0.7, 0.3,
     "Julia c = -0.7 + 0.3i — near the boundary of the main cardioid.",
     [], None),
    ("Grainy Julia", -1.476, 0.0,
     "Julia c = -1.476 — real parameter producing dendrite-like fine grain.",
     [], None),
    ("Flying Bird Julia", -0.36, 0.1,
     "Julia c = -0.36 + 0.1i — resembles a bird in flight.",
     ["flying bird"], None),
    ("Infinity Julia", -1.9, 0.00001,
     "Julia c = -1.9 + 0.00001i — near real boundary; produces infinity-sign loops.",
     [], None),
    ("Northern Light Julia", -0.2209, 0.7448,
     "Julia c = -0.2209 + 0.7448i — aurora-like flowing strands.",
     ["aurora"], None),
    ("Lacework Julia", 0.3, -0.5,
     "Julia c = 0.3 - 0.5i — intricate lacework of filaments.",
     ["lacework"], None),
]


def _entry(name: str, cr: float, ci: float, desc: str, aliases: list[str] | None,
           refs_override) -> dict:
    refs = refs_override or _REFS_JULIA
    # Build update so literal c distinguishes each hash
    sign = "+" if ci >= 0 else "-"
    update = f"z = z**2 + ({cr} {sign} {abs(ci)}*I)"
    init = "z = z0"
    return {
        "name": name,
        "aliases": (aliases or []) + [f"c={cr}{sign}{abs(ci)}i"],
        "iteration_type": "escape_time",
        "update": update,
        "init": init,
        "params": _PARAMS,
        "presets": [{"id": "default", "name": "Default view", "params": {}}],
        "variants": [],
        "references": refs,
        "description_en": desc,
        "source_url": refs[0].get("url", ""),
    }


TABLE: list[dict] = []
for name, cr, ci, desc, aliases, refs_o in JULIA_C:
    TABLE.append(_entry(name, cr, ci, desc, aliases, refs_o))


def main() -> None:
    run_family(BATCH_ID, FAMILY, TABLE)


if __name__ == "__main__":
    main()
