"""Extended L-systems: space-filling curves, plant generators, fractal trees (Family 5).

Sources:
  - P. Prusinkiewicz, A. Lindenmayer, "The Algorithmic Beauty of Plants" (1990).
  - W. McKenna, "Fractal curves" (1985).
  - W. Gosper / R. W. Gosper, "Exploring the Gosper curve" (1976).
  - Paul Bourke L-system catalog.
  - Thue-Morse / Fibonacci-word L-system constructions (Monnerot-Dumaine 2009).
"""
from __future__ import annotations

from scripts.research.seed_data.generator_lib import run_family

BATCH_ID = "space_filling_curves_extended"
FAMILY = "lsystem_ext"

_PARAMS = {
    "depth": {"default": 4, "range": [1, 12]},
    "angle": {"default": 90.0, "range": [1.0, 180.0]},
    "step_length": {"default": 4.0, "range": [0.1, 50.0]},
}
_PRESETS = [{"id": "default", "name": "Default depth", "params": {}}]


def _e(name: str, axiom: str, rule: str, angle: float, desc: str,
       refs: list[dict], aliases: list[str] | None = None,
       url: str = "http://paulbourke.net/fractals/lsys/") -> dict:
    update = f"axiom={axiom!r} rule={rule!r} angle={angle}"
    params = dict(_PARAMS)
    params["angle"] = {"default": angle, "range": [1.0, 180.0]}
    return {
        "name": name,
        "aliases": aliases or [],
        "iteration_type": "l_system",
        "update": update,
        "init": f"axiom: {axiom}",
        "params": params,
        "presets": _PRESETS,
        "variants": [],
        "references": refs,
        "description_en": desc,
        "source_url": refs[0].get("url", url),
    }


_PB_URL = "http://paulbourke.net/fractals/lsys/"
_ABOP_URL = "http://algorithmicbotany.org/papers/abop/abop.pdf"
_ABOP = [
    {"author": "P. Prusinkiewicz, A. Lindenmayer",
     "title": "The Algorithmic Beauty of Plants", "year": 1990,
     "url": _ABOP_URL},
]
_PB = lambda title: [  # noqa: E731
    {"author": "Paul Bourke", "title": title, "year": 2002, "url": _PB_URL},
]


TABLE: list[dict] = [
    # ---- Hilbert / Moore / Peano / Lebesgue space-filling curves
    _e("Hilbert Curve 3D Alpha",
       "X", "X->^<XF^<XFX-F^>>XFX&F+>>XFX-F>X->",
       90,
       "3D Hilbert curve variant Alpha (McKenna 1985) — fills unit cube via 90° turtle navigation in 3D.",
       _ABOP + _PB("3D Hilbert"),
       aliases=["3D Hilbert Alpha"]),
    _e("Hilbert Curve 3D Beta",
       "A", "A->B-F+CFC+F-D&F^D-F+&&CFC+F+B//",
       90,
       "3D Hilbert curve variant Beta — alternate 3D order producing the same volume-fill but different visit order (Hilbert-3 of order 2).",
       _ABOP + _PB("3D Hilbert beta")),
    _e("Hilbert Curve 3D Gosper",
       "A", "A->^>F^F-FA-A^F-F>F+",
       90,
       "Gosper-style 3D Hilbert variant — 3D space-filling using Gosper-derived production rules.",
       _PB("3D Hilbert Gosper")),
    _e("Moore Curve (Closed Hilbert)",
       "LFL+F+LFL", "L->-RF+LFL+FR-; R->+LF-RFR-FL+",
       90,
       "Moore curve — closed-loop variant of Hilbert curve forming a single loop visiting every cell of an n×n grid.",
       _ABOP + _PB("Moore curve"),
       aliases=["Moore"]),
    _e("Peano Curve (Original 1890)",
       "X", "X->XFYFX+F+YFXFY-F-XFYFX; Y->YFXFY-F-XFYFX+F+YFXFY",
       90,
       "Original Peano curve (Giuseppe Peano 1890) — first published space-filling curve. 3-by-3 substitution.",
       [{"author": "G. Peano",
         "title": "Sur une courbe, qui remplit toute une aire plane",
         "year": 1890, "url": "https://doi.org/10.1007/BF01199438",
         "doi": "10.1007/BF01199438"}],
       aliases=["Peano original"]),
    _e("Peano-Gosper Curve",
       "X", "X->X+YF++YF-FX--FXFX-YF+; Y->-FX+YFYF++YF+FX--FX-Y",
       60,
       "Peano-Gosper space-filling curve — Gosper's hexagonal variant with 7-segment substitution; fills hexagonal Gosper island.",
       _PB("Peano-Gosper"), aliases=["Gosper curve", "Flowsnake"]),
    _e("Gosper Island",
       "F", "F->F+F++F-F", 60,
       "Gosper island — boundary curve of the Peano-Gosper curve; encloses hexagonal-snowflake-like region.",
       _PB("Gosper island")),
    _e("Hex-Gosper",
       "XF", "X->X+YF++YF-FX--FXFX-YF+; Y->-FX+YFYF++YF+FX--FX-Y",
       60,
       "Hex-Gosper curve — hexagonal-tiling variant of Gosper curve at hexagonal step layout.",
       _PB("Hex-Gosper"), aliases=["hexagonal Gosper"]),
    _e("McKenna Curve",
       "F+F+F+F+F", "F->F-F+F+F-F", 72,
       "McKenna curve (1985) — pentagonal space-filling curve from McKenna's 'Fractal curves' paper.",
       _PB("McKenna curve")),
    _e("Lebesgue Curve",
       "L", "L->LFL-FL-FL+FLFLFL-FL", 90,
       "Lebesgue space-filling curve — quaternary substitution; alternative to Hilbert/Peano.",
       _PB("Lebesgue curve")),
    _e("Sierpinski Curve (Closed)",
       "F--XF--F--XF", "X->XF+F+XF--F--XF+F+X", 45,
       "Sierpinski closed curve — boundary of the Sierpinski carpet; closed loop visiting the carpet boundary.",
       _PB("Sierpinski curve closed")),
    _e("Sierpinski-Knopp Curve",
       "FX", "X->+FX+F-FX-FX-F+FX+; F->F", 90,
       "Sierpinski-Knopp space-filling curve — Knopp's 1917 variant of Sierpinski's space-filling curve.",
       [{"author": "K. Knopp",
         "title": "Theorie und Anwendung der unendlichen Reihen",
         "year": 1917, "url": "https://en.wikipedia.org/wiki/Sierpi%C5%84ski_curve"}]),
    _e("Murray Polygon Curve (Order 3)",
       "F", "F->F+F-F-F+F+F-F", 60,
       "Murray polygon curve — generalised polygon-based space-filling curves of arbitrary order.",
       _PB("Murray polygon")),
    _e("Murray Polygon Curve (Order 5)",
       "F", "F->F+F-F-F+F-F+F+F-F", 72,
       "Murray polygon order-5 — pentagonal-symmetry Murray curve variant.",
       _PB("Murray polygon 5")),

    # ---- Quadratic Koch islands at multiple depths
    _e("Quadratic Koch Island (Type A)",
       "F+F+F+F", "F->F+FF-FF-F-F+F+FF-F-F+F+FF+FF-F", 90,
       "Quadratic Koch island Type A — 8-segment substitution producing closed island with fractal coastline.",
       _PB("Quadratic Koch A")),
    _e("Quadratic Koch Island (Type B)",
       "F+F+F+F", "F->F-FF+FF+F+F-F-FF+F+F-F-FF-FF+F", 90,
       "Quadratic Koch island Type B — alternate quadratic Koch substitution with rotated bumps.",
       _PB("Quadratic Koch B")),
    _e("Koch Snowflake (Order 2)",
       "F++F++F", "F->F-F++F-F", 60,
       "Koch snowflake (Helge von Koch 1904) — classic fractal triangle-based snowflake.",
       _PB("Koch snowflake")),
    _e("Koch Anti-Snowflake",
       "F++F++F", "F->F+F--F+F", 60,
       "Anti-Koch snowflake — bumps inward instead of outward producing star-of-David-like fractal.",
       _PB("Anti-Koch")),

    # ---- Christmas trees & canopies
    _e("Christmas Tree Symmetric",
       "X", "X->F[+X][-X]FX; F->FF", 25,
       "Symmetric fractal Christmas tree — bilateral branching producing Christmas-tree silhouette.",
       _ABOP, aliases=["xmas tree"]),
    _e("Christmas Tree Asymmetric",
       "X", "X->F[+X][-X]F[+X]X; F->FF", 28,
       "Asymmetric fractal Christmas tree — biased branching with extra right-shoot.",
       _ABOP),
    _e("Christmas Tree Stylised",
       "X", "X->F-[[X]+X]+F[+FX]-X; F->FF", 22.5,
       "Stylised conifer Christmas tree from ABOP §1.6.",
       _ABOP),
    _e("Christmas Tree Snowy",
       "X", "X->F[+++X][---X][+X][-X]F[+X]X; F->FF", 18,
       "Bushy snow-laden conifer with 4-shoot branching pattern.",
       _ABOP),
    _e("Fractal Canopy Symmetric",
       "F", "F->FF[+F][-F]", 30,
       "Symmetric fractal canopy — flat top of recursive bifurcating tree; classical Mandelbrot canopy.",
       [{"author": "B. B. Mandelbrot", "title": "The Fractal Geometry of Nature",
         "year": 1982, "url": "https://en.wikipedia.org/wiki/Fractal_canopy"}]),
    _e("Fractal Canopy Asymmetric",
       "F", "F->FF[++F][--F][+F]", 25,
       "Asymmetric canopy with 3-shoot bifurcation; biased toward left.",
       _ABOP),
    _e("H-Fractal Tree Order 1",
       "F-F+F+F-F", "F->F-F+F+F-F", 90,
       "H-fractal — recursive Hs nested at half scale; canonical 4-shoot branching.",
       _PB("H-fractal")),
    _e("H-Fractal Tree Order 2",
       "F+F-F-F+F", "F->F+F-F-F+F", 90,
       "H-fractal alternate variant — phase-shifted production rule.",
       _PB("H-fractal-2")),

    # ---- Plant simulations (20+ variants)
    _e("Plant ABOP A",
       "F", "F->F[+F]F[-F]F", 25.7,
       "Plant A from ABOP — simple bracketed L-system producing weed-like plant.",
       _ABOP),
    _e("Plant ABOP B",
       "F", "F->F[+F]F[-F][F]", 20,
       "Plant B from ABOP — 4-bracket variant with extra leaf.",
       _ABOP),
    _e("Plant ABOP C",
       "F", "F->FF-[-F+F+F]+[+F-F-F]", 22.5,
       "Plant C from ABOP — symmetric push-pop branching.",
       _ABOP),
    _e("Plant ABOP D",
       "X", "X->F[+X]F[-X]+X; F->FF", 20,
       "Plant D from ABOP — non-terminal X with 2-shoot branching.",
       _ABOP),
    _e("Plant ABOP E",
       "X", "X->F[+X][-X]FX; F->FF", 25.7,
       "Plant E from ABOP — slightly bushier variant of D.",
       _ABOP),
    _e("Plant ABOP F (variant)",
       "X", "X->F-[[X]+X]+F[++FX]-X; F->FFF", 21.7,
       "Plant F from ABOP (variant) — fern-like bilateral branching with stronger inner-shoot bias.",
       _ABOP),
    _e("Cypress Tree",
       "F", "F->F[+F+F][-F-F]F", 18,
       "Tall slender cypress tree — narrow vertical fractal tree.",
       _PB("Cypress")),
    _e("Oak Tree",
       "F", "F->F[++F][+F][-F][--F]F", 35,
       "Oak-style tree with 4-shoot symmetric branching producing dense canopy.",
       _PB("Oak tree")),
    _e("Willow Tree",
       "F", "F->F[+++F][---F]F", 12,
       "Weeping willow — narrow drooping branches.",
       _PB("Willow")),
    _e("Birch Tree",
       "F", "F->F[+F]F[-F][+F][-F]F", 15,
       "Slender birch tree with multiple side-shoots.",
       _PB("Birch")),
    _e("Pine Tree",
       "F", "F->F[+++F][---F][++F][--F]F", 15,
       "Pine tree with downward-sweeping branches.",
       _PB("Pine")),
    _e("Maple Tree",
       "F", "F->F[+F][-F][++F][--F]F", 28,
       "Maple-style tree with broad symmetric branching.",
       _PB("Maple")),
    _e("Bonsai Tree",
       "X", "X->F[++X]F[--X]+X; F->FF", 33,
       "Bonsai-style miniature tree with twisted branches.",
       _PB("Bonsai")),
    _e("Bamboo",
       "F", "F->F[+F][-F][F]F", 8,
       "Bamboo — narrow tall jointed stems with sparse leaves.",
       _PB("Bamboo")),
    _e("Mediterranean Pine",
       "X", "X->F-[[X]+X]+F[+FX]-X; F->FF", 19,
       "Mediterranean pine — broad umbrella crown.",
       _PB("Med pine")),
    _e("Saguaro Cactus",
       "F", "F->F[++F][--F][F]F", 90,
       "Saguaro cactus L-system — vertical trunk with right-angle arm branches.",
       _PB("Saguaro")),
    _e("Sea Coral",
       "F", "F->FF-[-F+F+F]+[+F-F-F]", 30,
       "Sea-coral L-system — irregular branching reminiscent of coral.",
       _PB("Sea coral")),
    _e("Fern (Asymmetric)",
       "X", "X->F+[[X]-X]-F[-FX]+X; F->FF", 22.5,
       "Asymmetric fern from ABOP — fronds curl predominantly to one side.",
       _ABOP),

    # ---- Special L-systems
    _e("Fibonacci Word Fractal",
       "F", "F->F+G; G->F-G", 90,
       "Fibonacci word fractal (Monnerot-Dumaine 2009) — turtle drawing of infinite Fibonacci word.",
       [{"author": "A. Monnerot-Dumaine",
         "title": "The Fibonacci word fractal",
         "year": 2009, "url": "https://hal.archives-ouvertes.fr/hal-00367972"}],
       aliases=["Fibonacci word"]),
    _e("Prouhet-Thue-Morse Curve L-system",
       "F", "F->F+G; G->G-F", 60,
       "Prouhet-Thue-Morse curve — turtle drawing using Thue-Morse turn sequence.",
       [{"author": "A. Allouche, J. Shallit",
         "title": "Automatic Sequences",
         "year": 2003, "url": "https://doi.org/10.1017/CBO9780511546563",
         "doi": "10.1017/CBO9780511546563"}],
       aliases=["PTM curve"]),
    _e("Williams-Beasley Curve",
       "F", "F->F+F-F-FF+F+F-F", 90,
       "Williams-Beasley fractal curve — quadratic-substitution with 8-segment generator.",
       _PB("Williams-Beasley")),
    _e("Zetetic Curve",
       "F", "F->F+F-F-F+F+F-F-F+F", 90,
       "Zetetic curve — Brian Beasley's exploratory fractal curve from BCS Lighthouse.",
       _PB("Zetetic")),
    _e("Quadratic Snowflake",
       "F+F+F+F", "F->F-F+F+F-F", 90,
       "Quadratic Koch snowflake — closed quadratic Koch generator forming snowflake-like region.",
       _PB("Quadratic snowflake")),
]


def main() -> None:
    run_family(BATCH_ID, FAMILY, TABLE)


if __name__ == "__main__":
    main()
