"""Classic continuous-time strange attractors.

Update strings use the full 3-ODE system with semicolons so sympy parse fails
and the hash falls back to the raw string (which is unique per system).
"""
from __future__ import annotations

from scripts.research.seed_data.generator_lib import run_family

BATCH_ID = "classic_attractors"
FAMILY = "classic_attr"

_PARAMS = {
    "iterations": {"default": 200000, "range": [1000, 1000000]},
    "step_size": {"default": 0.005, "range": [0.0001, 0.05]},
}
_PRESETS = [{"id": "classic", "name": "Canonical parameters", "params": {"step_size": 0.005}}]


def _e(name: str, update: str, desc: str, refs: list[dict],
       aliases: list[str] | None = None, init: str = "x=0.1; y=0.1; z=0.1") -> dict:
    return {
        "name": name,
        "aliases": aliases or [],
        "iteration_type": "strange_attractor",
        "update": update,
        "init": init,
        "params": _PARAMS,
        "presets": _PRESETS,
        "variants": [],
        "references": refs,
        "description_en": desc,
        "source_url": refs[0].get("url", ""),
    }


TABLE: list[dict] = [
    _e(
        "Lorenz System",
        "dx = 10*(y-x); dy = x*(28-z) - y; dz = x*y - 2.667*z",
        "Classical Lorenz system (1963) with canonical parameters sigma=10, rho=28, beta=8/3 giving the butterfly attractor — the foundational example of deterministic chaos and sensitive dependence on initial conditions.",
        [{"author": "E. N. Lorenz", "title": "Deterministic nonperiodic flow", "year": 1963,
          "url": "https://doi.org/10.1175/1520-0469(1963)020%3C0130:DNF%3E2.0.CO;2",
          "doi": "10.1175/1520-0469(1963)020<0130:DNF>2.0.CO;2"}],
        aliases=["Lorenz butterfly", "butterfly attractor"],
    ),
    _e(
        "Lorenz-84",
        "dx = -y**2 - z**2 - a*x + a*F; dy = x*y - b*x*z - y + G; dz = b*x*y + x*z - z",
        "Lorenz-84 atmospheric circulation model — a low-order model of the general atmospheric circulation exhibiting chaos for appropriate F,G forcing parameters.",
        [{"author": "E. N. Lorenz", "title": "Irregularity: a fundamental property of the atmosphere", "year": 1984,
          "url": "https://doi.org/10.1111/j.1600-0870.1984.tb00230.x",
          "doi": "10.1111/j.1600-0870.1984.tb00230.x"}],
        aliases=["Lorenz 84"],
    ),
    _e(
        "Lorenz-96",
        "dxi = (x_next - x_prev2)*x_prev - xi + F",
        "Lorenz-96 N-dimensional toy climate model: dXi/dt = (Xi+1 - Xi-2)*Xi-1 - Xi + F. Exhibits spatiotemporal chaos for F > 4; widely used in data-assimilation benchmarks.",
        [{"author": "E. N. Lorenz", "title": "Predictability: a problem partly solved", "year": 1995,
          "url": "https://www.ecmwf.int/sites/default/files/elibrary/1995/10829-predictability-problem-partly-solved.pdf"}],
        aliases=["Lorenz 96"],
    ),
    _e(
        "Rössler Attractor",
        "dx = -y - z; dy = x + 0.2*y; dz = 0.2 + z*(x - 5.7)",
        "Rössler attractor (1976) with canonical parameters a=0.2, b=0.2, c=5.7. Single folded-band attractor from a system with just one quadratic nonlinearity.",
        [{"author": "O. E. Rössler", "title": "An equation for continuous chaos", "year": 1976,
          "url": "https://doi.org/10.1016/0375-9601(76)90101-8",
          "doi": "10.1016/0375-9601(76)90101-8"}],
        aliases=["Roessler", "Rossler"],
    ),
    _e(
        "Rössler Hyperchaos",
        "dx = -y - z; dy = x + 0.25*y + w; dz = 3 + x*z; dw = -0.5*z + 0.05*w",
        "Rössler's 4D hyperchaotic system (1979) — two positive Lyapunov exponents. First system to demonstrate continuous-time hyperchaos.",
        [{"author": "O. E. Rössler", "title": "An equation for hyperchaos", "year": 1979,
          "url": "https://doi.org/10.1016/0375-9601(79)90150-6",
          "doi": "10.1016/0375-9601(79)90150-6"}],
    ),
    _e(
        "Chua's Circuit (double scroll)",
        "dx = alpha*(y - x - fx); dy = x - y + z; dz = -beta*y",
        "Chua's circuit (1983) with piecewise-linear nonlinearity fx=m1*x+0.5*(m0-m1)*(|x+1|-|x-1|). Simplest autonomous electronic circuit exhibiting chaos; double-scroll attractor is the signature shape.",
        [{"author": "T. Matsumoto", "title": "A chaotic attractor from Chua's circuit", "year": 1984,
          "url": "https://doi.org/10.1109/TCS.1984.1085459",
          "doi": "10.1109/TCS.1984.1085459"}],
        aliases=["Chua double scroll", "Chua circuit"],
    ),
    _e(
        "Chen Attractor",
        "dx = 35*(y - x); dy = -7*x - x*z + 28*y; dz = x*y - 3*z",
        "Chen's chaotic attractor (1999) with classic parameters a=35, b=3, c=28. Topologically non-equivalent to Lorenz though structurally similar.",
        [{"author": "G. Chen, T. Ueta", "title": "Yet another chaotic attractor", "year": 1999,
          "url": "https://doi.org/10.1142/S0218127499001024",
          "doi": "10.1142/S0218127499001024"}],
    ),
    _e(
        "Lü System",
        "dx = 36*(y - x); dy = -x*z + 20*y; dz = x*y - 3*z",
        "Lü system (2002) with parameters a=36, b=3, c=20. Bridges Lorenz and Chen families via continuous parameter deformation.",
        [{"author": "J. Lü, G. Chen", "title": "A new chaotic attractor coined", "year": 2002,
          "url": "https://doi.org/10.1142/S0218127402004620",
          "doi": "10.1142/S0218127402004620"}],
        aliases=["Lu system", "Lu-Chen system"],
    ),
    _e(
        "Halvorsen Attractor",
        "dx = -1.4*x - 4*y - 4*z - y**2; dy = -1.4*y - 4*z - 4*x - z**2; dz = -1.4*z - 4*x - 4*y - x**2",
        "Halvorsen cyclically symmetric attractor: each equation is a cyclic permutation of the others.",
        [{"author": "Chlouverakis & Sprott", "title": "Chaotic hyperjerk systems", "year": 2006,
          "url": "https://sprott.physics.wisc.edu/pubs/paper330.pdf"}],
    ),
    _e(
        "Aizawa Attractor",
        "dx = (z - 0.7)*x - 3.5*y; dy = 3.5*x + (z - 0.7)*y; dz = 0.6 + 0.95*z - z**3/3 - (x**2 + y**2)*(1 + 0.25*z) + 0.1*z*x**3",
        "Aizawa attractor — 3D system whose attractor resembles a sphere-wrapping spiral structure with polar lobes.",
        [{"author": "Y. Aizawa", "title": "Aizawa attractor (classical catalog)", "year": 1982,
          "url": "https://www.algosome.com/articles/aizawa-attractor-chaos.html"}],
    ),
    _e(
        "Thomas Attractor",
        "dx = sin(y) - 0.208186*x; dy = sin(z) - 0.208186*y; dz = sin(x) - 0.208186*z",
        "Thomas' cyclically symmetric attractor with pure sine coupling. For b < 0.32899 the flow is chaotic; labyrinth chaos emerges as b → 0.",
        [{"author": "R. Thomas", "title": "Deterministic chaos seen in terms of feedback circuits", "year": 1999,
          "url": "https://doi.org/10.1142/S0218127499001383",
          "doi": "10.1142/S0218127499001383"}],
        aliases=["Thomas cyclically symmetric attractor", "labyrinth chaos"],
    ),
    _e(
        "Three-Scroll Unified (Pan)",
        "dx = 40*(y - x) + 0.833*x*z; dy = 20*y - x*z; dz = 0.5*x*y - 0.65*z",
        "Three-Scroll Unified Chaotic System (Pan, Zhou, Lü 2010) — generates exactly three scrolls; unifies features from Lorenz/Chen/Lü.",
        [{"author": "L. Pan et al.", "title": "A new three-scroll unified chaotic system", "year": 2010,
          "url": "https://doi.org/10.1109/CINC.2010.5643913",
          "doi": "10.1109/CINC.2010.5643913"}],
        aliases=["TSUCS", "three scroll"],
    ),
    _e(
        "Shimizu-Morioka",
        "dx = y; dy = (1 - z)*x - 0.75*y; dz = x**2 - 0.45*z",
        "Shimizu-Morioka system (1980) — simplification of the Lorenz system that retains the butterfly topology while using fewer parameters.",
        [{"author": "T. Shimizu, N. Morioka",
          "title": "Bifurcation of a symmetric limit cycle in a simple model", "year": 1980,
          "url": "https://doi.org/10.1016/0375-9601(80)90363-5",
          "doi": "10.1016/0375-9601(80)90363-5"}],
    ),
    _e(
        "Rabinovich-Fabrikant",
        "dx = y*(z - 1 + x**2) + 0.1*x; dy = x*(3*z + 1 - x**2) + 0.1*y; dz = -2*z*(0.87 + x*y)",
        "Rabinovich-Fabrikant equations (1979) — physical model for stochasticity in non-equilibrium media.",
        [{"author": "M. I. Rabinovich, A. L. Fabrikant",
          "title": "Stochastic self-modulation of waves in nonequilibrium media", "year": 1979,
          "url": "https://link.springer.com/article/10.1007/BF01118570"}],
    ),
    _e(
        "Dadras Attractor",
        "dx = y - 3*x + 2.7*y*z; dy = 1.7*y - x*z + z; dz = 2*x*y - 9*z",
        "Dadras attractor (2009) — 3D chaotic system with simple quadratic nonlinearities and no equilibria.",
        [{"author": "S. Dadras, H. R. Momeni",
          "title": "A novel three-dimensional autonomous chaotic system", "year": 2009,
          "url": "https://doi.org/10.1016/j.physleta.2009.05.015",
          "doi": "10.1016/j.physleta.2009.05.015"}],
    ),
    _e(
        "Burke-Shaw",
        "dx = -10*(x + y); dy = -y - 10*x*z; dz = 10*x*y + 4.272",
        "Burke-Shaw attractor — cyclic-symmetric variant of Lorenz.",
        [{"author": "W. Burke, R. Shaw", "title": "Strange attractor in a double-pendulum experiment", "year": 1981,
          "url": "https://doi.org/10.1016/0375-9601(81)90040-X",
          "doi": "10.1016/0375-9601(81)90040-X"}],
    ),
    _e(
        "Moore-Spiegel",
        "dx = y; dy = z; dz = -z - (20 - 9 + 9*x**2)*y - 20*x",
        "Moore-Spiegel oscillator (1966) — simplified model of thermal convection in a stellar atmosphere; a canonical 'jerk' equation.",
        [{"author": "D. W. Moore, E. A. Spiegel", "title": "A thermally excited non-linear oscillator", "year": 1966,
          "url": "https://ui.adsabs.harvard.edu/abs/1966ApJ...143..871M"}],
    ),
    _e(
        "Newton-Leipnik",
        "dx = -0.4*x + y + 10*y*z; dy = -x - 0.4*y + 5*x*z; dz = 0.175*z - 5*x*y",
        "Newton-Leipnik attractor — anisotropic chaos from rigid-body dynamics; exhibits twin coexisting strange attractors.",
        [{"author": "R. B. Leipnik, T. A. Newton",
          "title": "Double strange attractors in rigid body motion", "year": 1981,
          "url": "https://doi.org/10.1016/0375-9601(81)90165-9",
          "doi": "10.1016/0375-9601(81)90165-9"}],
    ),
    _e(
        "Rucklidge Attractor",
        "dx = -2*x + 6.7*y - y*z; dy = x; dz = -z + y**2",
        "Rucklidge model of double-convection (1992). Two-parameter family with rich bifurcation structure.",
        [{"author": "A. M. Rucklidge", "title": "Chaos in models of double convection", "year": 1992,
          "url": "https://doi.org/10.1017/S0022112092001915",
          "doi": "10.1017/S0022112092001915"}],
    ),
    _e(
        "Wang-Sun Attractor",
        "dx = a*x + c*y*z; dy = b*x + d*y - x*z; dz = e*z + f*x*y",
        "Wang-Sun attractor (2012) — 3D chaotic system with only one stable equilibrium, yet a hidden chaotic attractor coexists.",
        [{"author": "Z. Wang, S. Sun",
          "title": "A new chaotic system with only one stable equilibrium", "year": 2012,
          "url": "https://doi.org/10.1016/j.cnsns.2012.01.015",
          "doi": "10.1016/j.cnsns.2012.01.015"}],
    ),
    _e(
        "Arneodo Attractor",
        "dx = y; dy = z; dz = 5.5*x - 3.5*y - z - x**3",
        "Arneodo-Coullet-Tresser attractor (1981) — simple polynomial system with period-doubling cascade and homoclinic chaos.",
        [{"author": "A. Arneodo, P. Coullet, C. Tresser",
          "title": "Possible new strange attractors with spiral structure", "year": 1981,
          "url": "https://doi.org/10.1007/BF01208379",
          "doi": "10.1007/BF01208379"}],
        aliases=["Arneodo-Coullet-Tresser"],
    ),
    _e(
        "Nosé-Hoover",
        "dx = y; dy = y*z - x; dz = 1 - y**2",
        "Nosé-Hoover oscillator — conservative (non-dissipative) chaotic system from molecular-dynamics thermostats.",
        [{"author": "W. G. Hoover",
          "title": "Canonical dynamics: Equilibrium phase-space distributions", "year": 1985,
          "url": "https://doi.org/10.1103/PhysRevA.31.1695",
          "doi": "10.1103/PhysRevA.31.1695"}],
        aliases=["Nose-Hoover"],
    ),
    _e(
        "Chen-Lee",
        "dx = -y*z + 5*x; dy = x*z - 10*y; dz = x*y/3 - 3.8*z",
        "Chen-Lee chaotic system (2004) from anti-control of chaos studies in rigid body motion.",
        [{"author": "H. Chen, C. Lee",
          "title": "Anti-control of chaos in rigid body motion", "year": 2004,
          "url": "https://doi.org/10.1016/j.chaos.2004.02.008",
          "doi": "10.1016/j.chaos.2004.02.008"}],
    ),
    _e(
        "Dequan Li Attractor",
        "dx = 40*(y - x) + 16*y*z; dy = -x*z + 55*y; dz = x*y - 1.833*z",
        "Dequan Li attractor (2008) — three-scroll chaotic attractor with rich multi-scroll phase-space topology.",
        [{"author": "D. Li", "title": "A three-scroll chaotic attractor", "year": 2008,
          "url": "https://doi.org/10.1016/j.physleta.2007.05.040",
          "doi": "10.1016/j.physleta.2007.05.040"}],
    ),
    _e(
        "Finance Chaotic System",
        "dx = z + (y - 0.9)*x; dy = 1 - 0.2*y - x**2; dz = -x - 1.2*z",
        "Finance chaotic model (Ma-Chen 2001) describing nonlinear dynamics in a financial market with interest rate, investment demand and price index.",
        [{"author": "J. Ma, Y. Chen",
          "title": "Bifurcation topology of a financial chaotic system", "year": 2001,
          "url": "https://doi.org/10.1007/BF02435525",
          "doi": "10.1007/BF02435525"}],
    ),
    _e(
        "Four-Wing Chaotic",
        "dx = a*x + b*y*z; dy = c*x + d*y - x*z; dz = e*z + f*x*y",
        "Four-wing chaotic attractor — extended Chen-family system producing four scrolls/wings in phase space.",
        [{"author": "W. Wang, Y. Zhang",
          "title": "A new four-wing chaotic attractor with circuit implementation", "year": 2012,
          "url": "https://doi.org/10.1016/j.chaos.2011.08.006",
          "doi": "10.1016/j.chaos.2011.08.006"}],
    ),
    _e(
        "Liu Chaotic System",
        "dx = 10*(y - x); dy = 40*x - x*z; dz = -2.5*z + 4*x**2",
        "Liu chaotic system (2004) — a Lorenz-like system with a squared-x feedback in z.",
        [{"author": "C. Liu, T. Liu, L. Liu, K. Liu",
          "title": "A new chaotic attractor", "year": 2004,
          "url": "https://doi.org/10.1016/j.chaos.2003.12.034",
          "doi": "10.1016/j.chaos.2003.12.034"}],
    ),
    _e(
        "Qi Chaotic System",
        "dx = a*(y - x) + y*z; dy = c*x - y - x*z; dz = x*y - b*z",
        "Qi's 4D chaotic system (2008) with a large positive Lyapunov exponent. Variant of the generalized Lorenz family.",
        [{"author": "G. Qi et al.", "title": "A new hyperchaotic system", "year": 2008,
          "url": "https://doi.org/10.1016/j.physleta.2007.12.072",
          "doi": "10.1016/j.physleta.2007.12.072"}],
    ),
    _e(
        "Hadley Circulation",
        "dx = -y**2 - z**2 - 0.2*x + 0.2*7; dy = x*y - 4*x*z - y + 1.2; dz = 4*x*y + x*z - z",
        "Hadley convection model (Masoller et al.) — simplified atmospheric circulation with chaotic regimes; a specific parameter case of the Lorenz-84 structural family.",
        [{"author": "Hadley 1735; Lorenz 1984",
          "title": "Atmospheric circulation model", "year": 1984,
          "url": "https://doi.org/10.3402/tellusa.v36i2.11473",
          "doi": "10.3402/tellusa.v36i2.11473"}],
    ),
    _e(
        "Sakarya Attractor",
        "dx = -x + y + y*z; dy = -x - y + a*x*z; dz = z - b*x*y",
        "Sakarya chaotic system — 3D autonomous system with quadratic cross-terms.",
        [{"author": "Y. Li, W. K. S. Tang, G. Chen",
          "title": "Generating hyperchaos via state feedback control", "year": 2005,
          "url": "https://doi.org/10.1142/S0218127405013605",
          "doi": "10.1142/S0218127405013605"}],
    ),
    _e(
        "Bouali Attractor",
        "dx = 3*x*(1 - y) - 0.5*z; dy = -y*(1 - x**2); dz = 0.05*x",
        "Bouali attractor (2012) — economic cycle model exhibiting stretched-loop chaotic regime.",
        [{"author": "S. Bouali",
          "title": "A novel strange attractor with a stretched loop", "year": 2012,
          "url": "https://doi.org/10.1007/s11071-011-0260-7",
          "doi": "10.1007/s11071-011-0260-7"}],
    ),
    _e(
        "Yu-Wang",
        "dx = a*(y - x); dy = b*x - c*x*z; dz = exp(x*y) - d*z",
        "Yu-Wang chaotic system (2012) — 3D autonomous with exponential nonlinearity.",
        [{"author": "F. Yu, C. Wang",
          "title": "A novel three-dimensional autonomous chaotic system", "year": 2012,
          "url": "https://doi.org/10.1007/s11071-012-0439-x",
          "doi": "10.1007/s11071-012-0439-x"}],
    ),
    _e(
        "Genesio-Tesi",
        "dx = y; dy = z; dz = -c*x - b*y - a*z + x**2",
        "Genesio-Tesi chaotic system (1992) — simple polynomial 3D with single quadratic nonlinearity, canonical jerk form.",
        [{"author": "R. Genesio, A. Tesi",
          "title": "Harmonic balance methods for chaotic dynamics", "year": 1992,
          "url": "https://doi.org/10.1016/0005-1098(92)90177-H",
          "doi": "10.1016/0005-1098(92)90177-H"}],
    ),
    _e(
        "Coullet System",
        "dx = y; dy = z; dz = a*x - b*y - c*z - x**3",
        "Coullet 3D system — canonical jerk equation with cubic nonlinearity exhibiting period-doubling.",
        [{"author": "P. Coullet, C. Tresser",
          "title": "Iterations d'endomorphismes et groupe de renormalisation", "year": 1978,
          "url": "https://doi.org/10.1051/jphyscol:1978517"}],
    ),
    _e(
        "Hindmarsh-Rose",
        "dx = y - x**3 + 3*x**2 - z + I; dy = 1 - 5*x**2 - y; dz = r*(s*(x - x0) - z)",
        "Hindmarsh-Rose neuron model (1984) — 3-variable simplified model of neuronal bursting behavior.",
        [{"author": "J. L. Hindmarsh, R. M. Rose",
          "title": "A model of neuronal bursting using three coupled first order differential equations", "year": 1984,
          "url": "https://doi.org/10.1098/rspb.1984.0024",
          "doi": "10.1098/rspb.1984.0024"}],
    ),
    _e(
        "Duffing Oscillator (forced)",
        "dx = y; dy = -delta*y - alpha*x - beta*x**3 + gamma*cos(omega*t)",
        "Forced Duffing oscillator — periodically forced anharmonic oscillator with hysteresis and chaos.",
        [{"author": "G. Duffing",
          "title": "Erzwungene Schwingungen bei veränderlicher Eigenfrequenz",
          "year": 1918, "url": "https://archive.org/details/erzwungeneschwin00duff"}],
    ),
    _e(
        "Van der Pol (forced)",
        "dx = y; dy = mu*(1 - x**2)*y - x + A*cos(omega*t)",
        "Forced van der Pol oscillator — canonical self-sustained relaxation oscillator with chaotic response to strong forcing.",
        [{"author": "B. van der Pol", "title": "On relaxation-oscillations", "year": 1926,
          "url": "https://doi.org/10.1080/14786442608564127",
          "doi": "10.1080/14786442608564127"}],
    ),
    _e(
        "FitzHugh-Nagumo",
        "dv = v - v**3/3 - w + I; dw = phi*(v + a - b*w)",
        "FitzHugh-Nagumo model — 2-variable simplification of Hodgkin-Huxley neuron; shows excitability and limit cycles.",
        [{"author": "R. FitzHugh",
          "title": "Impulses and physiological states in theoretical models of nerve membrane",
          "year": 1961, "url": "https://doi.org/10.1016/S0006-3495(61)86902-6",
          "doi": "10.1016/S0006-3495(61)86902-6"}],
    ),
    _e(
        "Langford Attractor",
        "dx = (z - beta)*x - omega*y; dy = omega*x + (z - beta)*y; dz = lambda_ + alpha*z - z**3/3 - (x**2 + y**2)*(1 + rho*z) + epsilon*z*x**3",
        "Langford attractor — precursor of the Aizawa system; features a torus breakdown to chaos.",
        [{"author": "W. F. Langford",
          "title": "Numerical studies of torus bifurcations", "year": 1984,
          "url": "https://doi.org/10.1007/978-3-0348-6256-1_19",
          "doi": "10.1007/978-3-0348-6256-1_19"}],
    ),
    _e(
        "Sprott-Jafari No-Equilibrium",
        "dx = y; dy = -x + y*z; dz = -x - a*x*y - x*z",
        "Sprott-Jafari hidden attractor — a chaotic system with no equilibria, pioneering example of hidden attractors.",
        [{"author": "S. Jafari, J. C. Sprott, M. Golpayegani",
          "title": "Elementary chaotic flows with no equilibria", "year": 2013,
          "url": "https://doi.org/10.1016/j.physleta.2013.07.042",
          "doi": "10.1016/j.physleta.2013.07.042"}],
    ),
    _e(
        "Van der Pol (unforced)",
        "dx = y; dy = mu*(1 - x**2)*y - x",
        "Unforced van der Pol relaxation oscillator — prototype self-excited oscillator.",
        [{"author": "B. van der Pol", "title": "On relaxation-oscillations", "year": 1926,
          "url": "https://doi.org/10.1080/14786442608564127",
          "doi": "10.1080/14786442608564127"}],
    ),
]


def main() -> None:
    run_family(BATCH_ID, FAMILY, TABLE)


if __name__ == "__main__":
    main()
