"""Number-theory fractals (Family 3).

Sources:
  - H. Weyl, "Über die Gleichverteilung von Zahlen mod. Eins" (1916).
  - M. Mendès France, G. Tenenbaum, "Sur les fractales de Weierstrass".
  - S. Lehmer, "Continued fractions of algebraic and transcendental numbers".
  - Erdős, Moser, Rado, "On the evolution of random graphs".
  - L. Collatz correspondence; OEIS / Numberphile visualisations.
  - Stern-Brocot / Farey sequence literature.
"""
from __future__ import annotations

from scripts.research.seed_data.generator_lib import run_family

BATCH_ID = "number_theory"
FAMILY = "numtheory"

_PARAMS = {
    "depth": {"default": 12, "range": [1, 24]},
    "iterations": {"default": 100000, "range": [100, 1000000]},
}
_PRESETS = [{"id": "default", "name": "Default", "params": {}}]


def _e(name: str, update: str, init: str, desc: str, refs: list[dict],
       aliases: list[str] | None = None) -> dict:
    return {
        "name": name,
        "aliases": aliases or [],
        "iteration_type": "number_theory",
        "update": update,
        "init": init,
        "params": _PARAMS,
        "presets": _PRESETS,
        "variants": [],
        "references": refs,
        "description_en": desc,
        "source_url": refs[0].get("url", ""),
    }


_MW = "https://mathworld.wolfram.com/"
_OEIS = "https://oeis.org"


TABLE: list[dict] = [
    _e("Stern-Brocot Tree Fractal",
       "node(a/b, c/d) -> left=(a/b, (a+c)/(b+d)), right=((a+c)/(b+d), c/d)",
       "tree rooted at 1/1 with parents 0/1 and 1/0",
       "Stern-Brocot tree fractal — every positive rational appears exactly once. Rendering depth-vs-value exposes self-similar fractal structure with golden-ratio scaling for Fibonacci branches.",
       [{"author": "M. A. Stern", "title": "Über eine zahlentheoretische Funktion",
         "year": 1858, "url": _MW + "Stern-BrocotTree.html"},
        {"author": "A. Brocot", "title": "Calcul des rouages par approximation",
         "year": 1861, "url": _MW + "Stern-BrocotTree.html"}],
       aliases=["Stern-Brocot"]),
    _e("Farey Sequence Fractal",
       "F_n = sorted{p/q | 0 <= p <= q <= n, gcd(p,q)=1}",
       "F_0 = {0/1, 1/1}",
       "Farey sequence fractal — F_n is the sorted list of irreducible fractions in [0,1] with denominator <= n. Plot of mediant convergence reveals Ford-circle Apollonian-like self-similarity.",
       [{"author": "J. Farey", "title": "On a curious property of vulgar fractions",
         "year": 1816, "url": _MW + "FareySequence.html"}],
       aliases=["Farey"]),
    _e("Ford Circles Apollonian",
       "circle(p/q) = {radius=1/(2*q*q), center=(p/q, 1/(2*q*q))}",
       "root circles at 0/1 and 1/1",
       "Ford circles (Ford 1938) — for every p/q in lowest terms place a circle tangent to the x-axis at p/q with radius 1/(2q²). Adjacent Farey fractions produce mutually tangent circles → Apollonian packing.",
       [{"author": "L. R. Ford", "title": "Fractions",
         "year": 1938, "url": "https://doi.org/10.2307/2302799",
         "doi": "10.2307/2302799"}],
       aliases=["Ford circles"]),
    _e("Minkowski Question Mark Function",
       "?(x) = sum_{k>=1} (-1)^(k+1) * 2^(1 - (a_1 + ... + a_k)) where x = [a_0; a_1, a_2, ...] (continued fraction)",
       "x in [0,1]",
       "Minkowski's question-mark function ?(x) — maps quadratic irrationals to dyadic rationals; its derivative is zero almost everywhere yet it is strictly increasing. Singular continuous fractal graph.",
       [{"author": "H. Minkowski", "title": "Zur Geometrie der Zahlen",
         "year": 1904, "url": _MW + "MinkowskiQuestionMarkFunction.html"}],
       aliases=["?(x)", "Minkowski ?"]),
    _e("Devil's Staircase (Cantor Function)",
       "c(x) = sum_{k>=1} b_k * 2^{-k} where x = sum_{k>=1} (2*b_k)*3^{-k}",
       "x in [0,1], ternary expansion avoiding 1s",
       "Cantor devil's staircase — the Cantor function; continuous, monotonic, derivative zero almost everywhere, maps Cantor set onto [0,1]. Classical singular continuous function.",
       [{"author": "G. Cantor",
         "title": "De la puissance des ensembles parfaits de points",
         "year": 1884, "url": _MW + "CantorFunction.html"}],
       aliases=["Cantor function", "Devil's staircase"]),
    _e("Weierstrass Function",
       "W(x) = sum_{n=0}^inf (0.5)**n * cos((3**n)*pi*x)",
       "x in [0,1]",
       "Weierstrass function (1872) — sum_{n} a^n cos(b^n π x) with ab>1+3π/2. First published example of a continuous nowhere-differentiable function; graph has Hausdorff dimension >1.",
       [{"author": "K. Weierstrass",
         "title": "Über continuirliche Functionen eines reellen Arguments, die für keinen Werth des letzeren einen bestimmten Differentialquotienten besitzen",
         "year": 1872, "url": _MW + "WeierstrassFunction.html"}],
       aliases=["Weierstrass"]),
    _e("Weierstrass Function (a=0.3, b=7)",
       "W(x) = sum_{n=0}^inf (0.3)**n * cos((7**n)*pi*x)",
       "x in [0,1]",
       "Weierstrass function with a=0.3, b=7 — alternate parameter set producing higher-frequency rough graph with similar fractal dimension.",
       [{"author": "G. H. Hardy", "title": "Weierstrass's non-differentiable function",
         "year": 1916, "url": "https://doi.org/10.1090/S0002-9947-1916-1501068-6",
         "doi": "10.1090/S0002-9947-1916-1501068-6"}]),
    _e("Weierstrass-Mandelbrot Cosine",
       "W_M(x) = sum_{n=-inf}^inf (1 - cos(gamma**n * x)) / gamma**((2-D)*n) with gamma=1.5, D=1.5",
       "x in R",
       "Weierstrass-Mandelbrot function — bilateral series producing self-similar graph with exact fractal dimension D. Key example in Mandelbrot's fractal-geometry exposition.",
       [{"author": "B. B. Mandelbrot", "title": "The Fractal Geometry of Nature",
         "year": 1982, "url": _MW + "Weierstrass-MandelbrotFunction.html"}]),
    _e("Takagi (Blancmange) Curve",
       "T(x) = sum_{n=0}^inf (1/2)**n * s(2**n * x); s(y) = |y - round(y)|",
       "x in [0,1]",
       "Takagi blancmange curve (1901) — continuous nowhere-differentiable function whose graph resembles a pudding (blancmange). Related to Cantor's function via base-2 expansions.",
       [{"author": "T. Takagi",
         "title": "A simple example of a continuous function without derivative",
         "year": 1901, "url": _MW + "TakagiFractalCurve.html"}],
       aliases=["Blancmange"]),
    _e("Takagi-Landsberg Curve",
       "T_w(x) = sum_{n=0}^inf w**n * s(2**n * x) with w=1/3",
       "x in [0,1]",
       "Takagi-Landsberg curve with weight w=1/3 — parametric family generalising Takagi curve; dimension 2 + log₂(w) for 1/2<w<1.",
       [{"author": "G. Landsberg",
         "title": "Über eine einfache Methode zur Konstruktion stetiger nirgends differenzierbarer Funktionen",
         "year": 1908, "url": _MW + "TakagiFractalCurve.html"}]),
    _e("Bolzano Non-Differentiable",
       "B_0(x) = x; B_{n+1}(x) piecewise linear on 4 segments through fixed points",
       "B_0(x) = x on [0,1]",
       "Bolzano's nowhere-differentiable function (~1830, published posthumously 1930) — earliest known construction, piecewise-linear 4-segment iteration.",
       [{"author": "B. Bolzano",
         "title": "Functionenlehre (posthumous)",
         "year": 1830, "url": _MW + "BolzanoFunction.html"}],
       aliases=["Bolzano function"]),
    _e("Collatz Fractal",
       "c(n) = n/2 if n even, 3*n+1 if n odd",
       "seed n over integers; visit heatmap",
       "Collatz 3n+1 conjecture fractal — plotting orbit lengths over integer grid produces fractal heatmap. Conway proved generalised Collatz maps are undecidable.",
       [{"author": "L. Collatz",
         "title": "On the motivation and origin of the (3n+1)-problem",
         "year": 1986, "url": _MW + "CollatzProblem.html"}],
       aliases=["3n+1"]),
    _e("Collatz Conjecture Tree",
       "c_inv(n) = {2*n, (n-1)/3 if (n-1)/3 is odd integer}",
       "root node 1",
       "Collatz reverse-tree fractal — traces 2n and (n−1)/3 preimages backward from 1; tree is conjecturally the entire set of natural numbers. Self-similar visualisation.",
       [{"author": "J. C. Lagarias",
         "title": "The 3x+1 problem and its generalisations",
         "year": 1985, "url": "https://doi.org/10.2307/2322189",
         "doi": "10.2307/2322189"}]),
    _e("Continued Fraction Fractal",
       "x = a_0 + 1/(a_1 + 1/(a_2 + ...)); plot orbit of (a_0, a_1, ...)",
       "x irrational in [0,1]",
       "Continued fraction fractal — partial-quotient sequence of irrational x is Gauss-mapped. The sequence distribution follows the Gauss-Kuzmin law with fractal structure for periodic/eventually-periodic quadratic irrationals.",
       [{"author": "A. Y. Khinchin", "title": "Continued fractions",
         "year": 1935, "url": _MW + "ContinuedFraction.html"}],
       aliases=["continued fraction"]),
    _e("Gauss Map Fractal",
       "T(x) = 1/x mod 1",
       "x in (0,1)",
       "Gauss map T(x) = {1/x} — shifts partial quotients of continued fraction; its invariant measure is the Gauss measure dμ = dx/((1+x) ln 2). Fractal orbit structure.",
       [{"author": "C. F. Gauss", "title": "Disquisitiones Arithmeticae",
         "year": 1801, "url": _MW + "GaussMap.html"}]),
    _e("Thue-Morse Sequence",
       "t_n = number of 1s in binary(n) mod 2; sequence 0,1,1,0,1,0,0,1,...",
       "t_0 = 0",
       "Thue-Morse sequence (Thue 1906, Morse 1921) — canonical aperiodic/cube-free 2-automatic sequence. Visualised as 1D black-white pattern or 2D via x⊕y bit. Self-similar at powers of 2.",
       [{"author": "A. Thue",
         "title": "Über unendliche Zeichenreihen",
         "year": 1906, "url": _MW + "Thue-MorseSequence.html"}],
       aliases=["Thue-Morse"]),
    _e("Thue-Morse 2D Heatmap",
       "T2(x, y) = (popcount(x) + popcount(y)) mod 2",
       "(x, y) in {0..2^n-1}^2",
       "Thue-Morse 2D heatmap — bit-wise parity of x⊕y over a square grid; produces nested-Sierpinski-like 2D fractal of depth log₂(grid size).",
       [{"author": "M. Morse", "title": "Recurrent geodesics on a surface of negative curvature",
         "year": 1921, "url": "https://doi.org/10.1090/S0002-9947-1921-1501161-8",
         "doi": "10.1090/S0002-9947-1921-1501161-8"}]),
    _e("Rudin-Shapiro Sequence",
       "rs_n = (-1)^(count_11(binary(n))); sequence +1,+1,+1,-1,+1,+1,-1,+1,...",
       "rs_0 = 1",
       "Rudin-Shapiro sequence — 2-automatic sequence whose partial sums are bounded by sqrt(2n). Power spectrum is flat (Shapiro sequence).",
       [{"author": "H. S. Shapiro",
         "title": "Extremal problems for polynomials and power series",
         "year": 1951, "url": _MW + "Rudin-ShapiroSequence.html"}],
       aliases=["Rudin-Shapiro"]),
    _e("Look-and-Say Sequence Fractal",
       "LAS(s) = describe_digits(s); e.g. '1223' -> '112213'",
       "seed = '1'",
       "Conway's look-and-say sequence — digit-lengths follow Conway's cosmological theorem (22 'atoms'); visualising nth term lengths gives asymptotic λ ≈ 1.30357 self-similar growth.",
       [{"author": "J. H. Conway", "title": "The weird and wonderful chemistry of audioactive decay",
         "year": 1987, "url": _MW + "Look-and-SaySequence.html"}],
       aliases=["audioactive"]),
    _e("Kolakoski Sequence",
       "k_n such that run-length encoding of sequence equals sequence itself",
       "seed = (1, 2, 2, 1, 1, 2, ...)",
       "Kolakoski sequence — self-describing sequence over {1,2} where run-lengths reproduce the sequence. Asymptotic density conjectured to be 1/2 but unproven.",
       [{"author": "W. Kolakoski",
         "title": "Self-generating runs",
         "year": 1965, "url": _MW + "KolakoskiSequence.html"}]),
    _e("Fibonacci Word Fractal",
       "F(n): F_1 = B, F_2 = A, F_{n+1} = F_n + F_{n-1}; draw segment L turn +/-",
       "seed F_1 = B",
       "Fibonacci word fractal — turtle-graphics render of the infinite Fibonacci word (A,B,A,A,B,A,B,...) produces self-similar curve related to golden-ratio scaling.",
       [{"author": "A. Monnerot-Dumaine",
         "title": "The Fibonacci word fractal",
         "year": 2009, "url": "https://hal.archives-ouvertes.fr/hal-00367972"}],
       aliases=["Fibonacci word"]),
    _e("Prouhet-Thue-Morse Curve",
       "turn_direction = thue_morse(n); draw fixed-length segments with 60 deg turns",
       "start at origin",
       "Prouhet-Thue-Morse curve — turtle-graphics drawing using Thue-Morse sequence to determine turn directions; produces self-similar curve with PTM fractal dimension.",
       [{"author": "G. Allouche, J. Shallit",
         "title": "Automatic sequences: theory, applications, generalizations",
         "year": 2003, "url": "https://doi.org/10.1017/CBO9780511546563"}]),
    _e("Pisot Plastic Number",
       "P: x**3 = x + 1, P ≈ 1.3247179572...",
       "cubic Pisot number",
       "Plastic number ρ (Dom. van der Laan 1928) — the smallest Pisot-Vijayaraghavan number. Its fractal substitution tiling is 2-dimensional.",
       [{"author": "D. van der Laan",
         "title": "The plastic number",
         "year": 1928, "url": _MW + "PlasticNumber.html"}],
       aliases=["Plastic number"]),
    _e("Tribonacci Constant Fractal",
       "T: x**3 = x**2 + x + 1, T ≈ 1.8392867552...",
       "cubic Pisot number",
       "Tribonacci constant — dominant root of x³=x²+x+1; boundary of Rauzy fractal has fractal dimension related to tribonacci substitution.",
       [{"author": "G. Rauzy", "title": "Nombres algébriques et substitutions",
         "year": 1982, "url": "https://doi.org/10.24033/bsmf.1957",
         "doi": "10.24033/bsmf.1957"}],
       aliases=["Tribonacci"]),
    _e("Beta-Expansion Fractal (phi)",
       "beta-expansion(x, phi): x = sum_k a_k * phi**(-k), a_k in {0,1}",
       "phi = golden ratio",
       "Beta-expansion fractal with β = φ — Parry-Renyi expansions in non-integer base φ produce fractal number systems with golden-ratio self-similarity.",
       [{"author": "W. Parry",
         "title": "On the β-expansions of real numbers",
         "year": 1960, "url": "https://doi.org/10.1007/BF02020954",
         "doi": "10.1007/BF02020954"}],
       aliases=["phi expansion"]),
    _e("Beta-Expansion Fractal (sqrt2)",
       "beta-expansion(x, sqrt(2)): x = sum_k a_k * 2**(-k/2), a_k in {0,1,2}",
       "beta = sqrt(2)",
       "Beta-expansion in β=√2 — silver-ratio base number system; support of invariant measure is a Cantor-like fractal.",
       [{"author": "A. Renyi",
         "title": "Representations for real numbers and their ergodic properties",
         "year": 1957, "url": "https://doi.org/10.4064/aa-8-4-477-493",
         "doi": "10.4064/aa-8-4-477-493"}]),
    _e("p-adic Fractal (p=3)",
       "distance_3(a,b) = 3**(-v_3(a-b)) where v_3 is 3-adic valuation",
       "Z_3 p-adic integers",
       "3-adic fractal — ternary tree of p-adic integers Z_3 with ultrametric 3^{-v_3}. Cantor-set topology; visualisation of algebraic number closure is fractal.",
       [{"author": "K. Hensel", "title": "Theorie der algebraischen Zahlen",
         "year": 1908, "url": _MW + "p-adicNumber.html"}]),
    _e("p-adic Fractal (p=5)",
       "distance_5(a,b) = 5**(-v_5(a-b)) where v_5 is 5-adic valuation",
       "Z_5 p-adic integers",
       "5-adic fractal — analogue of 3-adic case with quinary expansion. Visualises completions of Q under non-archimedean metric.",
       [{"author": "Y. A. Katznelson",
         "title": "An introduction to harmonic analysis",
         "year": 1968, "url": _MW + "p-adicNumber.html"}]),
    _e("Eisenstein Integer Lattice Fractal",
       "E = {a + b*omega | a, b in Z}; omega = exp(2*pi*i/3)",
       "lattice in C",
       "Eisenstein integers — triangular lattice Z[ω] with ω=e^(2πi/3). Ideal primes partition the plane into self-similar rosettes; class-field fractals emerge.",
       [{"author": "G. Eisenstein",
         "title": "Genaue Untersuchung der unendlichen Doppelproducte",
         "year": 1844, "url": _MW + "EisensteinInteger.html"}]),
    _e("Gaussian Integer Lattice Fractal",
       "G = {a + b*i | a, b in Z}; Gaussian primes",
       "square lattice in C",
       "Gaussian primes forming fractal pattern — primes in Z[i] exhibit 8-fold symmetry and form a fractal-like irregular distribution.",
       [{"author": "C. F. Gauss",
         "title": "Disquisitiones Arithmeticae",
         "year": 1801, "url": _MW + "GaussianInteger.html"}],
       aliases=["Gaussian primes"]),
    _e("Pascal Triangle Mod 2",
       "P(n, k) mod 2 = bitand((n-k) k == 0 ? 1 : 0) ; Lucas' theorem",
       "P(0,0) = 1",
       "Pascal's triangle mod 2 = Sierpinski triangle — by Lucas' theorem C(n,k) is odd iff (n-k)&k = 0. Classical number-theoretic fractal identity.",
       [{"author": "E. Lucas", "title": "Théorie des Fonctions Numériques Simplement Périodiques",
         "year": 1878, "url": _MW + "LucasTheorem.html"}]),
    _e("Pascal Triangle Mod 3",
       "P(n,k) mod 3 via Lucas; produces 3-ary Sierpinski-like triangle",
       "P(0,0) = 1",
       "Pascal's triangle mod 3 — Lucas' theorem with base 3 gives ternary Sierpinski-like fractal with 3 colours.",
       [{"author": "E. Lucas", "title": "Sur les congruences des nombres eulériens",
         "year": 1878, "url": _MW + "LucasTheorem.html"}]),
    _e("Pascal Triangle Mod 5",
       "P(n,k) mod 5 via Lucas theorem base 5",
       "P(0,0) = 1",
       "Pascal's triangle mod 5 — quinary analogue; base-5 Lucas factorisation produces 5-ary self-similar triangle.",
       [{"author": "E. Lucas", "title": "Théorie des Fonctions Numériques",
         "year": 1878, "url": _MW + "LucasTheorem.html"}]),
    _e("Rauzy Fractal (Substitution)",
       "sub: a -> ab, b -> ac, c -> a; project abelianisation onto contracting eigenplane",
       "seed a",
       "Rauzy fractal (1982) — 2D fractal tile arising from the tribonacci substitution, tiling the plane under lattice translations. Self-similar with tribonacci-ratio scaling.",
       [{"author": "G. Rauzy", "title": "Nombres algébriques et substitutions",
         "year": 1982, "url": "https://doi.org/10.24033/bsmf.1957",
         "doi": "10.24033/bsmf.1957"}],
       aliases=["Rauzy"]),
    _e("Recamán's Sequence",
       "a(n) = a(n-1) - n if a(n-1) - n > 0 and not yet visited, else a(n-1) + n",
       "a(0) = 0",
       "Recamán's sequence (OEIS A005132) — visiting integers along ± n steps avoiding repeats. Turtle-graphics drawing produces a striking nested-semicircle fractal.",
       [{"author": "B. Recamán", "title": "Sequence A005132",
         "year": 1991, "url": _OEIS + "/A005132"}],
       aliases=["Recaman"]),
    _e("Ulam Spiral",
       "spiral_walk(1, 2, 3, ...) mark n if n prime",
       "origin (0,0)",
       "Ulam spiral — spiraling integers with primes marked shows diagonal-line patterns connecting prime-generating quadratics (e.g. Euler's n²+n+41).",
       [{"author": "S. M. Ulam",
         "title": "A visual display of some properties of the distribution of primes",
         "year": 1964, "url": _MW + "PrimeSpiral.html"}],
       aliases=["Ulam spiral"]),
    _e("Sacks Spiral",
       "sacks(n) = (sqrt(n) * cos(2*pi*sqrt(n)), sqrt(n) * sin(2*pi*sqrt(n)))",
       "plot n=1,2,3,...",
       "Sacks spiral (1994) — Archimedean-like spiral placing squares on radial arms; primes form striking curved loci.",
       [{"author": "R. Sacks", "title": "Number spiral",
         "year": 1994, "url": "http://www.numberspiral.com/"}]),
    _e("Goldbach Partitions Fractal",
       "G(n) = number of ways n = p + q with p,q prime",
       "n = even integers",
       "Goldbach partitions — G(n) plotted vs even n shows the Goldbach comet fractal cloud whose envelope follows n/log(n)².",
       [{"author": "C. Goldbach", "title": "Letter to Euler",
         "year": 1742, "url": _MW + "GoldbachConjecture.html"}]),
    _e("Euler Totient Fractal",
       "phi(n) = |{k in [1,n] | gcd(k,n) = 1}|",
       "n = 1,2,3,...",
       "Euler totient function fractal — totient ratio φ(n)/n vs n produces fractal Farey-like self-similar bands.",
       [{"author": "L. Euler", "title": "Theoremata arithmetica nova methodo demonstrata",
         "year": 1763, "url": _MW + "TotientFunction.html"}]),
    _e("Mobius Function Fractal",
       "mu(n) = (-1)^k if n is squarefree with k primes, else 0",
       "n = 1,2,3,...",
       "Möbius function μ(n) 2D visualisation — cumulative Mertens function M(n) plotted vs n has conjectured growth |M(n)| ≤ n^(1/2+ε) tied to the Riemann hypothesis; fractal fluctuations.",
       [{"author": "A. F. Möbius", "title": "Über eine besondere Art von Umkehrung der Reihen",
         "year": 1832, "url": _MW + "MoebiusFunction.html"}]),
]


def main() -> None:
    run_family(BATCH_ID, FAMILY, TABLE)


if __name__ == "__main__":
    main()
