import 'package:flutter_fractals/core/modules/builders/escape_time_builder.dart';

/// IFS (Iterated Function System) and Geometric Fractals.
///
/// Fractals generated through geometric transformations and iterated
/// function systems including Sierpinski variants, Koch curves, and more.

final List<EscapeTimeConfig> ifsGeometricEntries = [
  EscapeTimeConfig(
    id: 'sierpinski_triangle',
    name: 'Sierpinski Triangle',
    shaderAsset: 'shaders/sierpinski_triangle_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
  ),
  EscapeTimeConfig(
    id: 'sierpinski_carpet',
    name: 'Sierpinski Carpet',
    shaderAsset: 'shaders/sierpinski_carpet_gpu.frag',
    defaultIterations: 100,
    defaultBailout: 4.0,
  ),
  EscapeTimeConfig(
    id: 'koch_snowflake',
    name: 'Koch Snowflake',
    shaderAsset: 'shaders/koch_snowflake_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 6.0,
  ),
  EscapeTimeConfig(
    id: 'dragon_curve',
    name: 'Dragon Curve',
    shaderAsset: 'shaders/dragon_curve_gpu.frag',
    defaultIterations: 140,
    defaultBailout: 8.0,
  ),
  EscapeTimeConfig(
    id: 'barnsley_fern',
    name: 'Barnsley Fern',
    shaderAsset: 'shaders/barnsley_fern_gpu.frag',
    defaultIterations: 120,
    defaultCenterY: 0.2,
    defaultBailout: 6.0,
  ),
  EscapeTimeConfig(
    id: 'pythagorean_tree',
    name: 'Pythagorean Tree',
    shaderAsset: 'shaders/pythagorean_tree_gpu.frag',
    defaultIterations: 120,
    defaultCenterY: -0.15,
    defaultBailout: 6.0,
  ),
  EscapeTimeConfig(
    id: 'hilbert_curve',
    name: 'Hilbert Curve',
    shaderAsset: 'shaders/hilbert_curve_gpu.frag',
    defaultIterations: 160,
    defaultBailout: 4.0,
  ),
  EscapeTimeConfig(
    id: 'peano_curve',
    name: 'Peano Curve',
    shaderAsset: 'shaders/peano_curve_gpu.frag',
    defaultIterations: 140,
    defaultBailout: 4.0,
  ),
  EscapeTimeConfig(
    id: 'gosper_curve',
    name: 'Gosper Curve',
    shaderAsset: 'shaders/gosper_curve_gpu.frag',
    defaultIterations: 180,
    defaultBailout: 6.0,
  ),
  EscapeTimeConfig(
    id: 'levy_c_curve',
    name: 'Lévy C Curve',
    shaderAsset: 'shaders/levy_c_gpu.frag',
    defaultIterations: 180,
    defaultBailout: 6.0,
  ),
  EscapeTimeConfig(
    id: 'levy_tapestry',
    name: 'Lévy Tapestry',
    shaderAsset: 'shaders/levy_tapestry_gpu.frag',
    defaultIterations: 220,
    defaultBailout: 6.0,
  ),
  EscapeTimeConfig(
    id: 'golden_dragon',
    name: 'Golden Dragon',
    shaderAsset: 'shaders/golden_dragon_gpu.frag',
    defaultIterations: 170,
    defaultBailout: 8.0,
  ),
  EscapeTimeConfig(
    id: 'twin_dragon',
    name: 'Twin Dragon',
    shaderAsset: 'shaders/twin_dragon_gpu.frag',
    defaultIterations: 170,
    defaultBailout: 8.0,
  ),
  EscapeTimeConfig(
    id: 'terdragon',
    name: 'Terdragon',
    shaderAsset: 'shaders/terdragon_gpu.frag',
    defaultIterations: 170,
    defaultBailout: 8.0,
  ),
  EscapeTimeConfig(
    id: 'chair_tiling',
    name: 'Chair Tiling',
    shaderAsset: 'shaders/chair_tiling_gpu.frag',
    defaultIterations: 150,
    defaultBailout: 6.0,
  ),
  EscapeTimeConfig(
    id: 'koch_anti_snowflake',
    name: 'Koch Anti-Snowflake',
    shaderAsset: 'shaders/koch_anti_snowflake_gpu.frag',
    defaultIterations: 150,
    defaultBailout: 6.0,
  ),
  EscapeTimeConfig(
    id: 'quadratic_koch_island',
    name: 'Quadratic Koch Island',
    shaderAsset: 'shaders/quadratic_koch_gpu.frag',
    defaultIterations: 160,
    defaultBailout: 6.0,
  ),
  EscapeTimeConfig(
    id: 'cyclosorus_fern',
    name: 'Cyclosorus Fern',
    shaderAsset: 'shaders/cyclosorus_fern_gpu.frag',
    defaultIterations: 200,
    defaultCenterY: 0.2,
    defaultBailout: 6.0,
  ),
  EscapeTimeConfig(
    id: 'menger_sponge_2d',
    name: 'Menger Sponge (2D Cross-Section)',
    shaderAsset: 'shaders/menger_sponge_gpu.frag',
    defaultIterations: 140,
    defaultBailout: 4.0,
  ),
  EscapeTimeConfig(
    id: 'vicsek_fractal',
    name: 'Vicsek Fractal',
    shaderAsset: 'shaders/vicsek_gpu.frag',
    defaultIterations: 140,
    defaultBailout: 4.0,
  ),
  EscapeTimeConfig(
    id: 'penrose_tiling',
    name: 'Penrose Tiling (P3)',
    shaderAsset: 'shaders/penrose_tiling_gpu.frag',
    defaultIterations: 180,
    defaultBailout: 4.0,
  ),
  EscapeTimeConfig(
    id: 'fibonacci_word',
    name: 'Fibonacci Word Fractal',
    shaderAsset: 'shaders/fibonacci_word_gpu.frag',
    defaultIterations: 160,
    defaultBailout: 4.0,
  ),
  EscapeTimeConfig(
    id: 'rauzy_fractal',
    name: 'Rauzy Fractal',
    shaderAsset: 'shaders/rauzy_gpu.frag',
    defaultIterations: 200,
    defaultBailout: 4.0,
  ),
  EscapeTimeConfig(
    id: 'pinwheel_tiling',
    name: 'Pinwheel Tiling',
    shaderAsset: 'shaders/pinwheel_gpu.frag',
    defaultIterations: 180,
    defaultBailout: 4.0,
  ),
  EscapeTimeConfig(
    id: 'z_order_curve',
    name: 'Z-Order Curve (Morton)',
    shaderAsset: 'shaders/z_order_curve_gpu.frag',
    defaultIterations: 180,
    defaultBailout: 4.0,
  ),
  EscapeTimeConfig(
    id: 'greek_cross_fractal',
    name: 'Greek Cross Fractal',
    shaderAsset: 'shaders/greek_cross_gpu.frag',
    defaultIterations: 160,
    defaultBailout: 4.0,
  ),
  EscapeTimeConfig(
    id: 'sierpinski_pentagon',
    name: 'Sierpinski Pentagon',
    shaderAsset: 'shaders/sierpinski_pentagon_gpu.frag',
    defaultIterations: 140,
    defaultBailout: 4.0,
  ),
  EscapeTimeConfig(
    id: 'hexaflake',
    name: 'Hexaflake',
    shaderAsset: 'shaders/hexaflake_gpu.frag',
    defaultIterations: 140,
    defaultBailout: 4.0,
  ),
  EscapeTimeConfig(
    id: 'pentaflake',
    name: 'Pentaflake',
    shaderAsset: 'shaders/pentaflake_gpu.frag',
    defaultIterations: 140,
    defaultBailout: 4.0,
  ),
  EscapeTimeConfig(
    id: 'cantor_dust',
    name: 'Cantor Dust',
    shaderAsset: 'shaders/cantor_dust_gpu.frag',
    defaultIterations: 160,
    defaultBailout: 4.0,
  ),
  EscapeTimeConfig(
    id: 'apollonian_gasket',
    name: 'Apollonian Gasket',
    shaderAsset: 'shaders/apollonian_gasket_gpu.frag',
    defaultIterations: 180,
    defaultBailout: 4.0,
  ),
  EscapeTimeConfig(
    id: 'ford_circles',
    name: 'Ford Circles',
    shaderAsset: 'shaders/ford_circles_gpu.frag',
    defaultIterations: 140,
    defaultBailout: 4.0,
  ),
  EscapeTimeConfig(
    id: 'steiner_chain',
    name: 'Steiner Chain',
    shaderAsset: 'shaders/steiner_chain_gpu.frag',
    defaultIterations: 160,
    defaultBailout: 4.0,
  ),
  EscapeTimeConfig(
    id: 'cesaro_fractal',
    name: 'Cesàro Fractal',
    shaderAsset: 'shaders/cesaro_gpu.frag',
    defaultIterations: 180,
    defaultBailout: 4.0,
  ),
  EscapeTimeConfig(
    id: 'cantor_set',
    name: 'Cantor Set',
    shaderAsset: 'shaders/cantor_set_gpu.frag',
    defaultIterations: 120,
    defaultBailout: 4.0,
  ),
  EscapeTimeConfig(
    id: 'fractal_canopy',
    name: 'Fractal Canopy',
    shaderAsset: 'shaders/fractal_canopy_gpu.frag',
    defaultIterations: 80,
    // Keep canopy iteration cap lower than generic escape-time modules to
    // avoid runaway branch expansion on mobile GPUs.
    maxIterations: 120,
    defaultCenterY: -0.15,
    defaultBailout: 4.0,
  ),
  EscapeTimeConfig(
    id: 'benesi',
    name: 'Benesi Fractal',
    shaderAsset: 'shaders/benesi_gpu.frag',
    defaultIterations: 220,
    defaultBailout: 8.0,
  ),
  EscapeTimeConfig(
    id: 'pseudo_kleinian',
    name: 'Pseudo-Kleinian',
    shaderAsset: 'shaders/pseudo_kleinian_gpu.frag',
    defaultIterations: 220,
    defaultBailout: 10.0,
  ),
];
